### ISSUE TITLE
The  README.txt under root folder seems out of date

### ISSUE THREAD

**Issue by duyuan11** [SeisSol/SeisSol#1]
I followed the compiling procedures in README.txt and tried more than 5 times, it would always report  "
"Checking for C library netcdf... no
Could not find netCDF!
",
I have no idea how to build SeisSol currently, I am assuming the README.txt file is not very correct. 
Could  anyone help with this?  I would appreciate!

**Comment by alheinecke** [comment]
Sure. Can you please post the config.log and other outputs of the scons build system.

Intel MPI 5.0.X has bugs in the mpiwrappers (they are not reporting the correct exit code and scons assumes that the library was not found).

Can you try without NetCDF support?

**Comment by rettenbs** [comment]
There was indeed a small mistake since the variables "cppCompiler" and "fortranCompiler" are no longer supported. If this does not help, the config.log provides detailed information about the errors.

It might also help to delete the Scons cache (rm -r .sconf_temp).

**Comment by duyuan11** [comment]
Thanks very much for your response! 


The config.log is
---------------------------------------------------------------------------------------------------------------------
file /home/william/Desktop/SeisSol/build/scons/Tools/MPITool.py,line 81:
	Configure(confdir = .sconf_temp)
scons: Configure: Checking for mpicxx... 
mpicxx --version
g++ (Ubuntu 4.8.2-19ubuntu1) 4.8.2
Copyright (C) 2013 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

scons: Configure: yes

scons: Configure: Checking for mpicc... 
mpicc --version
gcc (Ubuntu 4.8.2-19ubuntu1) 4.8.2
Copyright (C) 2013 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

scons: Configure: yes

scons: Configure: Checking for mpicxx... 
mpicxx --version
g++ (Ubuntu 4.8.2-19ubuntu1) 4.8.2
Copyright (C) 2013 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

scons: Configure: yes

scons: Configure: Checking for mpif90... 
mpif90 --version
GNU Fortran (Ubuntu 4.8.2-19ubuntu1) 4.8.2
Copyright (C) 2013 Free Software Foundation, Inc.

GNU Fortran comes with NO WARRANTY, to the extent permitted by law.
You may redistribute copies of GNU Fortran
under the terms of the GNU General Public License.
For more information about these matters, see the file named COPYING

scons: Configure: yes


file /home/william/Desktop/SeisSol/build/scons/Tools/NetcdfTool.py,line 76:
	Configure(confdir = .sconf_temp)
scons: Configure: Checking for C library netcdf... 
.sconf_temp/conftest_4.c <-
  |
  |
  |#include "netcdf_par.h"
  |
  |int
  |main() {
  |  
  |return 0;
  |}
  |
mpicc -o .sconf_temp/conftest_4.o -c -Wall -Werror -ansi -xCORE-AVX2 -fma -O2 -fopenmp -DOMPI_SKIP_MPICXX -DALIGNMENT=32 -DDHSW -DNDEBUG -DCONVERGENCE_ORDER=6 -DNUMBER_OF_QUANTITIES=9 -DNUMBER_OF_RELAXATION_MECHANISMS=0 -DNUMBER_OF_TEMPORAL_INTEGRATION_POINTS=1 -DPARALLEL -DUSE_MPI -DOMP -DGENERATEDKERNELS -DCLUSTERED_LTS -DLOGLEVEL=1 -DLOGLEVEL0=2 -DLOG_LEVEL=2 -Isubmodules -I/home/william/Desktop/InstallPools/netcdf-4.3.3.1/netcdfInstallDir/include -I/home/william/Desktop/InstallPools/ZLIB-HDF-install-dir/include .sconf_temp/conftest_4.c
.sconf_temp/conftest_4.c(3): catastrophic error: cannot open source file "netcdf_par.h"
  #include "netcdf_par.h"
                         ^

compilation aborted for .sconf_temp/conftest_4.c (code 4)
scons: Configure: no

-------------------------------------------------------------------------------------------------------------------------

I am using the command in my PC (i7-4770) as 

scons -f SConstruct_generatedKernels buildVariablesFile=build/options/supermuc_mac_cluster.py compileMode=release arch=dhsw numberOfTemporalIntegrationPoints=1 compiler=intel  order=6 generatedKernels=yes netcdf=yes netcdfDir=/home/william/Desktop/InstallPools/netcdf-4.3.3.1/netcdfInstallDir hdf5Dir=/home/william/Desktop/InstallPools/ZLIB-HDF-install-dir -j 32 


My netcdf, HDF and zlib work well for me to use GMT (Generic Mapping Tools), but seem not work here.

**Comment by rettenbs** [comment]
The problem is hidden in the last lines:

.sconf_temp/conftest_4.c(3): catastrophic error: cannot open source file "netcdf_par.h"
#include "netcdf_par.h"

You need a netCDF version with supports parallel I/O. There is also some help in the Readme about parallel HDF5/netCDF.

Since netCDF is currently only required to load special optimized mesh files you can also use SeisSol without enabling netCDF.
