### ISSUE TITLE
error related to pspammsparse_xxx subroutines

### ISSUE THREAD

**Issue by daisy20170101** [SeisSol/SeisSol#100]
Compilation on NG broke due to:
/usr/lib64/gcc/x86_64-suse-linux/4.8/../../../../x86_64-suse-linux/bin/ld: build/build_release_generatedKernels_dskx_hybrid_none_9_4/generated_code/kernel.o: in function `seissol::kernel::addVelocity::execute()':
kernel.cpp:(.text+0x43b4): undefined reference to `pspammsparse_e60658f2bd24617a41c922e81bd775a8_m24_n3_k3_ldA24_ldB0_ldC24_alpha1_beta1_alignedA1_alignedC1_pfsigonly(double const*, double const*, double*, double, double, double const*)'
/usr/lib64/gcc/x86_64-suse-linux/4.8/../../../../x86_64-suse-linux/bin/ld: build/build_release_generatedKernels_dskx_hybrid_none_9_4/generated_code/kernel.o: in function `seissol::kernel::subTriangleVelocity::execute0()':
kernel.cpp:(.text+0x604e): undefined reference to `pspammsparse_e60658f2bd24617a41c922e81bd775a8_m8_n3_k3_ldA8_ldB0_ldC8_alpha1_beta0_alignedA1_alignedC1_pfsigonly(double const*, double const*, double*, double, double, double const*)'
/usr/lib64/gcc/x86_64-suse-linux/4.8/../../../../x86_64-suse-linux/bin/ld: build/build_release_generatedKernels_dskx_hybrid_none_9_4/generated_code/kernel.o: in function `seissol::kernel::subTriangleVelocity::execute1()':
kernel.cpp:(.text+0x60ae): undefined reference to `pspammsparse_e60658f2bd24617a41c922e81bd775a8_m8_n3_k3_ldA8_ldB0_ldC8_alpha1_beta0_alignedA1_alignedC1_pfsigonly(double const*, double const*, double*, double, double, double const*)'
/usr/lib64/gcc/x86_64-suse-linux/4.8/../../../../x86_64-suse-linux/bin/ld: build/build_release_generatedKernels_dskx_hybrid_none_9_4/generated_code/kernel.o: in function `seissol::kernel::subTriangleVelocity::execute2()':
kernel.cpp:(.text+0x610e): undefined reference to `pspammsparse_e60658f2bd24617a41c922e81bd775a8_m16_n3_k3_ldA16_ldB0_ldC16_alpha1_beta0_alignedA1_alignedC1_pfsigonly(double const*, double const*, double*, double, double, double const*)'
/usr/lib64/gcc/x86_64-suse-linux/4.8/../../../../x86_64-suse-linux/bin/ld: build/build_release_generatedKernels_dskx_hybrid_none_9_4/generated_code/kernel.o: in function `seissol::kernel::subTriangleVelocity::execute3()':
kernel.cpp:(.text+0x6155): undefined reference to `pspammsparse_e60658f2bd24617a41c922e81bd775a8_m24_n3_k3_ldA24_ldB0_ldC24_alpha1_beta0_alignedA1_alignedC1_pfsigonly(double const*, double const*, double*, double, double, double const*)'

I couldn't find the definition of subroutines pspammsparse_xxx, which are defined in subroutine.h but not in subroutine.cpp. Wondering if this is a problem.

**Comment by Thomas-Ulrich** [comment]
kind of a follow up issue of #95

**Comment by uphoffc** [comment]
No that's not related to #95.

The subroutines are located in build/build_release_generatedKernels_dskx_hybrid_none_9_4/generated_code/subroutine.cpp, if they exist.
If they do not exist, then the file pspamm.py was not found in the PATH during compilation. However, in that case you should have got the following error:

`RuntimeError: GEMM code generator executable "pspamm.py" not found. (Make sure to add the folder containing the executable to your PATH.)`

**Comment by daisy20170101** [comment]
While I have added pspamm.py to PATH. Here what I have 

usage: pspamm.py [-h] [--bm BM] [--bn BN] [--bk BK] [--arch ARCH]
                 [--precision PRECISION] [--prefetching PREFETCHING]
                 [--mtx_filename MTX_FILENAME]
                 [--mtx_format {any,csc,csr,bsc,bsr,bcsc,bcsr}]
                 [--output_funcname OUTPUT_FUNCNAME]
                 [--output_filename OUTPUT_FILENAME] [--output_overwrite]
                 m n k lda ldb ldc alpha beta



But I don't have any pspamm_xxxx in subroutines.cpp. There are only some libxsmm_xxx in subroutines.cpp.

**Comment by daisy20170101** [comment]
Hi 
Is there any clue of these?

**Comment by uphoffc** [comment]
Have you tried cleaning / building SeisSol again?

**Comment by Thomas-Ulrich** [comment]
Hi,

So the problem is related with python/3.5_intel on supermuc NG:
```
Calling external code generators...
/lrz/sys/tools/python/intelpython35_u4/intelpython3/lib/python3.5/site-packages/numpy/core/numeric.py:301: FutureWarning: in the future, full((2, 1), -1) will return an array of dtype('int64')
  format(shape, fill_value, array(fill_value).dtype), FutureWarning)
/lrz/sys/tools/python/intelpython35_u4/intelpython3/lib/python3.5/site-packages/numpy/core/numeric.py:301: FutureWarning: in the future, full((8, 2), True) will return an array of dtype('bool')
  format(shape, fill_value, array(fill_value).dtype), FutureWarning)
/lrz/sys/tools/python/intelpython35_u4/intelpython3/lib/python3.5/site-packages/numpy/core/numeric.py:301: FutureWarning: in the future, full((8, 2), -1) will return an array of dtype('int64')
  format(shape, fill_value, array(fill_value).dtype), FutureWarning)
/lrz/sys/tools/python/intelpython35_u4/intelpython3/lib/python3.5/site-packages/numpy/core/numeric.py:301: FutureWarning: in the future, full((3, 3), -1) will return an array of dtype('int64')
  format(shape, fill_value, array(fill_value).dtype), FutureWarning)
Traceback (most recent call last):
  File "/hppfs/work/pr45fi/di73yeq4/myLibs/PSpaMM/pspamm.py", line 66, in <module>
    alg = MatMul(**args.__dict__)
  File "/hppfs/work/pr63qo/di73yeq4/myLibs/PSpaMM/matmul.py", line 161, in __init__
    self.B = BlockCursor("B", self.starting_regs[1], self.k, self.n, self.ldb, self.bk, self.bn, self.precision.value, blocks, patterns,mtx_overhead)
  File "/hppfs/work/pr63qo/di73yeq4/myLibs/PSpaMM/cursors/blockcursor.py", line 45, in __init__
    pattern = patterns[index]   
TypeError: list indices must be integers or slices, not numpy.float64
```
with python/3.6_intel everything works fine.

**Comment by krenzland** [comment]
I thought that with 3.6 you get issues with the tornado library? (according to #94)

**Comment by Thomas-Ulrich** [comment]
yes but there is an easy fix for #94:
pip install --user tornado-3.2.1.tar.gz

**Comment by daisy20170101** [comment]
Thanks for updating this @Thomas-Ulrich 
It seems that python3.5 doesn't work now.

**Comment by daisy20170101** [comment]
Should we confirm this and update our doc ?

**Comment by daisy20170101** [comment]
This can be closed as it is fixed
