### ISSUE TITLE
Trying to compile with Spack seissol-env environment

### ISSUE THREAD

**Issue by markyoder** [SeisSol/SeisSol#1032]
**Describe the bug**
Trying to compile SiesSol (again...) with the Spack environment.
I ran into some versioning issues, so I removed all of the upper version restrictions -- at least as a starting point.

Now, I cannot get past this CMAKE error.  My CMake-foo is a bit weak, but happy to help recode the CMake configuration, with a little direction, if that will help.

Here is my error:

```
-- The C compiler identification is GNU 12.1.0
-- The CXX compiler identification is GNU 12.1.0
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - failed
-- Check for working C compiler: /home/groups/sh_s-dss/share/sdss/spack_sdss/spack/opt/spack/linux-centos7-x86_64/gcc-12.1.0/mpich-4.1.2-qnrmqaht675xnjknscb2hduhro6t7rlv/bin/mpicc
-- Check for working C compiler: /home/groups/sh_s-dss/share/sdss/spack_sdss/spack/opt/spack/linux-centos7-x86_64/gcc-12.1.0/mpich-4.1.2-qnrmqaht675xnjknscb2hduhro6t7rlv/bin/mpicc - broken
CMake Error at /home/groups/sh_s-dss/share/sdss/spack_sdss/spack/opt/spack/linux-centos7-x86_64/gcc-12.1.0/cmake-3.27.9-tycy64q26clfs4xoferhrm2zats3f3nv/share/cmake-3.27/Modules/CMakeTestCCompiler.cmake:67 (message):
  The C compiler

    "/home/groups/sh_s-dss/share/sdss/spack_sdss/spack/opt/spack/linux-centos7-x86_64/gcc-12.1.0/mpich-4.1.2-qnrmqaht675xnjknscb2hduhro6t7rlv/bin/mpicc"

  is not able to compile a simple test program.

  It fails with the following output:

    Change Dir: '/scratch/users/myoder96/seissol/SeisSol/build/CMakeFiles/CMakeScratch/TryCompile-1794oZ'
    
    Run Build Command(s): /home/groups/sh_s-dss/share/sdss/spack_sdss/spack/opt/spack/linux-centos7-x86_64/gcc-12.1.0/cmake-3.27.9-tycy64q26clfs4xoferhrm2zats3f3nv/bin/cmake -E env VERBOSE=1 /usr/bin/gmake -f Makefile cmTC_b0cb8/fast
    /usr/bin/gmake  -f CMakeFiles/cmTC_b0cb8.dir/build.make CMakeFiles/cmTC_b0cb8.dir/build
    gmake[1]: Entering directory `/scratch/users/myoder96/seissol/SeisSol/build/CMakeFiles/CMakeScratch/TryCompile-1794oZ'
    Building C object CMakeFiles/cmTC_b0cb8.dir/testCCompiler.c.o
    /home/groups/sh_s-dss/share/sdss/spack_sdss/spack/opt/spack/linux-centos7-x86_64/gcc-12.1.0/mpich-4.1.2-qnrmqaht675xnjknscb2hduhro6t7rlv/bin/mpicc    -o CMakeFiles/cmTC_b0cb8.dir/testCCompiler.c.o -c /scratch/users/myoder96/seissol/SeisSol/build/CMakeFiles/CMakeScratch/TryCompile-1794oZ/testCCompiler.c
    Linking C executable cmTC_b0cb8
    /home/groups/sh_s-dss/share/sdss/spack_sdss/spack/opt/spack/linux-centos7-x86_64/gcc-12.1.0/cmake-3.27.9-tycy64q26clfs4xoferhrm2zats3f3nv/bin/cmake -E cmake_link_script CMakeFiles/cmTC_b0cb8.dir/link.txt --verbose=1
    /home/groups/sh_s-dss/share/sdss/spack_sdss/spack/opt/spack/linux-centos7-x86_64/gcc-12.1.0/mpich-4.1.2-qnrmqaht675xnjknscb2hduhro6t7rlv/bin/mpicc CMakeFiles/cmTC_b0cb8.dir/testCCompiler.c.o -o cmTC_b0cb8 
    /home/groups/sh_s-dss/share/sdss/spack_sdss/spack/opt/spack/linux-centos7-x86_64/gcc-12.1.0/binutils-2.41-v6vluhmzqckxg5ao7hwqujn37mhgxcpq/lib/../x86_64-pc-linux-gnu/bin/ld: cannot find crtbegin.o: No such file or directory
    /home/groups/sh_s-dss/share/sdss/spack_sdss/spack/opt/spack/linux-centos7-x86_64/gcc-12.1.0/binutils-2.41-v6vluhmzqckxg5ao7hwqujn37mhgxcpq/lib/../x86_64-pc-linux-gnu/bin/ld: cannot find -lgcc: No such file or directory
    /home/groups/sh_s-dss/share/sdss/spack_sdss/spack/opt/spack/linux-centos7-x86_64/gcc-12.1.0/binutils-2.41-v6vluhmzqckxg5ao7hwqujn37mhgxcpq/lib/../x86_64-pc-linux-gnu/bin/ld: cannot find -lgcc: No such file or directory
    collect2: error: ld returned 1 exit status
    gmake[1]: *** [cmTC_b0cb8] Error 1
    gmake[1]: Leaving directory `/scratch/users/myoder96/seissol/SeisSol/build/CMakeFiles/CMakeScratch/TryCompile-1794oZ'
    gmake: *** [cmTC_b0cb8/fast] Error 2
    
    

  

  CMake will not be able to correctly generate this project.
Call Stack (most recent call first):
  CMakeLists.txt:12 (project)
```

**Expected behavior**
I expect SesisSol to compile.

*To Reproduce**
Happy to provide as much of this as you need. But basically, I git-clone the seissol-spack-aid repo; tweak the recipe here and there until it will install (basically, some of the upper version restrictions conflict with new packages and package recipes).
Follow the CMake instructions

be frustrated...

1. Which version do you use? Provide branch and commit id.
2. Which build settings do you use? Which compiler version do you use? 
3. On which machine does your problem occur? If on a cluster: Which modules are loaded?
4. Provide parameter/material files.

**Screenshots/Console output**
If you suspect a problem in the numerics/physics add a screenshot of your output.

If you encounter any errors/warnings/... during execution please provide the console output.

**Additional context**

**Comment by Thomas-Ulrich** [comment]
did you load seissol-env (either with spack or as a module before starting the install?).
Did you also think of loading the compiler?

you can try also to compile directly a seissol package, and not seissol-env, with this branch: https://github.com/spack/spack/pull/41176
e.g.

`git fetch origin pull/41176/head:seissol` within the spack repository, and then install with:

```spack install -j 60 seissol@master convergence_order=4 dr_quad_rule=dunavant equations=elastic precision=single```

**Comment by markyoder** [comment]
Yes, I have a compiler loaded. Yes, I load seissol-env as an LMOD module.
Yes, CMake still breaks.

I'll have a look at your git + spack sequence, though I am having better
luck by just building the environment manually, from the known dependencies.

I am, however running into this error:
```

                 from
*/scratch/users/myoder96/seissol/SeisSol/src/Initializer/time_stepping/LtsLayout.cpp:48*
:

*/scratch/users/myoder96/seissol/SeisSol/src/Monitoring/LoopStatistics.h:44:10:*
*fatal
error: *bits/types/struct_timespec.h: No such file or directory

   44 | #include *<bits/types/struct_timespec.h>*

      |          *^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~*
```

And cannot figure out where to find struct_timespec.h . Any ideas?


Mark Yoder, PhD
805 451 8750
*www.linkedin.com/in/Mark-R-Yoder-PhD
<http://www.linkedin.com/in/Mark-R-Yoder-PhD>*

"Difficulties are just things to overcome, after all."
~E. Shackleton

**Comment by davschneller** [comment]
That include line is a bug that got fixed in #1018. Can you do a `git pull` again? Then the error should disappear.

**Comment by markyoder** [comment]
Yeah, ok. I thought I was working from a fresh pull. Is there a branch or
tag I should be targeting?

m

Mark Yoder, PhD
805 451 8750
*www.linkedin.com/in/Mark-R-Yoder-PhD
<http://www.linkedin.com/in/Mark-R-Yoder-PhD>*

"Difficulties are just things to overcome, after all."
~E. Shackleton

**Comment by davschneller** [comment]
Currently, the master branch should be good. (it's basically identical to v1.1.3 at the moment)

**Comment by markyoder** [comment]
Ok. Can I just disable the compiler test in CMake? if, yes... how do I do
that? I was getting past that Cmake and into the compile phase before I did
the `git pull`

m

Mark Yoder, PhD
805 451 8750
*www.linkedin.com/in/Mark-R-Yoder-PhD
<http://www.linkedin.com/in/Mark-R-Yoder-PhD>*

"Difficulties are just things to overcome, after all."
~E. Shackleton

**Comment by markyoder** [comment]
Yup. Using the MPI compilers for CC and CXX, as the CMake error suggests.

`mpicc -show` gives:

```

***@***.*** /scratch/users/myoder96/seissol] *(job 40453794)* $
mpicc -show

/share/software/user/open/gcc/12.1.0/bin/gcc
-I/home/groups/sh_s-dss/share/sdss/spack_sdss/spack/opt/spack/linux-centos7-x86_64/gcc-12.1.0/mpich-4.1.2-yro4vuxroxx4yegqzdtyl5xqvctyvg7a/include
-L/home/groups/sh_s-dss/share/sdss/spack_sdss/spack/opt/spack/linux-centos7-x86_64/gcc-12.1.0/mpich-4.1.2-yro4vuxroxx4yegqzdtyl5xqvctyvg7a/lib
-Wl,-rpath
-Wl,/home/groups/sh_s-dss/share/sdss/spack_sdss/spack/opt/spack/linux-centos7-x86_64/gcc-12.1.0/mpich-4.1.2-yro4vuxroxx4yegqzdtyl5xqvctyvg7a/lib
-lmpi
```
so ***@***.*** . Is there a way to mash a
-L/share/software/user/open/gcc/12.1.0/lib
in there? Based on the error, it seems that would fix the compiler error
(he said, crossing his fingers).

m

Mark Yoder, PhD
805 451 8750
*www.linkedin.com/in/Mark-R-Yoder-PhD
<http://www.linkedin.com/in/Mark-R-Yoder-PhD>*

"Difficulties are just things to overcome, after all."
~E. Shackleton

**Comment by markyoder** [comment]
might be something corrupting on my side. Starting to look like a Monday
morning problem!

m

Mark Yoder, PhD
805 451 8750
*www.linkedin.com/in/Mark-R-Yoder-PhD
<http://www.linkedin.com/in/Mark-R-Yoder-PhD>*

"Difficulties are just things to overcome, after all."
~E. Shackleton

**Comment by markyoder** [comment]
Maybe this is somehow related to using RPATH vs LD_LIBRARY_PATH, etc. to
satisfy dependencies? Or generally, somehow the LD_LIBRARY_PATH, etc.
variables are being overridden or ignored -- I was recently discussing this
issue in other applications. In this case, I can do something like:

#SET(CMAKE_C_COMPILER_WORKS 1 CACHE INTERNAL "")

#SET(CMAKE_CXX_COMPILER_WORKS 1 CACHE INTERNAL "")


to skip the compiler test, but then it breaks down the way for what looks
like the same reason, but now it can't find OpenMP.

I am happy to work around the problem -- what variables can we set to force
CMake to find those libraries?


Mark Yoder, PhD
805 451 8750
*www.linkedin.com/in/Mark-R-Yoder-PhD
<http://www.linkedin.com/in/Mark-R-Yoder-PhD>*

"Difficulties are just things to overcome, after all."
~E. Shackleton

**Comment by markyoder** [comment]
Ok. Thanks so much for bouncing some of these ideas back to me. It looks
like the problem lies with one or more LMOD module stepping on another LMOD
Module; I think something to do with the way Spack writed the gcc and/or
binutils modules.

So... it looks like I can get cmake to work and seissol to build with my
environment; I'll see if I can similarly tweak the seissol-aid to work.

Thanks again!

m


Mark Yoder, PhD
805 451 8750
*www.linkedin.com/in/Mark-R-Yoder-PhD
<http://www.linkedin.com/in/Mark-R-Yoder-PhD>*

"Difficulties are just things to overcome, after all."
~E. Shackleton
