### ISSUE TITLE
building error

### ISSUE THREAD

**Issue by brioglade** [SeisSol/SeisSol#1034]
Generating kernels...
Calling external code generators...

wrong usage -> exit!

Usage (sparse*dense=dense, dense*sparse=dense):
    sparse, sparse_csr
    filename to append
    routine name
    M
    N
    K
    LDA (if < 1 --> A sparse)
    LDB (if < 1 --> B sparse)
    LDC
    alpha: 1
    beta: 0 or 1
    0: unaligned A, otherwise aligned (ignored for sparse)
    0: unaligned C, otherwise aligned (ignored for sparse)
    ARCH: noarch, wsm, snb, hsw, skx, clx, cpx
    PREFETCH: nopf (none), other options are not supported
    PRECISION: SP, DP
    matrix input (CSC mtx file)

Usage (dense*dense=dense):
    dense, dense_asm
    filename to append
    routine name
    M
    N
    K
    LDA
    LDB
    LDC
    alpha: -1 or 1
    beta: 0 or 1
    0: unaligned A, otherwise aligned
    0: unaligned C, otherwise aligned
    ARCH: noarch, wsm, snb, hsw, skx, clx, cpx
    PREFETCH: nopf (none), BL2viaC, AL2, curAL2,
              AL2_BL2viaC, curAL2_BL2viaC,
    PRECISION: SP, DP

Traceback (most recent call last):
  File "/home/vivlio/src/SeisSol/generated_code/generate.py", line 182, in <module>
    generator.generate(outputDir=cmdLineArgs.outputDir,
  File "/home/vivlio/src/SeisSol/generated_code/yateto/generator.py", line 378, in generate
    cache.generate(header, fRoutines.cpp, fGpulikeRoutines.cpp)
  File "/home/vivlio/src/SeisSol/generated_code/yateto/codegen/cache.py", line 39, in generate
    declaration = generator(name, cppFileName)
  File "/home/vivlio/src/SeisSol/generated_code/yateto/codegen/gemm/gemmgen.py", line 323, in __call__
    self._callGenerator(argList)
  File "/home/vivlio/src/SeisSol/generated_code/yateto/codegen/gemm/gemmgen.py", line 231, in _callGenerator
    raise RuntimeError(f"""GEMM code generator executable "{self._cmd}" failed. Thus, the kernel generation may be incomplete.
RuntimeError: GEMM code generator executable "/home/vivlio/seissol-opt/bin/libxsmm_gemm_generator" failed. Thus, the kernel generation may be incomplete.
Given command: /home/vivlio/seissol-opt/bin/libxsmm_gemm_generator dense /home/vivlio/src/SeisSol/build/src/generated_code/subroutine.cpp libxsmm_m3_n1_k3_ldA3_ldB3_ldC3_alpha1_beta0_alignedA0_alignedC0_transAFalse_transBFalse_pfsigonly 3 1 3 3 3 3 1 0 0 0 hsw pfsigonly DP
Stdout: None
Stderr: None
make[2]: *** [CMakeFiles/SeisSol-codegen.dir/build.make:96: src/generated_code/subroutine.h] Error 1
make[2]: *** Deleting file 'src/generated_code/subroutine.h'
make[1]: *** [CMakeFiles/Makefile2:119: CMakeFiles/SeisSol-codegen.dir/all] Error 2
make: *** [Makefile:136: all] Error 2

**Comment by davschneller** [comment]
Thank you for sending the error message. However, please use our provided templates for any future issues you will post.

Regarding the error message: if you use libxsmm@1.17, the error will (most likely) disappear. We right now only support libxsmm up to version 1.17—the libxsmm Github main branch is will not work at the moment, unless you use `LIBXSMM_JIT`.
