### ISSUE TITLE
Failure during installing SeisSol on Euler

### ISSUE THREAD

**Issue by palgunadi1993** [SeisSol/SeisSol#1047]
**Describe the bug**
Failure during installation when installing EnergyOutput
``
/cluster/home/kpalgunadi/myLibs/seissol-cpu/src/ResultWriter/EnergyOutput.cpp: In member function ‘void seissol::writer::EnergyOutput::computeDynamicRuptureEnergies()’:
/cluster/home/kpalgunadi/myLibs/seissol-cpu/src/ResultWriter/EnergyOutput.cpp:224:32: error: ‘timeDerivativeMinusPtr’ is predetermined ‘shared’ for ‘shared’
                waveSpeedsMinus)
                                ^
/cluster/home/kpalgunadi/myLibs/seissol-cpu/src/ResultWriter/EnergyOutput.cpp:224:32: error: ‘timeDerivativePlusPtr’ is predetermined ‘shared’ for ‘shared’
make[2]: *** [CMakeFiles/SeisSol-lib.dir/build.make:1001: CMakeFiles/SeisSol-lib.dir/src/ResultWriter/EnergyOutput.cpp.o] Error 1
make[2]: *** Waiting for unfinished jobs....
make[1]: *** [CMakeFiles/Makefile2:199: CMakeFiles/SeisSol-lib.dir/all] Error 2
make: *** [Makefile:136: all] Error 2
``
**Expected behavior**
SeisSol is compiled

**To Reproduce**
1. Which version do you use? commit 5f05d19847dd07839c313857699cdba7a4ddcf54 
2. Which build settings do you use? Which compiler version do you use? 
``CC=mpicc CXX=mpiCC FC=mpif90 ~/bin/cmake/bin/cmake -DNUMA_AWARE_PINNING=ON -DASAGI=ON -DCMAKE_BUILD_TYPE=Release -DHOST_ARCH=skx -DPRECISION=double -DORDER=4 -DGEMM_TOOLS_LIST=LIBXSMM,PSpaMM ..``
4. On which machine does your problem occur? If on a cluster: Which modules are loaded?
Euler ETH Zurich. 
Loaded modules:
``Currently Loaded Modules:
  1) StdEnv   2) gcc/8.2.0   3) openmpi/4.1.4   4) cmake/3.26.3   5) openblas/0.2.20   6) python/3.8.5

Inactive Modules:
  1) mpich
``
![Screenshot from 2024-02-09 10-49-46](https://github.com/SeisSol/SeisSol/assets/35545825/dcd1cbef-ecfc-480f-8f7e-d1917018a49a)

**Comment by davschneller** [comment]
Hi, can you try https://github.com/SeisSol/SeisSol/tree/davschneller/default-none-fix ?

GCC 8 is unfortunately a bit old—but we can try. (the problem is most likely that one here: https://www.gnu.org/software/gcc/gcc-9/porting_to.html#ompdatasharing )

**Comment by palgunadi1993** [comment]
Hi,
It seems the problem is gcc/8.2.0. It failed with your changes.
I switched to gcc/11.2.0, your patched seissol worked and compiled successfully. 
I tried with the master branch (without removing default none) using gcc/11.2.0 and it worked too.

Thank you for your help.

Best regards,
Kadek

**Comment by palgunadi1993** [comment]
I close this now.
