### ISSUE TITLE
A missing source file

### ISSUE THREAD

**Issue by ravil-mobile** [SeisSol/SeisSol#106]
https://github.com/SeisSol/SeisSol/blob/131973dfd226ef04cf452885f587f98a9f0fe39c/src/sources.cmake#L19

Please, add the following file as well: 
src/Numerical_aux/Statistics.cpp

I couldn't compiler without it

**Comment by krenzland** [comment]
There is no such file - the cmake branch is a bit behind the master. I'll update the branch and then I'll also include the file.
