### ISSUE TITLE
Patch for seissol 64 is not up-to-date

### ISSUE THREAD

**Issue by palgunadi1993** [SeisSol/SeisSol#1078]
It would be nice to update the patch for the SeisSol 64bit version. I'm struggling with the new coding as many of the variable names have changed since the last time it was updated.

### Rationale
Applying the following comment is not relevant anymore.
git apply Documentation/patchesI64/patch_SeisSol.diff

### Description

Maybe update the current implementation to the documentation/patchesI64?

### General information

- [x ] I have searched the issues of this repo and believe this is not a duplicate

Thank you for your help!

Best regards,
Kadek

**Comment by Thomas-Ulrich** [comment]
Actually, you should be able to use:
https://github.com/SeisSol/SeisSol/pull/1039
see also:
https://github.com/SeisSol/PUMGen/pull/59

**Comment by palgunadi1993** [comment]
So it should be able to run the 64 bits without adding patches?

**Comment by palgunadi1993** [comment]
Now it's solved with add a parameter specifying 64-type mesh. The documentation (the PR) for this is still under-review.

Cheers,
Kadek
