### ISSUE TITLE
What is the purpose of this structure in the source code?

### ISSUE THREAD

**Issue by ravil-mobile** [SeisSol/SeisSol#108]
https://github.com/SeisSol/SeisSol/blob/871a88ad2deb0094ea152da5e3d850ac856c2898/src/Equations/elastic/Kernels/Interface.hpp#L48

Does it relate somehow to the fact that there is a fancy macros LTSTREE_GENERATE_INTERFACE below?

**Comment by ravil-mobile** [comment]
Also, what is a purpose of passing an instance of this structure to **computeAder** and **computeIntegral** functions

/*:
 
    kernels::LocalTmp tmp;
  
    for(unsigned int l_cell = 0; l_cell < nrOfCells; l_cell++) {
        auto data = loader.entry(l_cell);
        m_timeKernel.computeAder((double)m_timeStepWidthSimulation,
                                  data,
                                  tmp,
                                  buffers[l_cell],
                                  derivatives[l_cell]);

        m_localKernel.computeIntegral(buffers[l_cell],
                                     data,
                                     tmp);
    }
 */

**Comment by krenzland** [comment]
For [viscoelasticity](https://github.com/SeisSol/SeisSol/blob/871a88ad2deb0094ea152da5e3d850ac856c2898/src/Equations/viscoelastic2/Model/datastructures.hpp)

The LTSTREE_GENERATE_INTERFACE generates a struct definition then which handles the LTSTree magic - the definition of this macro is in [this header](https://github.com/SeisSol/SeisSol/blob/871a88ad2deb0094ea152da5e3d850ac856c2898/src/Initializer/tree/InterfaceHelper.hpp).
