### ISSUE TITLE
Seissol infers the wrong boundary format

### ISSUE THREAD

**Issue by Thomas-Ulrich** [SeisSol/SeisSol#1083]
**Describe the bug**
Seissol infers the wrong boundary format for the following mesh with 
[mesh.zip](https://github.com/SeisSol/SeisSol/files/14787638/mesh.zip)
(pumlboundaryformat = 'auto')
```
Thu Mar 28 11:07:31, Info:  Inferring boundary format. 
Thu Mar 28 11:07:31, Info:  Using boundary format: i64 (4xi16) 
```
(should be i32 and it works fine if I set i32)

**To Reproduce**
1. Which version do you use? Provide branch and commit id.
master 5c163ed1f6931a3ac1e5e2ff5ca63dd97bce6c0f
2. Which build settings do you use? Which compiler version do you use? 
dhw4 elastic
3. On which machine does your problem occur? If on a cluster: Which modules are loaded?
cachemiss
```
ulrich@cachemiss:/export/dump/ulrich/tpv5$ module list
Currently Loaded Modulefiles:
 1) paraview/5.11.1                       12) zstd/1.5.5-gcc-12.2.0-d3iesv2            23) pkgconf/1.9.5-gcc-12.2.0-pdjoat6       34) python/3.9.2-gcc-12.2.0-ikw34ao                         
 2) libpciaccess/0.17-gcc-12.2.0-foegz6x  13) tar/1.34-gcc-12.2.0-344crw2              24) hdf5/1.12.2-gcc-12.2.0-xwxzdqa         35) yaml-cpp/0.6.2-gcc-12.2.0-adem7ot                       
 3) libiconv/1.17-gcc-12.2.0-pztn24l      14) gettext/0.21.1-gcc-12.2.0-htnecfu        25) netcdf-c/4.7.4-gcc-12.2.0-5wzc2ic      36) easi/1.3.0-gcc-12.2.0-3egmupu                           
 4) xz/5.4.1-gcc-12.2.0-beahnap           15) openssl/3.1.1-gcc-12.2.0-xydqrfk         26) asagi/1.0.1-gcc-12.2.0-xvz2l4l         37) eigen/3.4.0-gcc-12.2.0-kaoej2y                          
 5) zlib/1.2.13-gcc-12.2.0-qvwbld7        16) krb5/1.20.1-gcc-12.2.0-ywylqdh           27) gcc-runtime/12.2.0-gcc-12.2.0-v4wn2t2  38) memkind/1.13.0-gcc-12.2.0-22nvplr                       
 6) libxml2/2.10.3-gcc-12.2.0-6g4ulfn     17) libedit/3.1-20210216-gcc-12.2.0-uybrqun  28) impalajit/main-gcc-12.2.0-judjtis      39) metis/5.1.0-gcc-12.2.0-kcvzwx3                          
 7) ncurses/6.4-gcc-12.2.0-bt2tv43        18) libxcrypt/4.4.35-gcc-12.2.0-bnemwrw      29) nghttp2/1.52.0-gcc-12.2.0-x5wdgxs      40) parmetis/4.0.3-gcc-12.2.0-minbyzl                       
 8) hwloc/2.9.1-gcc-12.2.0-wjb3zv3        19) openssh/9.3p1-gcc-12.2.0-nvgsowj         30) curl/8.1.2-gcc-12.2.0-2s4wrx6          41) seissol/master-gcc-12.2.0-o4-elas-dunav-single-sggt32q  
 9) numactl/2.0.14-gcc-12.2.0-62dxa76     20) libevent/2.1.12-gcc-12.2.0-zgp5wia       31) readline/8.2-gcc-12.2.0-ofdoevl        42) gcc/12.2.0                                              
10) bzip2/1.0.8-gcc-12.2.0-yn6mmdj        21) pmix/4.2.3-gcc-12.2.0-ksjdukm            32) unzip/6.0-gcc-12.2.0-7wxq5cw           
11) pigz/2.7-gcc-12.2.0-5w24zpq           22) openmpi/4.1.5-gcc-12.2.0-ab5rikq         33) lua/5.3.2-gcc-12.2.0-zucnb2e           
```
4. Provide parameter/material files.
https://github.com/SeisSol/Examples/tree/master/tpv5

**Comment by davschneller** [comment]
Yup; that was unfortunately to be expected—the boundary data is stored as 64-bit integer, and the current `'auto'` option only looks for the integer size. I'd say we got two options here:

* make `'i32'` the default (and maybe remove the `'auto'` option—specifying yet another option in the settings shouldn't be a lot of work when changing the mesh)
* read the whole boundary data and check if any value is larger than a 32-bit integer. That is _almost_ a sure guarantee that we'll have a i64 vs i32 boundary.

**Comment by Thomas-Ulrich** [comment]
ok, up to you.
Probably option 1 is fine.
Else, what about updating the PUML format and adding the boundary format as a new attribute written in the file.
In seissol, check if the attribute is available. If not, and no option is specified in the parameter file, use i32.

**Comment by davschneller** [comment]
I like that idea—it's probably the best way without checking an Xdmf XML file (or the parameter file)
