### ISSUE TITLE
spack can't install perl

### ISSUE THREAD

**Issue by dxycugb** [SeisSol/SeisSol#1089]
I tried to compile the seissol with spack, but spack encountered an error when installing perl. I try to follow [https://github.com/spack/spack/issues/9446](url) and [https://serverfault.com/questions/145288/make-error-when-compiling-perl-5-12-1-rhel-5-5/293231#293231](url) method solved but did not work.

$ spack install seissol-env +mpi +asagi %gcc@11.4.0 ^openmpi@4.1.2
[+] /media/meggs/Newvolume/spack/opt/spack/linux-ubuntu22.04-nehalem/gcc-11.4.0/gmake-4.4.1-iqd2ns53pc2ccj5asapgnk45tte3cgsm
==> Waiting for ca-certificates-mozilla-2023-05-30-r3p7m75hcvypyvo7ckd4mfl6eofj4[+] /media/meggs/Newvolume/spack/opt/spack/linux-ubuntu22.04-nehalem/gcc-11.4.0/ca-certificates-mozilla-2023-05-30-r3p7m75hcvypyvo7ckd4mfl6eofj43ly
[+] /media/meggs/Newvolume/spack/opt/spack/linux-ubuntu22.04-nehalem/gcc-11.4.0/bzip2-1.0.8-bzvlh5xb7gcukbajcg5bmgc5c6hyzfae
[+] /media/meggs/Newvolume/spack/opt/spack/linux-ubuntu22.04-nehalem/gcc-11.4.0/cxxtest-develop-7ugwrjmy5pxnu2ybb6mvkkxv2jyindny
[+] /media/meggs/Newvolume/spack/opt/spack/linux-ubuntu22.04-nehalem/gcc-11.4.0/libiconv-1.17-gehf7fdrndlayzhykx7wyyzsxl34zbho
[+] /media/meggs/Newvolume/spack/opt/spack/linux-ubuntu22.04-nehalem/gcc-11.4.0/util-linux-uuid-2.38.1-u3ukwb56j4z4pufdgcz3b7gws6n3i3vh
[+] /media/meggs/Newvolume/spack/opt/spack/linux-ubuntu22.04-nehalem/gcc-11.4.0/berkeley-db-18.1.40-yedljedkffkwhohsdaeseij3rjkwsvzi
[+] /media/meggs/Newvolume/spack/opt/spack/linux-ubuntu22.04-nehalem/gcc-11.4.0/zlib-ng-2.1.4-ndxo2fpo4ze4p2mjf6gbmeg3ulgxvp2u
[+] /media/meggs/Newvolume/spack/opt/spack/linux-ubuntu22.04-nehalem/gcc-11.4.0/libsigsegv-2.14-2be3rupgjxnu4rcb77dif4wktqnijqf7
[+] /media/meggs/Newvolume/spack/opt/spack/linux-ubuntu22.04-nehalem/gcc-11.4.0/ncurses-6.4-zcacw7rwv47olkxb7d4t6pbngdr7nq6y
[+] /media/meggs/Newvolume/spack/opt/spack/linux-ubuntu22.04-nehalem/gcc-11.4.0/libffi-3.4.4-rrwxggyncbzj4m4mrzcn5aofj75yh5mw
[+] /media/meggs/Newvolume/spack/opt/spack/linux-ubuntu22.04-nehalem/gcc-11.4.0/libpciaccess-0.17-gsb7es45xqmmqjrp2ivez2g5lwcutc6w
[+] /media/meggs/Newvolume/spack/opt/spack/linux-ubuntu22.04-nehalem/gcc-11.4.0/nghttp2-1.57.0-7b7qxdkn6hnudzcod5nhq2ulf3q5ocl7
[+] /media/meggs/Newvolume/spack/opt/spack/linux-ubuntu22.04-nehalem/gcc-11.4.0/libtool-2.4.7-gss5dxrirj6us5vuvtrxqyc2ycx42gkv
[+] /media/meggs/Newvolume/spack/opt/spack/linux-ubuntu22.04-nehalem/gcc-11.4.0/findutils-4.9.0-7v2ps7dytxliwnmqkhgjxaqjxlgrk6df
[+] /media/meggs/Newvolume/spack/opt/spack/linux-ubuntu22.04-nehalem/gcc-11.4.0/unzip-6.0-ehx4oqgwfgr56paoqcarsvsirlvsi4de
[+] /media/meggs/Newvolume/spack/opt/spack/linux-ubuntu22.04-nehalem/gcc-11.4.0/libmd-1.0.4-3cl2r7qqexznm3gjt6txpwv6kbpgpk7r
[+] /media/meggs/Newvolume/spack/opt/spack/linux-ubuntu22.04-nehalem/gcc-11.4.0/zstd-1.5.5-bh7a6ua5vzwbbaurtphillpiy7n3jcz5
[+] /media/meggs/Newvolume/spack/opt/spack/linux-ubuntu22.04-nehalem/gcc-11.4.0/pkgconf-1.9.5-5nsijmgmlfl5l73wtyiusrlqyunjvjgh
[+] /media/meggs/Newvolume/spack/opt/spack/linux-ubuntu22.04-nehalem/gcc-11.4.0/xz-5.4.1-wyu2utgnu7ivnulifvsqz4nemkyjrf7w
[+] /media/meggs/Newvolume/spack/opt/spack/linux-ubuntu22.04-nehalem/gcc-11.4.0/diffutils-3.9-o4lhdu4kqwhctgt7nhu6ci6feveuwmxg
[+] /media/meggs/Newvolume/spack/opt/spack/linux-ubuntu22.04-nehalem/gcc-11.4.0/pigz-2.7-oa2afbzsrmn4giplgmpt275guwyz5k4z
[+] /media/meggs/Newvolume/spack/opt/spack/linux-ubuntu22.04-nehalem/gcc-11.4.0/readline-8.2-uqv2cc4fddvakp45yqk3enzyzruwb7ld
[+] /media/meggs/Newvolume/spack/opt/spack/linux-ubuntu22.04-nehalem/gcc-11.4.0/libbsd-0.11.7-ocanaobcluqtxujgx7gmeyesgrsr3suh
[+] /media/meggs/Newvolume/spack/opt/spack/linux-ubuntu22.04-nehalem/gcc-11.4.0/libedit-3.1-20210216-k76drbulk6ybde23h676aq5nj6o6asd5
[+] /media/meggs/Newvolume/spack/opt/spack/linux-ubuntu22.04-nehalem/gcc-11.4.0/libxml2-2.10.3-alxx4acygjg67fwrxhv5hoia3wcjwx7g
[+] /media/meggs/Newvolume/spack/opt/spack/linux-ubuntu22.04-nehalem/gcc-11.4.0/binutils-2.41-b3qvmusjocpz6wfobtj2uidb7c5iklzn
[+] /media/meggs/Newvolume/spack/opt/spack/linux-ubuntu22.04-nehalem/gcc-11.4.0/m4-1.4.19-dypasinmdpqzfog7wfahz5lugxz7pvgr
[+] /media/meggs/Newvolume/spack/opt/spack/linux-ubuntu22.04-nehalem/gcc-11.4.0/tar-1.34-klnal67afl744jfpumudmb3k3hbvises
[+] /media/meggs/Newvolume/spack/opt/spack/linux-ubuntu22.04-nehalem/gcc-11.4.0/sqlite-3.43.2-vldqkvgzz36crqidfdw66lo3bctzvf7z
[+] /media/meggs/Newvolume/spack/opt/spack/linux-ubuntu22.04-nehalem/gcc-11.4.0/gdbm-1.23-rxi3ioa3haueeml7kwmvgn7pj4lt6pus
[+] /media/meggs/Newvolume/spack/opt/spack/linux-ubuntu22.04-nehalem/gcc-11.4.0/expat-2.5.0-vcwsji5x2ht2ivgoxymgxu3qaztbg3co
[+] /media/meggs/Newvolume/spack/opt/spack/linux-ubuntu22.04-nehalem/gcc-11.4.0/hwloc-2.9.1-i54vzbooricreqy5wvkrqh3ykzdkpqyb
[+] /media/meggs/Newvolume/spack/opt/spack/linux-ubuntu22.04-nehalem/gcc-11.4.0/gettext-0.22.3-7zugpytedalw475zmvrtzx53kxepwyza
==> Installing perl-5.38.0-4kutl4c6jvogmqaidjqtnftmglw2krqo [35/65]
==> No binary for perl-5.38.0-4kutl4c6jvogmqaidjqtnftmglw2krqo found: installing from source
==> Using cached archive: /media/meggs/Newvolume/spack/var/spack/cache/_source-cache/archive/21/213ef58089d2f2c972ea353517dc60ec3656f050dcc027666e118b508423e517.tar.gz
==> Using cached archive: /media/meggs/Newvolume/spack/var/spack/cache/_source-cache/archive/9d/9da50e155df72bce55cb69f51f1dbb4b62d23740fb99f6178bb27f22ebdf8a46.tar.gz
==> Moving resource stage
	source: /tmp/meggs/spack-stage/resource-cpanm-4kutl4c6jvogmqaidjqtnftmglw2krqo/spack-src/
	destination: /tmp/meggs/spack-stage/spack-stage-perl-5.38.0-4kutl4c6jvogmqaidjqtnftmglw2krqo/spack-src/cpanm/cpanm
==> Applied patch /media/meggs/Newvolume/spack/var/spack/repos/builtin/packages/perl/zlib-ng.patch
==> Ran patch() for perl
==> perl: Executing phase: 'configure'
==> perl: Executing phase: 'build'
==> perl: Executing phase: 'install'
==> Error: ProcessError: Command exited with status 2:
    'make' '-j16' 'install'

2 errors found in build log:
     5146      /media/meggs/Newvolume/spack/opt/spack/linux-ubuntu22.04-nehalem
             /gcc-11.4.0/perl-5.38.0-4kutl4c6jvogmqaidjqtnftmglw2krqo/man/man1/
             perlpodstyle.1
     5147      /media/meggs/Newvolume/spack/opt/spack/linux-ubuntu22.04-nehalem
             /gcc-11.4.0/perl-5.38.0-4kutl4c6jvogmqaidjqtnftmglw2krqo/man/man1/
             perlpolicy.1
     5148      /media/meggs/Newvolume/spack/opt/spack/linux-ubuntu22.04-nehalem
             /gcc-11.4.0/perl-5.38.0-4kutl4c6jvogmqaidjqtnftmglw2krqo/man/man1/
             perlport.1
     5149      /media/meggs/Newvolume/spack/opt/spack/linux-ubuntu22.04-nehalem
             /gcc-11.4.0/perl-5.38.0-4kutl4c6jvogmqaidjqtnftmglw2krqo/man/man1/
             perlpragma.1
     5150      /media/meggs/Newvolume/spack/opt/spack/linux-ubuntu22.04-nehalem
             /gcc-11.4.0/perl-5.38.0-4kutl4c6jvogmqaidjqtnftmglw2krqo/man/man1/
             perlqnx.1
     5151      /media/meggs/Newvolume/spack/opt/spack/linux-ubuntu22.04-nehalem
             /gcc-11.4.0/perl-5.38.0-4kutl4c6jvogmqaidjqtnftmglw2krqo/man/man1/
             perlre.1
&&   5152    /media/meggs/Newvolume/spack/opt/spack/linux-ubuntu22.04-nehalem/g
             cc-11.4.0/perl-5.38.0-4kutl4c6jvogmqaidjqtnftmglw2krqo/man/Can't w
             rite-open /media/meggs/Newvolume/spack/opt/spack/linux-ubuntu22.04
             -nehalem/gcc-11.4.0/perl-5.38.0-4kutl4c6jvogmqaidjqtnftmglw2krqo/m
             an/man3/App::Cpan.tmp: Invalid argument at installman line 170.
     5153    man1/perlreapi.1
     5154      /media/meggs/Newvolume/spack/opt/spack/linux-ubuntu22.04-nehalem
             /gcc-11.4.0/perl-5.38.0-4kutl4c6jvogmqaidjqtnftmglw2krqo/man/man1/
             perlrebackslash.1
     5155      /media/meggs/Newvolume/spack/opt/spack/linux-ubuntu22.04-nehalem
             /gcc-11.4.0/perl-5.38.0-4kutl4c6jvogmqaidjqtnftmglw2krqo/man/man1/
             perlrecharclass.1
     5156      /media/meggs/Newvolume/spack/opt/spack/linux-ubuntu22.04-nehalem
             /gcc-11.4.0/perl-5.38.0-4kutl4c6jvogmqaidjqtnftmglw2krqo/man/man1/
             perlref.1
     5157      /media/meggs/Newvolume/spack/opt/spack/linux-ubuntu22.04-nehalem
             /gcc-11.4.0/perl-5.38.0-4kutl4c6jvogmqaidjqtnftmglw2krqo/man/man1/
             perlreftut.1
     5158      /media/meggs/Newvolume/spack/opt/spack/linux-ubuntu22.04-nehalem
             /gcc-11.4.0/perl-5.38.0-4kutl4c6jvogmqaidjqtnftmglw2krqo/man/man1/
             perlreguts.1
     5192      /media/meggs/Newvolume/spack/opt/spack/linux-ubuntu22.04-nehalem
             /gcc-11.4.0/perl-5.38.0-4kutl4c6jvogmqaidjqtnftmglw2krqo/man/man1/
             perlwin32.1
     5193      /media/meggs/Newvolume/spack/opt/spack/linux-ubuntu22.04-nehalem
             /gcc-11.4.0/perl-5.38.0-4kutl4c6jvogmqaidjqtnftmglw2krqo/man/man1/
             perlxs.1
     5194      /media/meggs/Newvolume/spack/opt/spack/linux-ubuntu22.04-nehalem
             /gcc-11.4.0/perl-5.38.0-4kutl4c6jvogmqaidjqtnftmglw2krqo/man/man1/
             perlxstut.1
     5195      /media/meggs/Newvolume/spack/opt/spack/linux-ubuntu22.04-nehalem
             /gcc-11.4.0/perl-5.38.0-4kutl4c6jvogmqaidjqtnftmglw2krqo/man/man1/
             perlxstypemap.1
     5196      /media/meggs/Newvolume/spack/opt/spack/linux-ubuntu22.04-nehalem
             /gcc-11.4.0/perl-5.38.0-4kutl4c6jvogmqaidjqtnftmglw2krqo/man/man3/
             AnyDBM_File.3
     5197      /media/meggs/Newvolume/spack/opt/spack/linux-ubuntu22.04-nehalem
             /gcc-11.4.0/perl-5.38.0-4kutl4c6jvogmqaidjqtnftmglw2krqo/man/man3/
             App::Cpan.3
&&   5198    make: *** [makefile:470: install-all] Error 22

See build log for details:
  /tmp/meggs/spack-stage/spack-stage-perl-5.38.0-4kutl4c6jvogmqaidjqtnftmglw2krqo/spack-build-out.txt

==> Warning: Skipping build of openmpi-4.1.2-ortihn62tbqgpg2bapx4cqoiui64xhz2 since perl-5.38.0-4kutl4c6jvogmqaidjqtnftmglw2krqo failed
==> Warning: Skipping build of parmetis-4.0.3-d3xt7sfwzjcvzndh3dbfqsvztu7fuuia since openmpi-4.1.2-ortihn62tbqgpg2bapx4cqoiui64xhz2 failed
==> Warning: Skipping build of seissol-env-develop-lnnr622fhaooajp73bivqeipq4ydqzsk since parmetis-4.0.3-d3xt7sfwzjcvzndh3dbfqsvztu7fuuia failed
==> Warning: Skipping build of hdf5-1.12.2-qfbi65zoassakkveemiwt3odqymogja5 since openmpi-4.1.2-ortihn62tbqgpg2bapx4cqoiui64xhz2 failed
==> Warning: Skipping build of netcdf-c-4.7.4-ylcwgrvxbshsujpenoehjz4qvcxu3mae since hdf5-1.12.2-qfbi65zoassakkveemiwt3odqymogja5 failed
==> Warning: Skipping build of asagi-1.0.1-ekt5qzymznuvh535pdza5idztrkmqyyx since netcdf-c-4.7.4-ylcwgrvxbshsujpenoehjz4qvcxu3mae failed
==> Warning: Skipping build of easi-1.2.0-xsotzvaenyfiuimwrtn4tyunyjb664tm since asagi-1.0.1-ekt5qzymznuvh535pdza5idztrkmqyyx failed
==> Warning: Skipping build of automake-1.16.5-f3thiqx6d7lgrnlxa2tzvwgyt7eqvpve since perl-5.38.0-4kutl4c6jvogmqaidjqtnftmglw2krqo failed
==> Warning: Skipping build of memkind-1.13.0-blkv4a4fuwxdv46tu3jkzpdk6nz3buh6 since automake-1.16.5-f3thiqx6d7lgrnlxa2tzvwgyt7eqvpve failed
==> Warning: Skipping build of numactl-2.0.14-i6rsunhm43gr4pwhxd3tt2tavdzdoydf since automake-1.16.5-f3thiqx6d7lgrnlxa2tzvwgyt7eqvpve failed
==> Warning: Skipping build of libevent-2.1.12-67n2cenc646x2gko7ej3a22pm6o2rsqm since automake-1.16.5-f3thiqx6d7lgrnlxa2tzvwgyt7eqvpve failed
==> Warning: Skipping build of pmix-4.2.2-xfuvkhk4zyzx2oqvzzebsovv433y66kq since libevent-2.1.12-67n2cenc646x2gko7ej3a22pm6o2rsqm failed
==> Warning: Skipping build of bison-3.8.2-cks7xdpu26npmooxtm75aalfqgs7tvo4 since perl-5.38.0-4kutl4c6jvogmqaidjqtnftmglw2krqo failed
==> Warning: Skipping build of krb5-1.20.1-7oylr6u4vqcvufcuyymv6rmg7coyu3s2 since bison-3.8.2-cks7xdpu26npmooxtm75aalfqgs7tvo4 failed
==> Warning: Skipping build of openssh-9.5p1-6xjpoep3i6geggvrhofndqvvd6yoi6ai since krb5-1.20.1-7oylr6u4vqcvufcuyymv6rmg7coyu3s2 failed
==> Warning: Skipping build of libxcrypt-4.4.35-w74xds6rigbyjzgf7l24uhh6nxwslrbo since perl-5.38.0-4kutl4c6jvogmqaidjqtnftmglw2krqo failed
==> Warning: Skipping build of python-3.11.6-ywtlaw66ey5rcaj2rvrujvm66fw6ufyx since libxcrypt-4.4.35-w74xds6rigbyjzgf7l24uhh6nxwslrbo failed
==> Warning: Skipping build of py-pspamm-develop-bpfkr2ibgitvtxjxii7tusieesqfzslg since python-3.11.6-ywtlaw66ey5rcaj2rvrujvm66fw6ufyx failed
==> Warning: Skipping build of libxsmm-1.17-fui456b56ql7db6rttknyqanjma3xxgp since python-3.11.6-ywtlaw66ey5rcaj2rvrujvm66fw6ufyx failed
==> Warning: Skipping build of py-wheel-0.41.2-u5ga4optve2rzsjkeectk2q2kn76jykf since python-3.11.6-ywtlaw66ey5rcaj2rvrujvm66fw6ufyx failed
==> Warning: Skipping build of py-pip-23.1.2-yinpofuiiudzkrj7mlwevrihufwqwuqt since python-3.11.6-ywtlaw66ey5rcaj2rvrujvm66fw6ufyx failed
==> Warning: Skipping build of autoconf-2.69-r4c3pfx4jrc2uevcwq7r7gcknsh63zrx since perl-5.38.0-4kutl4c6jvogmqaidjqtnftmglw2krqo failed
==> Warning: Skipping build of openssl-3.1.3-qd7fyqyo3ppwujjdqb6s455x76xiflgv since perl-5.38.0-4kutl4c6jvogmqaidjqtnftmglw2krqo failed
==> Warning: Skipping build of curl-8.4.0-bre733zajtn2rbf6tgbwvvzfjaswrj6z since openssl-3.1.3-qd7fyqyo3ppwujjdqb6s455x76xiflgv failed
==> Warning: Skipping build of lua-5.3.2-aaa2c22hw4z4twcefzuavxab5oookfjn since curl-8.4.0-bre733zajtn2rbf6tgbwvvzfjaswrj6z failed
==> Warning: Skipping build of cmake-3.27.7-q62nw4nayc7o2v2nbf7qzekimyekqxwa since curl-8.4.0-bre733zajtn2rbf6tgbwvvzfjaswrj6z failed
==> Warning: Skipping build of yaml-cpp-0.6.2-jwdrxma4pxovwxsgmyih4itkhemsnr6r since cmake-3.27.7-q62nw4nayc7o2v2nbf7qzekimyekqxwa failed
==> Warning: Skipping build of impalajit-main-iskqhhq4t266n7peo2el44owic3mjn5e since cmake-3.27.7-q62nw4nayc7o2v2nbf7qzekimyekqxwa failed
==> Warning: Skipping build of eigen-3.4.0-hb3ojzig7fabu6crjdynwhyxf7ig4wgt since cmake-3.27.7-q62nw4nayc7o2v2nbf7qzekimyekqxwa failed
==> Warning: Skipping build of metis-5.1.0-5qgginbamesxbnbtrj3f75c72stvdev2 since cmake-3.27.7-q62nw4nayc7o2v2nbf7qzekimyekqxwa failed
==> Error: seissol-env-develop-lnnr622fhaooajp73bivqeipq4ydqzsk: Package was not installed
==> Error: Installation request failed.  Refer to reported errors for failing package(s).
[spack-build-out.txt](https://github.com/SeisSol/SeisSol/files/14842889/spack-build-out.txt)

**Comment by Thomas-Ulrich** [comment]
You should rather look in spack for solutions to your problem, e.g.
https://github.com/spack/spack/issues?q=is%3Aissue+is%3Aopen+perl

(but probably you can try `spack external find perl`)

**Comment by Thomas-Ulrich** [comment]
I'm closing the issue, as it is not a problem on our side.
