### ISSUE TITLE
Why do we need such kind of initialization? Why can we use just integer literals for this piece of code with appropriate documentation?

### ISSUE THREAD

**Issue by ravil-mobile** [SeisSol/SeisSol#109]
https://github.com/SeisSol/SeisSol/blob/871a88ad2deb0094ea152da5e3d850ac856c2898/src/Initializer/tree/Layer.hpp#L49-L54

These values will be evaluated at compile time. Definitely, it is not going to effect performance. Question: What is the purpose of shifting bits?

**Comment by krenzland** [comment]
This has to do with the local time stepping which is done with a weird bitset. I don't really know why it is written in that way, but there's no harm in it...
Shifting is just idiomatic for powers of 2 in C++, doesn't really have anything to do with performance.

**Comment by ravil-mobile** [comment]
I know that there is no harm if you use shit operator and no effect on performance in this particular case. I just wonder why it cannot be done like this (which is a way verbose):
enum LayerType {Ghost = 0b00001, Copy = 0b00010, Interior=0b00100, NUMBER_OF_LAYERS};

**Comment by uphoffc** [comment]
Binary literals are only part of C++14. The shift operator is pretty verbose for powers of two imho.

Powers of two are used to be able to represent all of the 8 possible LayerMasks. (In practice we only require masking nothing, the ghost layer, or everything, see https://github.com/SeisSol/SeisSol/blob/871a88ad2deb0094ea152da5e3d850ac856c2898/src/Initializer/LTS.h, but such an implementation is general, extendable, and causes zero overhead.)

**Comment by ravil-mobile** [comment]
Binary literals were a part of C language. 

```c
#include <stdio.h>
enum MASK {c1 = 0b0001, c2 = 0b01001};

int main() {
    printf("the values is: %d\n", c1);
    printf("the values is: %d\n", c2);

    return 0;
}
```
You can compile the snippet above as following and it will work:

 gcc -std=c99 ./main.c

**Comment by krenzland** [comment]
C != C++
See [here](https://en.cppreference.com/w/cpp/language/integer_literal).

**Comment by ravil-mobile** [comment]
It was an extension of C and C++ languages before it was officially approved by the committee and included to the standard. Reference: https://gcc.gnu.org/onlinedocs/gcc/C-Extensions.html#C-Extensions. Both gcc and icc support this by default.

Ok. It doesn't make sense to argue about that anymore. I'll just add a comment in my branch. My original point is: it seems to me that there are lot's undocumented features like this one which are not 100% verbose with respect to the pure code which in fact slow down reading and debugging the source code.

In short, never mind
