### ISSUE TITLE
Could anybody tell me why we need these 2 empty structures?

### ISSUE THREAD

**Issue by ravil-mobile** [SeisSol/SeisSol#110]
https://github.com/SeisSol/SeisSol/blob/871a88ad2deb0094ea152da5e3d850ac856c2898/src/Equations/elastic/Model/datastructures.hpp#L48-L49

**Comment by krenzland** [comment]
for [viscoelasticity](https://github.com/SeisSol/SeisSol/blob/871a88ad2deb0094ea152da5e3d850ac856c2898/src/Equations/viscoelastic2/Model/datastructures.hpp)
