### ISSUE TITLE
Numerical oscillation at the dynamic friction level

### ISSUE THREAD

**Issue by francescomosconi** [SeisSol/SeisSol#1117]
**Describe the bug**
Numerical oscillations at the residual stress of the fault during a decelerating rupture. See attached image.

<img width="505" alt="Schermata 2024-05-21 alle 10 37 02" src="https://github.com/SeisSol/SeisSol/assets/84501864/cbacb459-bdd4-4bd0-8138-33553e9d39eb">

**Expected behavior**
No oscillations at the residual stress

**To Reproduce**
1. Version: v1.1.3-248-g45e14e40. Master branch;  commit id: dd018b3398258a23ec2a33c74bd7f31b503dcca6.
2. GPU version with MPI compilers. Build setup: Double precision, order 6.
3. Actually working on LEONARDO. Loaded modules:
<img width="1063" alt="Schermata 2024-05-21 alle 08 31 33" src="https://github.com/SeisSol/SeisSol/assets/84501864/bbe52243-8c8e-48bc-91ad-ec8694b7e56c">

4. Parameter file:
[parameters_ref.txt](https://github.com/SeisSol/SeisSol/files/15385531/parameters_ref.txt)

Output file:
[seissol_out.txt](https://github.com/SeisSol/SeisSol/files/15385535/seissol_out.txt)

**Additional context**
We obtain the plot from the seissol output, more precisesly we extrapolate a section (for each simulation time step) along the fault strike with paraview.
It is weird to don't observe the same problem of the numerical oscillation if we have an accelerating rupture, with identical configuration. See attached image. 

<img width="499" alt="Schermata 2024-05-21 alle 10 37 24" src="https://github.com/SeisSol/SeisSol/assets/84501864/759dd4ec-730a-47ec-9e2c-7247bdd96c64">

Maybe is because of the larger slip rate?
We actually use a fault mesh element size of 12.5cm with a mean cohesive zone value of 0.34m.

Do you have any suggestions?

Many thanks in advance!

**Comment by sebwolf-de** [comment]
This could be connected to the spatial spikes problem as reported in #546. Can you just post a paraview visualization of the fault (like e.g. https://seissol.readthedocs.io/en/latest/_images/tpv5_SRs_3s.png)

**Comment by francescomosconi** [comment]
I can provide you  the complete fault output through Python visualization. Should it work as well?

Shear stress:

![snapshot_Td0](https://github.com/SeisSol/SeisSol/assets/84501864/6eedfb65-1e4f-43b4-b897-ad0dddf28b80)

Slip rate:

![snapshot_SRd](https://github.com/SeisSol/SeisSol/assets/84501864/7623d17c-5fc5-44a2-9f6b-e3a408547b41)

Slip distribution:

![final_slip](https://github.com/SeisSol/SeisSol/assets/84501864/7c9e51ef-ca40-444e-8dea-4387f3757e51)

Normal stress change:

![snapshot_P_n](https://github.com/SeisSol/SeisSol/assets/84501864/1e421fb5-2719-4630-9894-89fd27d770d0)


Please let me know if you need further information!

**Comment by AliceGabriel** [comment]
Thanks! It looks indeed like https://github.com/SeisSol/SeisSol/issues/546

this is not a symmetric mesh right?

interesting that the same model with a coarser mesh is not affected.

**Comment by sebwolf-de** [comment]
Indeed, that is another manifestation of #546. You could use a symmetric mesh, which is maybe not possible with your geometry, or you could use the _eta hack_: https://github.com/SeisSol/SeisSol/issues/546#issuecomment-2034160010

**Comment by francescomosconi** [comment]
Utilize the `etahack = 0.9` solve perfectly the problem. 
Just for clarification, how should varying this parameter (i.e., the P impedance value) work?

Many thanks!

**Comment by AliceGabriel** [comment]
Hi Francesco, I would suggest choosing eta as close to 1.0 as possible, i.e., reducing to the largest value that would not result in artifacts; 0.9 is a value we have used before and can serve as a guideline. This is basically a way to dampen numerical issues. BTW should we rename this from eta hack into something less hacky-sounding?

**Comment by Thomas-Ulrich** [comment]
I suggest not using etahack (which means the normal stress transient is not fully accounted for in the friction law) and adding
```
numflux = 'rusanov' ! The numerical flux. Values: 'godunov', 'rusanov'
numfluxnearfault = 'rusanov' ! The numerical flux for faces of cells adjacent to the fault (on cells which have at least one DR face), excluding the DR faces themselves. Values: 'godunov', 'rusanov'
```
to equations.
