### ISSUE TITLE
viscoelastic2 compile error on SuperMUC-NG

### ISSUE THREAD

**Issue by jrekoske** [SeisSol/SeisSol#1148]
**Describe the bug**
I get an error during compilation

```
[ 84%] Building CXX object CMakeFiles/SeisSol-lib.dir/src/Reader/AsagiReader.cpp.o
/dss/dsshome1/0B/di46bak/SeisSol/src/Equations/viscoelastic2/Model/datastructures.hpp(64): error: incomplete type is not allowed
    static inline const std::array<std::string, NumberOfQuantities> Quantities = {
                                                                    ^
          detected during instantiation of class "seissol::model::ViscoElasticMaterialParametrized<MechanismsP> [with MechanismsP=3UL]" at line 107 of "/dss/dsshome1/0B/di46bak/SeisSol/src/ResultWriter/ReceiverWriter.cpp"

[ 85%] Building CXX object CMakeFiles/SeisSol-lib.dir/src/Parallel/Runtime/StreamOMP.cpp.o
```

**Expected behavior**
Code should compile without error

**To Reproduce**
1. Which version do you use? Provide branch and commit id.

I used master branch 494a6e1af19eedd0d66bf0fb04b1ea63f1345498

2. Which build settings do you use? Which compiler version do you use? 

```
cmake -DNUMA_AWARE_PINNING=ON -DASAGI=ON -DCMAKE_BUILD_TYPE=Release -DHOST_ARCH=skx -DPRECISION=single -DORDER=6 -DEQUATIONS=viscoelastic2 -DNUMBER_OF_MECHANISMS=3 ..
```

3 . On which machine does your problem occur? If on a cluster: Which modules are loaded?

SuperMUC-NG with these modules

```
Currently Loaded Modulefiles:
 1) admin/1.0     4) spack/22.2.1                                     7) intel-mpi/2019-intel  10) python/3.8.11-extended                
 2) tempdir/1.0   5) intel-oneapi-compilers/2021.4.0(default:intel)   8) gcc/11.2.0            11) numactl/2.0.14-intel21                
 3) lrz/1.0       6) intel-mkl/2020                                   9) cmake/3.21.4          12) seissol-env/develop-intel21-impi-x2b  
```

**Additional context**
It compiled error-free with elastic but not viscoelastic2.

**Comment by davschneller** [comment]
Hi, would #1149 fix your issue?

**Comment by jrekoske** [comment]
@davschneller  It doesn't seem like that fixed it. I checked out your new branch but and cleaned the compile directory, but got the same error.

**Comment by davschneller** [comment]
Just noticed what may have caused it. Sorry to ask again; may it be possible to try once more now?

**Comment by jrekoske** [comment]
@davschneller Yes it compiles now, thanks!

**Comment by davschneller** [comment]
That's great to hear; thanks for checking! #1149 should be merged soon as well.
