### ISSUE TITLE
"Did not find dynamic rupture surfaces"

### ISSUE THREAD

**Issue by Thomas-Ulrich** [SeisSol/SeisSol#116]
Taufiq and I got the error on setups that were previously working.
Therefore, it seems that this commit does not do his job properly:
https://github.com/SeisSol/SeisSol/commit/bc00758f0fa0bc034f6eae6a9c0a38705264d82a
Was it properly tested?

Thomas.

**Comment by krenzland** [comment]
Please provide an example of setups that fail and the error message.

Otherwise we cannot reproduce this issue.

**Comment by uphoffc** [comment]
You should not need another example. Just run a dynamic rupture test-case on many nodes until one node does not get dynamic rupture faces from the graph partitioner.

**Comment by krenzland** [comment]
Carsten, the fact that it occurs on many nodes is an information that is not provided by the bug report...
Generally it's good practice to attach information about the environment and situations that are not working.

**Comment by Thomas-Ulrich** [comment]
Sorry I was a bit lazy. But it seems the origin of the bug is known now ;-)

**Comment by sebwolf-de** [comment]
This was tested, but only on small simulations. We thought this error message might be helpful. Now it seems that it breaks more things, than helps. I will remove it again.

**Comment by sebwolf-de** [comment]
The originally intended functionality seems to be harder to implement, and we might not even need it.

**Comment by sebwolf-de** [comment]
https://github.com/SeisSol/SeisSol/tree/dynrup-hotfix
Does your simulation run on this branch?

**Comment by Thomas-Ulrich** [comment]
yes removing out the 2 lines fix the problem.
