### ISSUE TITLE
Wrong calculation of seismic moment and Mw in v1.1.4-342-gaa64de90

### ISSUE THREAD

**Issue by fabian-kutschera** [SeisSol/SeisSol#1170]
**Describe the bug**
While preparing new benchmark scenarios, I noticed an inconsistency in the displayed seismic moment (and Mw) in the .out file when running the scenario using different SeisSol version. 
I started with an initial test using the Docker image seissol/training:portable (which btw works great on my Apple M2!).
Here, I ran initial tests using a smaller mesh. The Docker SeisSol version appears to be v1.1.3 (Last commit: 01ae1b127fcc6f766b819d2e797df6a3547d730a).

I then moved to NG. Here, I used version v1.1.4-342-gaa64de90 (Last commit: aa64de903a1372713c9ff3576000561f54314a3b).
Suddenly, unrealistic large seismic moment and moment magnitudes are shown in the .out file. 
I used the same .yaml files and the same mesh file.

I re-compiled SeisSol on NG to have the same version as my Docker image (v.1.1.3) and I obtain the same values as I'ld expect.

I had a brief look at the fault output, which appears to be consistent among all three simulations, regardless of the version (see attached figure).

<img width="1531" alt="image" src="https://github.com/user-attachments/assets/0b2c865f-c941-4379-9e26-ccdd8ef680a2">

**Expected behavior**
Comparable and realistic magnitudes. 

**To Reproduce**
Mesh is here: https://drive.google.com/drive/folders/1wzGEdA5x_aVK-sl7zvIe9bKef-x07UMq?usp=sharing
[fault.yaml.txt](https://github.com/user-attachments/files/17085765/fault.yaml.txt)
[material.yaml.txt](https://github.com/user-attachments/files/17085766/material.yaml.txt)
[parameters.par.txt](https://github.com/user-attachments/files/17085767/parameters.par.txt)
[run.job.txt](https://github.com/user-attachments/files/17085768/run.job.txt)

**Screenshots/Console output: example**
Run using Docker SeisSol v1.1.3:

> Sat Sep 21 20:16:24, Info:  Seismic moment (without plasticity): 2.83978e+14  Mw: 3.56552 
> Sat Sep 21 20:16:24, Info:  Writing energy output at time 0.5 Done. 

Run using SeisSol v1.1.4 on NG:

> Sat Sep 21 22:30:11, Info:  Seismic moment (without plasticity): 6.07448e+97  Mw: 59.119 
> Sat Sep 21 22:30:11, Info:  Writing energy output at time 0.5 Done. 

Run using SeisSol v1.1.3 on NG (consistent with the Docker run):

> Sat Sep 21 23:01:50, Info:  Seismic moment (without plasticity): 2.83978e+14  Mw: 3.56552 
> Sat Sep 21 23:01:50, Info:  Writing energy output at time 0.5 Done. 

**Additional context**
Please also note the changed structure in the attached .out files.
That is the greeting "Welcome to SeisSol" appears first in v1.1.3, while the first lines seem to be mixed up in v1.1.4.

[v1.1.3_Docker.out.txt](https://github.com/user-attachments/files/17085754/v1.1.3_Docker.out.txt)
[v1.1.4_NG.out.txt](https://github.com/user-attachments/files/17085756/v1.1.4_NG.out.txt)
[v1.1.3_NG.out.txt](https://github.com/user-attachments/files/17085755/v1.1.3_NG.out.txt)

**Comment by davschneller** [comment]
Tried to reproduce the error for `master` (at the time of writing) for order 4 and 6, double precision on my laptop (Ryzen 5900HX); but got correct-looking results in both cases. I tried GCC and clang for order 4, both worked. I.e. maybe it's related to using the Intel compiler on SuperMUC NG Phase 1?

Does the error also occur when compiling SeisSol with e.g. GCC on NG? Or what happens if you install SeisSol on your Laptop directly, w/o Docker?

**Comment by fabian-kutschera** [comment]
I already have `module load gcc` in my `.bashrc` file on NG and compiled SeisSol using:

`cmake -DNUMA_AWARE_PINNING=ON -DASAGI=ON -DCMAKE_BUILD_TYPE=Release -DHOST_ARCH=skx -DPRECISION=double -DORDER=4 -DGEMM_TOOLS_LIST=PSpaMM ..`

Anything else I should have specified?
<img width="952" alt="image" src="https://github.com/user-attachments/assets/08333bb6-1e23-4dea-a1db-c278a17c1c90">

---

Another question @davschneller: when you ran the simulation, did you observe any slip artifacts in your fault output?
Looking closely at the figure above showing the slip after 4 seconds, some artifacts can already be seen. For me, these are more pronounced at the end of the simulation.

I tried the recommended `etahack` parameter from #546, but it did not resolve the problem.
Even a very extreme test with `etahack=0.6` still resulted in slip artifacts. Is there any indication in the .out log file, whether the etahack has been "correctly" applied?

**Comment by davschneller** [comment]
Maybe—but probably not; it'll use ICC still. :)
You may need to set `CC=gcc CXX=g++` before the `cmake` command (and build in a new directory). CMake should tell you right away that you're using GCC (where it wrote something about Intel before that).

---

Regarding the etahack etc.: yes, you're right; I see the small artifacts.

Yes, there is a warning emitted in the log, if `etahack` is not equal to 1. I.e. the `.err` file should show that.

You can also try #1103 , and set `vtkorder=4` in the `elementwise` section; maybe it shows you a bit more details (it'll span a polynomial over the fault output).

**Comment by fabian-kutschera** [comment]
Just a short intermediate summary for future reference after pers. comm. with David:

- The etahack resolves the problem with the slip artifacts (just needs to be applied correctly, see #1171)
- After some tests, we narrowed down the origin of the false magnitude display, which might have been introduced somewhere in-between Version v.1.1.4 commits 80354f7d0d1ebf255f9168fadde9b2b6554e7974 and aa64de903a1372713c9ff3576000561f54314a3b.

**Comment by davschneller** [comment]
Just letting you know that I tried reproducing the bug; but to no avail yet. Neither icc nor icx give me wrong values with a pretty similar configuration.

**Comment by davschneller** [comment]
Bug could be reproduced in the CI pipeline test rework (cf. the branch https://github.com/SeisSol/SeisSol/tree/davschneller/gpu-image ).

**Comment by davschneller** [comment]
Bug identified and squashed with #1178 .
