### ISSUE TITLE
Branch TP: Error running my model

### ISSUE THREAD

**Issue by sebanger** [SeisSol/SeisSol#119]
I was creating several executables for my thermal pressurization 
implementation but now after rerunning my model I get this error:

Thread 37 (Thread 0x2b78af214700 (LWP 42323)):
#0  0x00002b78a9b0dd03 in epoll_wait () from /lib64/libc.so.6
#1  0x00002b78aeba4c78 in poe_exiting_thread () from 
/opt/ibmhpc/pe1404/base/intel/lib64/libpoe.so
#2  0x00002b78a7b21806 in start_thread () from /lib64/libpthread.so.0
#3  0x00002b78a9b0d67d in clone () from /lib64/libc.so.6
#4  0x0000000000000000 in ?? ()

#5  <signal handler called>
#6  0x000000000041a7af in 
gemm_m20_n9_k10_ldA20_ldB12_ldC20_beta1_alignedA1_alignedC1_pfsigonly(double 
const*, double const*, double*, double const*, double const*, double 
const*) ()
#7  0x0000000000422d2f in seissol::generatedKernels::localFlux0(double 
const*, double const*, double const*, double const*, double*, double 
const*) ()
#8  0x000000000057b3d0 in 
seissol::kernels::Local::computeIntegral(faceType const*, GlobalData 
const*, LocalIntegrationData const*, double*, double*) ()
#9  0x00000000006a4283 in 
seissol::miniSeisSol(seissol::initializers::MemoryManager&) ()
#10 0x00002ab0cd7cfd43 in __kmp_invoke_microtask () from 
/lrz/sys/intel/studio2017_u6/compilers_and_libraries_2017.6.256/linux/compiler/lib/intel64/libiomp5.so
#11 0x00002ab0cd79e317 in __kmp_invoke_task_func (gtid=0) at 
../../src/kmp_runtime.cpp:7129
#12 0x00002ab0cd79f544 in __kmp_fork_call (loc=0x0, gtid=784973824, 
call_context=(unknown: 673185792), argc=0, microtask=0x0, invoker=0x0, 
ap=0x7ffe2ec9dd80) at ../../src/kmp_runtime.cpp:2404
#13 0x00002ab0cd77682e in __kmpc_fork_call (loc=0x0, argc=784973824, 
microtask=0x2ab128200000) at ../../src/kmp_csupport.cpp:341
#14 0x00000000006a4816 in 
seissol::miniSeisSol(seissol::initializers::MemoryManager&) ()
#15 0x0000000000479b9e in read_mesh_puml_c ()
#16 0x00000000004709e5 in meshreadercbinding_mp_read_mesh_fast_ ()
#17 0x00000000004a1805 in ini_seissol_mod_mp_ini_seissol_ ()
#18 0x00000000006bd3e4 in fortran_main ()
#19 0x00000000007110e9 in main ()

It basically stops after this:
Rank:        0 | Info    | 
<--------------------------------------------------------->
Rank:        0 | Info    | <     Start ini_SeisSol ...                 

Rank:        0 | Info    | 
<--------------------------------------------------------->
Rank:        0 | Info    | <  Parameters read from file: 
parameters_benchmark.par              >
Rank:        0 | Info    | <                                           

Rank:        0 | Info    | No plasticity assumed.
Rank:        0 | Info    | GPwise initialization.
Rank:        0 | Info    | Thermal pressurization assumed
Rank:        0 | Info    | Temp   483.150000000000
Rank:        0 | Info    | RF output in extra files on
Rank:        0 | Info    | Read a PUML mesh file
Rank:        0 | Info    | Output data is disabled
Rank:        0 | Info    | No output (FORMAT=10) specified, delta T 
set to:   1.000000000000000E+099
Rank:        0 | Info    | Use HDF5 XdmfWriter backend
Rank:        0 | Info    | Refinement is disabled
Thu Sep 05 14:59:11, Info:  Running mini SeisSol to determine node 
weight

Any ideas?

**Comment by Thomas-Ulrich** [comment]
Can we close the issue?
