### ISSUE TITLE
New Source Term implementation doesn't compile with GCC

### ISSUE THREAD

**Issue by alheinecke** [SeisSol/SeisSol#12]
Travis fails with following error:
mpicxx -o build/build_release_generatedKernels_ssnb_hybrid_none_9_6/SourceTerm/Manager.o -c -Wall -Werror -ansi -Wno-error=unknown-pragmas -mavx -O2 -fopenmp -DOMPI_SKIP_MPICXX -DALIGNMENT=32 -DSSNB -DNDEBUG -DCONVERGENCE_ORDER=6 -DNUMBER_OF_QUANTITIES=9 -DNUMBER_OF_RELAXATION_MECHANISMS=0 -DPARALLEL -DUSE_MPI -DOMP -DGENERATEDKERNELS -DCLUSTERED_LTS -DUSE_COMM_THREAD -DLOGLEVEL=2 -DLOGLEVEL0=2 -DLOG_LEVEL=2 -DH5Dcreate_vers=2 -DH5Dopen_vers=2 -DH5Acreate_vers=2 -DH5Eget_auto_vers=2 -DH5Eset_auto_vers=2 -DUSE_HDF -DUSE_NETCDF -Isubmodules -Isrc -Isrc/Equations/elastic -Isrc/Equations/elastic/generated_code src/SourceTerm/Manager.cpp

src/SourceTerm/Manager.cpp: In function ‘void seissol::sourceterm::cleanDoubles(uint8_t*, unsigned int)’:

src/SourceTerm/Manager.cpp:97:40: error: ‘MPI_UINT8_T’ was not declared in this scope

scons: *** [build/build_release_generatedKernels_ssnb_hybrid_none_9_6/SourceTerm/Manager.o] Error 1

scons: building terminated because of errors.

The command "scons compileMode=release order=6 generatedKernels=yes parallelization=hybrid netcdf=yes hdf5=yes commThread=yes arch=ssnb compiler=gcc -j2" exited with 2.

**Comment by alheinecke** [comment]
This issue is due to the fact that travis only uses MPI 2.1 and we request 2.2. The reason is the contained array. 

We should use MPI_SHORT and short this double the ammount of memory, but it's more compatible as these MPI 2.2 extensions are not required.

**Comment by uphoffc** [comment]
Fixed in 467edbe181b21124c18e435e3d995cf9b527750e.
