### ISSUE TITLE
Is there anyone that could publish a whole example case for SeisSol

### ISSUE THREAD

**Issue by duyuan11** [SeisSol/SeisSol#13]
I have tried to generate .neu, .part.np, .def, .par  etc. files by myself, but SeisSol always fails to run smoothly.  I am wondering whether some of you could publish a full example case (including .neu, .part.np, .def, .par  etc. files) for SeisSol, just as those classic cases provided by SPECFEM3D ?

**Comment by rettenbs** [comment]
You are not the only one asking for an example. We are currently discussion what examples we want to have public and how they should be included in the documentation.

**Comment by duyuan11** [comment]
I am really like to have a test run of Seissol, can some of you post a full example case (including .neu, .part.np, .def, .par etc. files) ? It will be heartily appreciated!

**Comment by duyuan11** [comment]
Now, nearly 4 months  have passed,  could you please kindly publish a complete example case?
We are really interested to have a successful first run. Thank you!

**Comment by rettenbs** [comment]
I started a wiki page here:
https://github.com/SeisSol/SeisSol/wiki/First-run

Unfortunately, we still do not have a mesh file which we can publish. However, you can contact [Alice Gabriel](http://www.geophysik.uni-muenchen.de/Members/gabriel). She or somebody from here group might be able to give you a full example.
See also the first statement in the readme: https://github.com/SeisSol/SeisSol/blob/master/README.md

**Comment by rettenbs** [comment]
We have now uploaded a complete setup for the TPV33 benchmark.

You can have a look here: https://github.com/SeisSol/SeisSol/wiki/First-run
Please let me know if there are any problems in the documentation
