### ISSUE TITLE
proj.4 in rconv

### ISSUE THREAD

**Issue by daisy20170101** [SeisSol/SeisSol#133]
When compiling rconv there is an error: couldn't find projects.h which is used in rconv/src/Map.h

I checked proj.4 it seems that it doesn't include projects.h in its installation any more. See https://github.com/OSGeo/PROJ/issues/835.

Should we fix this?

**Comment by uphoffc** [comment]
Using an old version is fine. We use the deprecated API anyhow (see https://proj.org/development/reference/deprecated.html) so we should rather move to the new API at some point in time (currently not necessary from my point of view): https://proj.org/development/migration.html

**Comment by daisy20170101** [comment]
Thanks! This is fixed so I closed it.
