### ISSUE TITLE
Creeping slip problem

### ISSUE THREAD

**Issue by git-taufiq** [SeisSol/SeisSol#137]
Hi,
I got a creeping slip problem in my simulation with fast velocity weakening friction law (FL=103), attached a snapshot of the problem. I used ASAGI to pass the 3D velocity structure and stress field.

![creeping_slip](https://user-images.githubusercontent.com/22062635/66438958-7abb4800-ea2e-11e9-975e-5b7bb44d84f1.JPG)
![creeping_slip_rupture_velocity](https://user-images.githubusercontent.com/22062635/66439482-1b5e3780-ea30-11e9-8e12-ead816fd026d.JPG)

It simulated with SeisSol master branch commit 047a0a03f0847420bacc5c316ff4f68080580092
The problem (not smooth slip) occured if it below certain rupture velocity (Vr) values.

**Comment by sebanger** [comment]
I get the same issue with rate and state. Does anybody know how we can fix this?
![p30_T83_ASI](https://user-images.githubusercontent.com/39982567/67553394-59847800-f70d-11e9-8577-4158930fe5ba.png)

**Comment by uphoffc** [comment]
I think we discussed these issues in July. (Taufiq was involved in the mails so you can ask him.)

**Comment by Thomas-Ulrich** [comment]
correct me if I m wrong:
you came up with a solution which produces smooth slip and limits the creep of the SR, by projecting the SR on the modal basis functions after applying the friction law.
This feature is to be incorporated in the future in the master branch:
An implementation of the feature is available for order 3 to 5 at this fork:
https://github.com/Thomas-Ulrich/SeisSol/tree/filterLSW
Other order can be added on demand.
This simple idea cannot be straightforwardly applied to RS friction laws, which generally do experience less creep than LSW.
Usually, refining the mesh in the creeping area/ using higher-order should fix/limit the creep.

**Comment by uphoffc** [comment]
Yes. But in LSW the state equation is dpsi/dt = |SR|. So filtering |SR| corresponds to filtering the state. You could transfer that idea to RS.

**Comment by Thomas-Ulrich** [comment]
I quickly tried to put the filter at many steps of the routine, and always get nan.
E.g. here after this line
https://github.com/Thomas-Ulrich/SeisSol/blob/filterLSW/src/Physics/Evaluate_friction_law.f90#L1400

```
diff --git a/src/Physics/Evaluate_friction_law.f90 b/src/Physics/Evaluate_friction_law.f90
index 8a13395..a7ce2eb 100644
--- a/src/Physics/Evaluate_friction_law.f90
+++ b/src/Physics/Evaluate_friction_law.f90
@@ -1398,6 +1398,7 @@ MODULE Eval_friction_law_mod
          fss = RS_fw + (flv - RS_fw)/(1.0D0+(tmp/RS_srW)**8)**(1.0D0/8.0D0)
          SVss = RS_a * LOG(2.0D0*RS_sr0/tmp * ( EXP(fss/RS_a)-EXP(-fss/RS_a))/2.0D0)
          LocSV=Svss*(1.0d0-EXP(-tmp*time_inc/RS_sl0))+EXP(-tmp*time_inc/RS_sl0)*SV0
+         LocSR = matmul(DISC%DynRup%filter,LocSV)
          !Mu from LocSR
          tmp = 0.5D0*(LocSR)/RS_sr0 * EXP(LocSV/RS_a)
          LocMu    = RS_a * LOG(tmp+SQRT(tmp**2+1.0D0))
```

**Comment by Thomas-Ulrich** [comment]
fixed through TP branch.
