### ISSUE TITLE
Pvd file not written

### ISSUE THREAD

**Issue by Thomas-Ulrich** [SeisSol/SeisSol#14]
Pvd file (for fault outputs) empty if domain of rank 0 has no rupture boundary elements.
(I understand it is a known bug, but some user may not be aware of that problem).

**Comment by rettenbs** [comment]
Can you test the xdmf_fault branch? This should write the fault in XDMF format which avoids this problem.

**Comment by rettenbs** [comment]
We switched the fault output to XDMF in 48275dc873638b17e5a4ee84a1f7a937da015096 which does not have this problem. Please open a new bug report if there is anything wrong with the XDMF implementation.
