### ISSUE TITLE
Cmake

### ISSUE THREAD

**Issue by ravil-mobile** [SeisSol/SeisSol#144]
Maybe it is better to add the following:
add_subdirectory(${CMAKE_CURRENT_SOURCE_DIR}/submodules/ImpalaJIT)
target_link_libraries(SeisSol-lib PUBLIC yaml-cpp impalajit-static)

instead of this:

https://github.com/SeisSol/SeisSol/blob/e83e23006d16cc951ad114119fbced4c9ee9bf6e/CMakeLists.txt#L204-L206

I tested. It works

**Comment by krenzland** [comment]
We decided to follow another approach and use pkg-config. Will be included in #158.
