### ISSUE TITLE
segmentation fault when using micro partition on supermuc-NG

### ISSUE THREAD

**Issue by mcFishin2039** [SeisSol/SeisSol#149]
Hello, 

When I attempt to run a long simulation (simulation time = 300 s, slurm run time=1:55:00 on partition micro), the simulation abruptly ends. 
The message in the .err file is: 
srun: error: i01r11c03s02: task 0: Segmentation fault (core dumped)

There does not appear to be an issue with the mesh, or other input files. The mesh used is very coarse (93M in size). 
A similar issue is encountered with a slightly larger mesh (size 2.4 G), but the simulation does not even make it past 10 seconds runtime on supermucng. Both meshes were generated with PumGEN. Running the simulations on the test partition yields no errors. The only thing I am changing is the partition in the file submission.sh (with free-surface output) or submission2.sh (no free-surface output). 

my working directory on supermuc ng is 
/hppfs/work/pr63qo/di39cih2/Cascadia/SIMULATIONS/Bruhat_Segall_type_run/TEST

if that helps. 

thank you, 

Marlon

**Comment by Thomas-Ulrich** [comment]
Hi,
This does not look good:
```
Sun Oct 20 21:21:59, Info:  Worker affinity              : "0123456789|0123456789|0123------|----------|--------89|0123456789|0123456789|01--------|----------|------"
Sun Oct 20 21:21:59, Info:  Communication thread affinity: "----------|----------|----456789|0123456789|01234567--|----------|----------|--23456789|0123456789|012345"
```

should rather be like:
```
Sat Oct 19 22:15:31, Info:  Worker affinity              : "0123456789|0123456789|0123456789|0123456789|0123456-89|0123456789|0123456789|0123456789|0123456789|01234-"
Sat Oct 19 22:15:31, Info:  Communication thread affinity: "----------|----------|----------|----------|-------7--|----------|----------|----------|----------|-----5"
```
The log shows that you use an old version of seissol (from 9th May).
Please update your repository and test again your setup.

Thomas.

**Comment by daisy20170101** [comment]
So you asked for 2 hour for the queue and it run for 1:55. Could it terminate because it run out of time?
I would suggest first update SeisSol and then run with more queue time.

**Comment by uphoffc** [comment]
Could you post your job script?

**Comment by Thomas-Ulrich** [comment]
I already checked that. It looks fine.

**Comment by mcFishin2039** [comment]
Yes, Job script: 
#!/bin/bash

# Job Name and Files (also --job-name)

#SBATCH -J cascadia 
#Output and error (also --output, --error):
#SBATCH -o ./%j.%x.out
#SBATCH -e ./%j.%x.err

#Initial working directory (also --chdir):
#SBATCH --workdir=/hppfs/work/pr63qo/di39cih2/Cascadia/SIMULATIONS/Bruhat_Segall_type_run/TEST

#Notification and type
#SBATCH --mail-type=END
#SBATCH --mail-user=ramosmd@umich.edu

# Wall clock limit:
#SBATCH --time=04:00:00
#SBATCH --no-requeue

#Setup of execution environment
#SBATCH --export=NONE
#SBATCH --account=pr63qo
#SBATCH --partition=micro

#Number of nodes and MPI tasks per node:
#max33 so far, else error
#SBATCH --nodes=16
#SBATCH --ntasks-per-node=1
#SBATCH --cpus-per-task=48
#Needs specific MPI
#module switch mpi.intel mpi.intel/2019
#Run the program:
export MP_SINGLE_THREAD=no
unset KMP_AFFINITY
export OMP_NUM_THREADS=94
export OMP_PLACES="cores(47)"

export XDMFWRITER_ALIGNMENT=8388608
export XDMFWRITER_BLOCK_SIZE=8388608
export SC_CHECKPOINT_ALIGNMENT=8388608

export SEISSOL_CHECKPOINT_ALIGNMENT=8388608
export SEISSOL_CHECKPOINT_DIRECT=1
export ASYNC_MODE=THREAD
export ASYNC_BUFFER_ALIGNMENT=8388608
export SEISSOL_ASAGI_MPI_MODE=OFF
source /etc/profile.d/modules.sh

echo $SLURM_NTASKS
srun --export=ALL ./SeisSol_release_generatedKernels_dskx_hybrid_none_9_4 parameters_no_free_surf_output.par

**Comment by mcFishin2039** [comment]
In either parameter file (parameters.par par, parameters_no_free_surf_output.par), the smaller mesh to test it with is CasSlab2-2500

**Comment by daisy20170101** [comment]
export OMP_NUM_THREADS=94

should this be 47? 
@Thomas-Ulrich

**Comment by uphoffc** [comment]
No, that's fine. Simultaneous multi-threading is useful in most cases.

But I had trouble with srun on SuperMUC-NG. You could try to use mpiexec -n $SLURM_NTASKS instead.

**Comment by Thomas-Ulrich** [comment]
Did you fix the problem? Can we close this issue?

**Comment by mcFishin2039** [comment]
Yes, that problem is solved.

Sorry for not updating this earlier.

- Marlon
