### ISSUE TITLE
Option to disable fault output completely

### ISSUE THREAD

**Issue by rettenbs** [SeisSol/SeisSol#15]
Hi,

is there an option to completely disable the fault output? The code seems to accept only OutputPointType = 3, 4 or 5.

Since we do not support element wise ASCII output anymore there should be at least an option to disable the fault output.

Sebastian

**Comment by swollherr** [comment]
Hi,

so far you could use '3' for 'faultreceiver output only' which disables the element wise fault output.
With your commit 52bae911adc1fe1ee0d761f8aace2e7a13a35e84 we can use '0' to disable both outputs.

Stephanie

**Comment by rettenbs** [comment]
The problem with '3' is that you need a fault receiver file. Hopefully the '0' works with the latest commit.
