### ISSUE TITLE
installing latest version of siesol - library issue in python build script with scons

### ISSUE THREAD

**Issue by mcFishin2039** [SeisSol/SeisSol#152]
Hello, 

Marlon again. 

I have uploaded the latest version of seissol from github onto supermucng
My working directory path is 
**/hppfs/work/pr63qo/di39cih2/SeisSol_Oct23/SeisSol-master**

the command  **scons -j 32 buildVariablesFile=supermuc_ng.py**
is unable to find the python libraries 
# import helper
import arch
import libs
import utils.gitversion
in the file **SConstruct** (lines 50 - 52)

I am also unable to use the command pip install arch, for example, to get these libraries. 

Any suggestions/advice is greatly appreciated. 

thanks, 

Marlon

**Comment by Thomas-Ulrich** [comment]
Hi,
you need to clone the submodules.
```
git clone git@github.com:SeisSol/SeisSol.git
cd SeisSol
git submodule update --init
```

**Comment by mcFishin2039** [comment]
I will try this now! 

Thanks!
