### ISSUE TITLE
gmsh2gambit on Segfault: Ids are not contiguous.

### ISSUE THREAD

**Issue by labraha2** [SeisSol/SeisSol#153]
@daisy20170101 
@git-taufiq 

I'm having an issue on segfault creating meshes. At first, I thought it was an error in my .geo so I tested in tpv5 to see if the issue was occurring on other meshes as well. Even meshes that worked in the past I can not create using the gmsh2gambit command.

for **.geo->.msh** 
[segfault tpv5]: gmsh tpv5.geo -3 -optimize
Warning : The '-optimize' option is now obsolete: Gmsh optimizes tetrahedral meshes by default
Warning : Use '-optimize_threshold threshold' to control which elements are optimized
Warning : Option '-optimize_threshold 0' leads to no optimization
.... 
The warnings are new but it still created my .msh 

for **.msh -> .neu**
[segfault tpv5]: gmsh2gambit -i tpv5.msh -o tpv5.neu
Reading MSH...Reading MSH...MSH parse error: Ids are not contiguous.

Is anyone else having this issue on the Segfault cluster?
Is there another way to create meshes that also work?

Thanks!
Lauren Abrahams

**Comment by Thomas-Ulrich** [comment]
Hi Lauren,
The problem is that the mesh format of gmsh changed in the most recent release.
Therefore you should create the mesh with - - format msh2 (if i remember well. See readthedocs, hopefully it is up to date) options and it then should work.
Thomas.

**Comment by labraha2** [comment]
Perfect that was it!

This is also courtesy of Lukas:

# Assumes gmsh, gmsh2gambit and pumgen are in $PATH
gmsh -3 -format msh2 "${filename}.geo"
gmsh2gambit -i "${filename}.msh" -o "${filename}.neu"
pumgen -s gambit "${filename}.neu" "${filename}.h5"
