### ISSUE TITLE
Artifacts at fault intersection

### ISSUE THREAD

**Issue by palgunadi1993** [SeisSol/SeisSol#156]
**Describe the bug**
There is a weird behavior at the fault intersection. This behavior occurs when I give a high value of fluid-pressure ratio (gamma=0.7). However, if I decrease the fluid-pressure ratio (gamma=0.6) the output is fine. I kept all parameters (nucleation, material, and friction) the same, the difference is only the stress magnitude. 

I am using fast velocity weakening friction law (FL=103)

**Expected behavior**
I think, at the fault intersection there should have smooth output and not creating localized very high-low values.

**To Reproduce**
1. commit 047a0a03f0847420bacc5c316ff4f68080580092
      Merge: 6a031bd 72dda58
           Author: Thomas-Ulrich <ulrich@geophysik.uni-muenchen.de>
         Date:   Fri Sep 27 14:26:23 2019 +0200

    Merge pull request #130 from git-taufiq/master
    
    Fix some typographical error

2.
compileMode                 = 'release'
generatedKernels            = 'yes'
measureNodeLevelPerformance = 'none'
useExecutionEnvironment     = 'yes'
logLevel                    = 'warning'
logLevel0                   = 'info'
order                       = '5'
netcdf                      = 'yes'
netcdfDir                   = '/opt/cray/pe/netcdf-hdf5parallel/4.4.1.1.6/INTEL/16.0'
hdf5                        = 'yes'
hdf5Dir                     = '/opt/cray/pe/hdf5-parallel/1.10.1.1/INTEL/16.0'
parallelization             = 'hybrid'
metis                       = 'yes'
metisDir                    = '/opt/cray/pe/tpsl/17.11.1/INTEL64/16.0/haswell/'

asagi='yes'
zlibDir = '/lustre/project/k1047/passonl/seissolTools/ASAGI/build/'
arch = 'dhsw'
compiler = 'cray_intel'
plasticity='no'

Compiler: cray_intel

3. I run it on Shaheen II. 
loaded module:
cray-hdf5-parallel
cray-netcdf-hdf5parallel
PrgEnv-intel
export PKG_CONFIG_PATH=/lustre/project/k1219/ulrich/myLibs/ASAGI/io:/lustre/project/k1219/ulrich/myLibs/ASAGI/build/lib/pkgconfig:/sw/xc40cle6/darshan/3.1.4/sles12.3_gcc7.2.0/lib/pkgconfig:/opt/slurm/default/lib/:/opt/cray/rca/2.2.18-6.0.7.1_5.48__g2aa4f39.ari/lib64/pkgconfig/:/opt/cray/alps/default/lib64/pkgconfig:/opt/cray/xpmem/2.2.15-6.0.7.1_5.11__g7549d06.ari/lib64/pkgconfig:/opt/cray/gni-headers/5.0.12.0-6.0.7.1_3.11__g3b1768f.ari/lib64/pkgconfig:/opt/cray/dmapp/7.1.1-6.0.7.1_6.2__g45d1b37.ari/lib64/pkgconfig:/opt/cray/pe/pmi/5.0.13/lib64/pkgconfig:/opt/cray/ugni/6.0.14.0-6.0.7.1_3.13__gea11d3d.ari/lib64/pkgconfig:/opt/cray/udreg/2.3.2-6.0.7.1_5.13__g5196236.ari/lib64/pkgconfig:/opt/cray/pe/craype/2.5.13/pkg-config:/opt/cray/pe/iobuf/2.0.8/lib/pkgconfig:/opt/cray/pe/fftw/2.1.5.9/lib/pkgconfig:/opt/cray/pe/atp/2.1.1/lib/pkgconfig:/opt/cray/pe/netcdf-hdf5parallel/4.4.1.1.6/INTEL/16.0/lib/pkgconfig:/opt/cray/pe/netcdf/4.4.1.1.6/INTEL/16.0/lib/pkgconfig:/opt/cray/pe/hdf5-parallel/1.10.1.1/INTEL/16.0/lib/pkgconfig:/opt/cray/pe/hdf5/1.10.1.1/INTEL/16.0/lib/pkgconfig

4. 
Files that create the bugs:
[Korea_fault_dip.txt](https://github.com/SeisSol/SeisSol/files/3790093/Korea_fault_dip.txt)
[Korea_initial_stress_dip.txt](https://github.com/SeisSol/SeisSol/files/3790094/Korea_initial_stress_dip.txt)
[Korea_material_dip.txt](https://github.com/SeisSol/SeisSol/files/3790095/Korea_material_dip.txt)
[Korea_nucleation_stress_dip.txt](https://github.com/SeisSol/SeisSol/files/3790096/Korea_nucleation_stress_dip.txt)
[parameters-rs.txt](https://github.com/SeisSol/SeisSol/files/3790097/parameters-rs.txt)

Smooth result:
[Korea_initial_stress_dip.txt](https://github.com/SeisSol/SeisSol/files/3790100/Korea_initial_stress_dip.txt)

The other files are the same.

**Screenshots/Console output**
**Bugs (Slip-rate) (gamma=0.7):**
SRs (view normal to fault plane)
![SRs](https://user-images.githubusercontent.com/35545825/67876800-8986ad80-fb49-11e9-83b9-894684833b14.png)

SRs (view -normal to fault plane)
![SRs-back](https://user-images.githubusercontent.com/35545825/67876806-8b507100-fb49-11e9-96a9-6336ee56bc5a.png)

**Slip-rate (expected) result (gamma=0.6)**
SRs (view normal to fault plane)
![SRs-smooth](https://user-images.githubusercontent.com/35545825/67877073-fac66080-fb49-11e9-8986-29e6a6edd0a1.png)

SRs (view -normal to fault plane)
![SRs-smooth-back](https://user-images.githubusercontent.com/35545825/67877086-ff8b1480-fb49-11e9-93dd-55dee00f2d91.png)

**Bugs (Slip) (gamma=0.7):**
ASl (view normal to fault plane)
![ASl](https://user-images.githubusercontent.com/35545825/67876861-a4592200-fb49-11e9-9b59-98c3a7266cd6.png)

ASl (view -normal to fault plane)
![ASl-back](https://user-images.githubusercontent.com/35545825/67876886-ade28a00-fb49-11e9-9406-09a0357a4777.png)

**Slip (expected) result (gamma=0.6)**
ASl (view normal to fault plane)
![ASl-smooth](https://user-images.githubusercontent.com/35545825/67878576-9658d080-fb4c-11e9-9bfb-0179d19bc71f.png)

ASl (view -normal to fault plane)
![ASl-smooth-back](https://user-images.githubusercontent.com/35545825/67878603-9c4eb180-fb4c-11e9-8f45-bc2262ee442d.png)

**Bugs (Shear-stress) (gamma=0.7):**
Ts0 (view normal to fault plane)
![Ts0](https://user-images.githubusercontent.com/35545825/67877349-77593f00-fb4a-11e9-82d9-069f80be3e6c.png)

Ts0 (view -normal to fault plane)
![Ts0-back](https://user-images.githubusercontent.com/35545825/67877376-83dd9780-fb4a-11e9-9778-7ab0a858064b.png)

No error message in the output

**Additional context**

Do you have any idea?

cc:
@AliceGabriel

**Comment by daisy20170101** [comment]
It seems that this is problem when increasing Pfluid which will reduce effective normal stress. Pfluid goes into RSF trough effective normal stress. Is it possible that Pfluid is too large that causes the numerical scattering?

**Comment by AliceGabriel** [comment]
Kadek, can you please comment on the solution of the problem before closing the issue. I assume decreasing fluid pressure helped avoiding numerical problems in the case of intersecting faults?

**Comment by palgunadi1993** [comment]
Based on many simulations I have done, in the Pohang case, a high fluid-pressure ratio produces numerical artifacts at the fault intersection zone. Using a fluid-pressure ratio lower than 0.6 will overcome numerical stability.

Plasticity decreases the slip-rate and absolute slip. It also does not produce numerical instability at fault intersection for fluid-pressure < 0.75, but still experiencing numerical instability for > 0.75. 

It turns out that low effective normal stress at fault intersection case introduces a numerical instability.

**Comment by daisy20170101** [comment]
Hi, I here follow up on this issue since I have 'scatters' on the fault as well. I am wondering if the  'fluid-pressure ratio lower than 0.6 ' should be a correct fix to numerical stability in the code or case-dependence modification? thanks!
![m35f-td](https://user-images.githubusercontent.com/33549997/157836422-d7677938-1f5d-4342-ae9c-056c88810e65.png)

**Comment by palgunadi1993** [comment]
Hi Duo,

Sorry, I just saw your email as it ended up in my personal email.

My problem was at the fault intersection which was already solved by this pull request (https://github.com/SeisSol/SeisSol/pull/341#issue-900725282). Is it also a fault intersection with the seafloor? 
It may also sometimes appear on the "creeping" part (very low slip rate subject to rupture arrest) or in very low effective normal stress. 

For the pohang case, the numerical artifact was suppressed by adding fault plasticity and increasing plastic cohesion.
Please let me know if the problem is still there.

Cheers,
Kadek
