### ISSUE TITLE
Can SeisSol simulate range zone or block fault broken?

### ISSUE THREAD

**Issue by HakunanMatatat** [SeisSol/SeisSol#159]
hi everyone,Can SeisSol simulate range zone or block fault broken like specfem3d? Thanx.

**Comment by Thomas-Ulrich** [comment]
Hi,
Sorry, I don't understand the question.
Can you point us to some specfem3d documentation about 'range zone or block fault broken' to better understand what you want to model?

Thomas.

**Comment by HakunanMatatat** [comment]
For example,simulate seismic wave propagate or focal mechanism of fault in a small scale block domain.

**Comment by Thomas-Ulrich** [comment]
This is still not very clear. 
Seismic wave propagation and kinematic sources can be for sure modeled in SeisSol, whatever the scale of the model. I close the issue now. You can reopen if you have more information to share about what you want to model.
