### ISSUE TITLE
"utils/logger.h" not found in src/Checkpoint/Checkpoint.h 

### ISSUE THREAD

**Issue by Ckins** [SeisSol/SeisSol#16]
some header files can not be found, for example:

In file included from src/Checkpoint/mpio/Fault.h(49),
                 from src/Checkpoint/mpio/Fault.cpp(42):
src/Checkpoint/mpio/CheckPoint.h(48): catastrophic error: cannot open source file "utils/env.h"
  #include "utils/env.h"

[error.log.txt](https://github.com/SeisSol/SeisSol/files/211584/error.log.txt)

**Comment by rettenbs** [comment]
Hi,

you probably forgot to checkpoint the submodules. Use `git clone --recursive` to clone SeisSol, or if you already cloned the main repository, use `git submodule update --init --recursive` to clone all submodules as well.

Best,
Sebastian
