### ISSUE TITLE
compiling Asagi

### ISSUE THREAD

**Issue by mcFishin2039** [SeisSol/SeisSol#162]
hello, 

We are building Seissol on a local cluster in Michigan. 

At the point of compiling ASAGI, the compiler has an issue with NUMA_LIBRARY.  I can find numa.h, but not a library. Has anyone encountered this issue before? 

thanks, 

Marlon

**Comment by Thomas-Ulrich** [comment]
On supermuc, the numa lib folder is:
```
/dss/dsshome1/lrz/sys/spack/release/19.1/opt/x86_avx512/numactl/2.0.11-gcc-elmypjs/lib/
```
and contains:
```
libnuma.a  libnuma.la  libnuma.so  libnuma.so.1  libnuma.so.1.0.0
```
This folder is added to the $LIBRARY_PATH when loading the module.
According to TUM, compiling ASAGI with `-DNONUMA=on` should not lead to significant loss of performance, so maybe that is the most straightforward way to solve your problem.

**Comment by mcFishin2039** [comment]
Great, I will try that! 

M
