### ISSUE TITLE
TVP33 fails with an assert or a segfault 

### ISSUE THREAD

**Issue by schauveau** [SeisSol/SeisSol#17]
The TPV33 test described in https://github.com/SeisSol/SeisSol/wiki/First-run fails with either a segfault (in release mode) or an  assert (in debug mode). 

```
# mpirun -n 8 ../build/SeisSol_debug_generatedKernels_snoarch_mpi_none_9_3 parameters.par
...
Rank:        0 | Info    | Reading basis functions of order            1
Rank:        0 | Info    | Reading mass matrices   of order            1
Rank:        5 | Error   | initialization Gauss wise
Rank:        6 | Error   | initialization Gauss wise
Rank:        1 | Error   | initialization Gauss wise
Rank:        7 | Error   | initialization Gauss wise
Rank:        2 | Error   | initialization Gauss wise
Rank:        3 | Error   | initialization Gauss wise
Rank:        0 | Error   | initialization Gauss wise
Rank:        4 | Error   | initialization Gauss wise
Rank:        0 | Info    | Tetrahedral Elements 
...
Fri Apr 22 00:30:03, Info:  Performed a total of 0 reductions for maximum difference in 139777 cells. 
Fri Apr 22 00:30:03, Info:  Performed a total of 0 reductions for maximum difference in 139777 cells. 
Fri Apr 22 00:30:03, Info:  Performed a total of 0 reductions for maximum difference in 139777 cells. 
Fri Apr 22 00:30:03, Info:  maximum theoretical speedup (compared to GTS): 1.31244 per cell LTS, 1 with the used clustering. 
SeisSol_debug_generatedKernels_snoarch_hybrid_none_9_2: src/Initializer/MemoryManager.cpp:927: void seissol::initializers::MemoryManager::initial
izeFaceNeighbors(): Assertion `m_internalState.faceNeighbors[l_cell][l_face] != __null' failed.
[hsw215:46020] *** Process received signal ***
[hsw215:46020] Signal: Aborted (6)
[hsw215:46020] Signal code:  (-6)
```

The only suspicious thing in the output before the assert is the 'initialization Gauss wise'. I don't know if that is really significant.

I am using the current git master (b4464acd2eaf1868d097b5c8b1a891772a228dea) 

I followed the procedure currently described in https://github.com/SeisSol/SeisSol/wiki/First-run 

Here are the md5 of the data files I am using.

```
80ea388e641fa512c42aac5eb1115a64  createFR.py
45341023037a416e5a9123381e4c0659  matrices_10.xml
2eeacbc250fe99036d845e61c325944d  matrices_20.xml
98b6f1e80076f4899405f1c8b6eaee96  matrices_35.xml
0e1ffdefa426ba1785415815e147cd2b  matrices_4.xml
50daa56f5667127b2f580b12df86c9ae  matrices_56.xml
6e24c535eb6ff5690db52d16dae61c8e  matrices_84.xml
2604fa9c88f114b6296161357b85123b  parameters.par  (edited as requested so md5 may differ)
33f51e3b61c0d4892d1517ce41e9b0ec  parameters.template
ebe1531fe7b7e7f831d5d47ec4fa8ec6  tpv33_faultreceivers.dat
e033d78f191c0c2adbf6df4a08ce9469  tpv33_gmsh.met.epart.16
362a5004db2f92307963c6fd1ce601ac  tpv33_gmsh.met.epart.32
6e57cf766bfeb1949cb012951e5c7234  tpv33_gmsh.met.epart.8
b7903c555fa69d250c1506afe7add022  tpv33_gmsh.neu
f657c0265dd722f5c3393484668e7429  tpv33_receivers.dat
```

I tried various build variants (mpi/hybrid, snoarch/shsw, order 2/3/4, ...) and they all fail the same way.

My typical build command looks like that 
```
scons  buildVariablesFile=build/options/supermuc_mac_cluster.py compileMode=debug parallelization=mpi arch=snoarch numberOfTemporalIntegrationPoints=1 order=3 generatedKernels=yes netcdf=yes netcdfDir=$NETCDF_C hdf5Dir=$HDF5 -j 4
```
I followed the build instructions except that I used pre-compiled versions of netcdf and  hdf5 which, as far as I know, are working fine. Here is an overview of my environment:

```
Currently Loaded Modulefiles:
  1) slurm/14.11.11                    5) hwloc/1.11.2                      9) hdf5/1.10.0
  2) PrgEnv/Intel+OpenMPI/2016-03-21   6) openmpi/1.10.2                   10) pnetcdf/1.7.0
  3) intel/15.0                        7) szip/2.1                         11) netcdf-c/4.4.0
  4) gdk/352.55                        8) zlib/1.2.8
```

**Comment by swollherr** [comment]
Hi schauveau,

could you also post your edited Parameter file such that we can try to reproduce your error?
Thank you!

**Comment by schauveau** [comment]
Here it is
[parameters.par.txt](https://github.com/SeisSol/SeisSol/files/231583/parameters.par.txt)

By the way, the First-run page says 
```
Replace MESH_FORMAT_TAG with Gambit3D-fast (including the quotation marks)
```
But the quotation marks are obviously missing so I added them

**Comment by rettenbs** [comment]
Thanks for the hint, I updated the documentation

**Comment by schauveau** [comment]
Here are some full execution logs in debug and release modes (mpi only but the behaviour is identical with hybrid). 
[LOG-debug-8.txt](https://github.com/SeisSol/SeisSol/files/231616/LOG-debug-8.txt)
[LOG-release-8.txt](https://github.com/SeisSol/SeisSol/files/231617/LOG-release-8.txt)

**Comment by brietzke** [comment]
quick look suggest you are using order 6 in your input file - but tested
with code compiled with orders 2/3/4
please retry using consistent input
merci
Gilbert

**Comment by schauveau** [comment]
Ok! So you mean that the order value in parameters.par should match the order specified during compilation.

You should probably add that information to the FirstRun page
Thanks

**Comment by swollherr** [comment]
That is probably not the source of the segfault.
The GK version only sends a warning if the compiled order does not match the specified order from the parameter file and overwrites it with the compiled order.

**Comment by brietzke** [comment]
Thanks Stefanie - didn't know it is correcting wrong parameter input.
(in fact it should behave like this) - I just realized the mismatch.
thanks
Gilbert

**Comment by schauveau** [comment]
I just tried with order 2 in parameters and at compile time but that did no change anything.
I am currently running it with 6 but the code has been running silently for several minutes.
The last message  was 'Reading mass matrices   of order            5' 
i am not sure that this Is  normal behaviour. I had other messages before  the crash at lower orders.

**Comment by schauveau** [comment]
It took a while at order 6 but I eventually got the same assert.

Do you think that this could be related to netcfd or hdf5? 
I could try to compile them myself instead of using the system versions.

**Comment by rettenbs** [comment]
The provided example should not use the netCDF/HDF5 libraries. There are only used for our special mesh format and output/checkpointing. Neither is enabled in the example.

Either I messed up the mesh/partition files when assembling the example or one of the last commits broke the code.

Give us a few days to track down the issue.

**Comment by rettenbs** [comment]
We found a problem in the mesh file. Can you try the new version of the mesh file?
https://syncandshare.lrz.de/dl/fiY4t33sAo3xYFdkTzyawLXj/tpv33_gmsh.neu

**Comment by rettenbs** [comment]
I am closing this bug report. Please reopen if the problem still exists.
