### ISSUE TITLE
supermuc phase2 segmentation fault error

### ISSUE THREAD

**Issue by sebanger** [SeisSol/SeisSol#170]
Hi,

I am running on phase 2 (micro) with 40nodes, LTS=2 and CFL= 0.5 a simulation with my fracture network (36.7 million elements). this means in a specific volume I change the BC of each surface to dynamic rupture BC. So far this worked for simple models but now I am running it for a large complex model.
The error appears at two simulations at different time steps: at time 0s (no output at all) and 0.5s.

hal_ibl_read_callback: byte_len=0x1000, smc=0xc
Message id 4978 from task 32 (10.4.24.51) to task 24 (10.4.24.39) timed out.
epoch_ready=1 msg_len=8 hdr_len=24 msg_type=19 hndlr_idx=0
Last progress made at time 4280262006 s. Current time 4265555157 s.
ERROR 1 from file /project/sprelbrew/build/rbrews004a/src/ppe/lapi/Sam.cpp line 879
Sam::CheckTimeout TIMEOUT happened
Message id 876 from task 1 (10.4.24.10) to task 24 (10.4.24.39) timed out.
epoch_ready=1 msg_len=8 hdr_len=24 msg_type=19 hndlr_idx=0
Last progress made at time 4286480902 s. Current time 4277992949 s.
ERROR 1 from file /project/sprelbrew/build/rbrews004a/src/ppe/lapi/Sam.cpp line 879
Sam::CheckTimeout TIMEOUT happened
Message id 5864 from task 25 (10.4.24.40) to task 24 (10.4.24.39) timed out.
epoch_ready=1 msg_len=8 hdr_len=24 msg_type=19 hndlr_idx=0
Last progress made at time 4282274666 s. Current time 4269580477 s.
ERROR 1 from file /project/sprelbrew/build/rbrews004a/src/ppe/lapi/Sam.cpp line 879
Sam::CheckTimeout TIMEOUT happened
Message id 3814 from task 15 (10.4.24.24) to task 19 (10.4.24.28) timed out.
epoch_ready=1 msg_len=0 hdr_len=24 msg_type=19 hndlr_idx=5
Last progress made at time 4289416262 s. Current time 4283863670 s.
ERROR 1 from file /project/sprelbrew/build/rbrews004a/src/ppe/lapi/Sam.cpp line 879
Sam::CheckTimeout TIMEOUT happened
Message id 1629 from task 37 (10.4.24.56) to task 21 (10.4.24.30) timed out.
epoch_ready=1 msg_len=8 hdr_len=24 msg_type=19 hndlr_idx=0
Last progress made at time 4292533980 s. Current time 4290099105 s.
ERROR 1 from file /project/sprelbrew/build/rbrews004a/src/ppe/lapi/Sam.cpp line 879
Sam::CheckTimeout TIMEOUT happened
Message id 5245 from task 18 (10.4.24.27) to task 19 (10.4.24.28) timed out.
epoch_ready=1 msg_len=0 hdr_len=24 msg_type=19 hndlr_idx=5
Last progress made at time 4280517086 s. Current time 4266065317 s.
ERROR 1 from file /project/sprelbrew/build/rbrews004a/src/ppe/lapi/Sam.cpp line 879
Sam::CheckTimeout TIMEOUT happened
ERROR: 0031-250  task 19: Segmentation fault
hal_ibl_read_callback: byte_len=0x1000, smc=0xc
hal_ibl_read_callback: byte_len=0x1000, smc=0xc
ERROR: 0031-250  task 24: Segmentation fault
ERROR: 0031-250  task 8: Segmentation fault
ERROR: 0031-250  task 9: Segmentation fault
ERROR: 0031-161  EOF on socket connection with node i25r01c01s01ib

**Comment by krenzland** [comment]
Please use the issue template "bug report" and indicate how this can be reproduced.
