### ISSUE TITLE
Time step bug in log file (GK and classic)

### ISSUE THREAD

**Issue by AliceGabriel** [SeisSol/SeisSol#18]
Hi,

a potential bug in the standard out of both SeisSol GK and classic with global time stepping: the "Average time step of iteration" after a simulation in the analyse SeisSol part and written by every core is either set to "Infinity" or 0 - may be related to the LTS implementation?

Alice

**Comment by rettenbs** [comment]
The output is generated here:
https://github.com/SeisSol/SeisSol/blob/master/src/ResultWriter/analyse_seissol.f90#L110

I am not sure about classic but in GK the timestep is now longer available in Fortran. Do you still need this output? If not, we can simply remove the lines. (GK prints the timestep at the beginning, at least for GTS.)

**Comment by AliceGabriel** [comment]
Hi, we do not need this output at this point, it can be removed. But: is the time or the timestep variable in this routine depreciated? The timestep variable is used further in the analyse_seissol routine , e.g.
https://github.com/SeisSol/SeisSol/blob/master/src/ResultWriter/analyse_seissol.f90#L127
to call close_plot_fields ..
