### ISSUE TITLE
3d netcdf ASAGI issue - how to enable NUMA support? 

### ISSUE THREAD

**Issue by mcFishin2039** [SeisSol/SeisSol#187]
Hello, 

I am trying to implement a 3D prestress (T_d) distribution on a fault, but I encounter the following error upon submission: 

**ASAGI: NUMA communication could not be enabled because the ASAGI is not compiled with NUMA support**

Will this be solved by recompiling SeisSol or do I need to specify a different flag somewhere when I install ASAGI (e.g.,that enables NUMA support)?  
However, I see from the TUM Asagi website (http://tum-i5.github.io/ASAGI/build.xhtml)
 that NUMA support is not encouraged: 
**NONUMA = ON | OFF Do not compile with NUMA support. All intra-node communications will be turned off. [OFF]**

many thanks, 

Marlon

**Comment by uphoffc** [comment]
Hi Marlon,

the text you cite is a description of the NONUMA option and not a discouragement.

In principle you need to compile ASAGI with the NONUMA=off option. However, the error you see is not an actual error just a warning. So it's only a hint that the initialisation might be faster if you recompile ASAGI, but SeisSol is going to run fine.

Best regards,
Carsten

**Comment by mcFishin2039** [comment]
Thank you for clarifying this, Carsten!
