### ISSUE TITLE
2 partitions in cube generator

### ISSUE THREAD

**Issue by uphoffc** [SeisSol/SeisSol#19]
This bug affects the cube generator in preprocessing/meshing/cube_c/:

If the number of partitions is 2 in a spatial dimension and one selects periodic boundary conditions, then the number of boundary ranks will be wrong. So if e.g.
x x // x is a partition
then x will have 2 neighboring ranks but in reality it has only one, which leads to a crash if the generated mesh is used in SeisSol.

The issue comes, I think, from lines 1062-1197 in main.cpp, where (e.g. --px = 2)
if ((boundary == 6 && numPartitions[0] > 1) || x != 0) {
(...) ++bndSize; (...)
if ((boundary == 6 && numPartitions[0] > 1) || x != numPartitions[0]-1) {
(...) ++bndSize; (...)
is taken twice instead of once.

I think one of the branches has to catch this case (but which one)?

**Comment by rettenbs** [comment]
This is more difficult to fix due to the internals of the current format. I am marking this as "wontfix".
