### ISSUE TITLE
Issue with compilation: object has no attribute 'XdmfWriterSourceFiles'

### ISSUE THREAD

**Issue by aeleuterio** [SeisSol/SeisSol#20]
Hi,
I am trying to compile SeisSol in a Linux CentOS environment. I have HDF5, Scons 2.2.0 (and 2.5.0) and NetCDF all in place - I used your instructions to install them.
When I run:

`$ scons -f SConstruct buildVariablesFile=build/options/supermuc_mac_cluster.py compileMode=release arch=dnoarch numberOfTemporalIntegrationPoints=1 order=2 generatedKernels=yes netcdf=yes netcdfDir=/home/seisol/installed_files/ hdf5Dir=/home/packages/seisol/installed_files/ -j 32`

I get the following output (I am pasting only the relevant part):
`scons: warning: Ignoring missing SConscript 'build/build_release_generatedKernels_dnoarch_hybrid_none_9_2/xdmfwriter/SConscript'
File "/home/packages/seisol/SeisSol-201511/src/SConscript", line 62, in <module>
AttributeError: 'SConsEnvironment' object has no attribute 'XdmfWriterSourceFiles':`

How can I fix this and finish compiling SeisSol? Also, what is the best way for me to determine the values of arch and order?

Thank you in advance

**Comment by rettenbs** [comment]
Hi,

have you cloned all the submodules?

Best regards

**Comment by aeleuterio** [comment]
@rettenbs thanks for the reply.
As far as I know, yes. Which submodules should I check for?

**Comment by rettenbs** [comment]
The xdmfwriter submodule is the problem.

If you have the xdmfwriter submodule you might use the wrong version for your SeisSol version. Earlier versions of the XDMF writer required an additional source file which required some SCons modifications. This is no longer required and also removed in SeisSol: https://github.com/SeisSol/SeisSol/commit/e3af85a278f16b4e0d8b33da573cc7bbc42a6b0b

To checkout the correct submodule version, use `git submodule update`.

**Comment by aeleuterio** [comment]
@rettenbs on my environment I don't have access to git (it is offline and I have to download the files on separated machine and move them). With that in mind, I downloaded the SeisSol-201511.tar.gz release version and in the submodules folder, all the subfolders are empty. The same happens if I download the .zip of SeisSol's master branch.

So I download the master branches of what the GitHub page points to (cxxtest, glm, pugixml, utils, xdmfwriter) and put it in the submodules corresponding folders, but I am still getting the same error.

**Comment by rettenbs** [comment]
Using SeisSol-201511.tar.gz and the master from XMDF Writer repository will not work for the reason described above. Using the .zip from the master from all repositories should work with the current version but this might not always be the case.

I suggest that you clone the repository (including submodules) to your local machine and then create an archive of your local copy and move this one to your final environment. It is the only way to guarantee that you have the correct version for all submodules.

**Comment by aeleuterio** [comment]
Thank you for the suggestion.
I cloned the repository using Git Bash client for Windows, ran git pull on the master but still have empty folder for the submodules. Given that they link to other repositories, do I need to set anything else separately?

@rettenbs once again, thank you for answering these questions that don't relate directly to SeisSol, it is greatly appreciated

**Comment by swollherr** [comment]
Please use the following command to check out SeisSol including all submodules:
git clone --recursive https://github.com/SeisSol/SeisSol.git

This should result in non-empty submodule folders.

**Comment by rettenbs** [comment]
I updated the "known issues" page with 2 bullet point to prevent such problems in the future: https://github.com/SeisSol/SeisSol/wiki/Known-Issues
