### ISSUE TITLE
errors in build files when compiling

### ISSUE THREAD

**Issue by markyoder** [SeisSol/SeisSol#202]
**Describe the bug**
A clear and concise description of what the bug is. Tell us what the code actually does.
1) I am compiling on an HPC system, so most of the dependencies are met via LMOD modules (aka,`module load netcdf` ), I think I have all the paths sorted out, but I could use some clarification on exactly what `netcdfDir=...` does (aka, sets an environment variable?).
2) When I compile, I get a bunch of `no endif` errors in the build files, like

`build/build_release_generatedKernels_dnoarch_hybrid_none_9_4/generated_code/subroutine.cpp(36): error: the #endif for this directive is missing
  #ifdef __SSE3__`

my compile command is:
`scons compiler=$SS_CC compileMode=release order=4 parallelization=hybrid hdf5=yes netcdf=yes metis=yes asagi=yes netcdfDir=${NETCDF_DIR}  hdf5Dir=${HDF5_DIR}  metisDir=${PARMETIS4_DIR} zlibDir=${ASAGI_DIR}/build/lib useExecutionEnvironment=yes arch=dnoarch `

Looking briefly at those build files, the error appears to be exactly what it says it is; there are `ifdef` blocks that appear to not be closed.

**Expected behavior**
compile successfully.
A clear and concise description of what you expected to happen. Tell us what you want the code to do.

**To Reproduce**
1. Which version do you use? Provide branch and commit id.
latest snapshot
2. Which build settings do you use? Which compiler version do you use? 
OHPC Intel 2019 stack or gnu 8.3.0 stack, different MPIs as well. same behavior.
[install_seissol.sh.txt](https://github.com/SeisSol/SeisSol/files/4378462/install_seissol.sh.txt)

3. On which machine does your problem occur? If on a cluster: Which modules are loaded?
See attached install script. Most of the SW is Open HPC.

4. Provide parameter/material files.
(see attached).

Thanks!

**Screenshots/Console output**
If you suspect a problem in the numerics/physics add a screenshot of your output.

If you encounter any errors/warnings/... during execution please provide the console output.
```
build/build_release_generatedKernels_dnoarch_hybrid_none_9_4/generated_code/subroutine.cpp(140): error: the #endif for this directive is missing
  #ifdef __SSE3__
   ^

build/build_release_generatedKernels_dnoarch_hybrid_none_9_4/generated_code/subroutine.cpp(115): error: the #endif for this directive is missing
  #ifdef __SSE3__
   ^

build/build_release_generatedKernels_dnoarch_hybrid_none_9_4/generated_code/subroutine.cpp(90): error: the #endif for this directive is missing
  #ifdef __SSE3__
   ^

```

Thanks!

**Additional context**

**Comment by sebwolf-de** [comment]
Good morning Mark,
thanks for your report!

I just tried your setting on SuperMUC-NG and it compiled. I checked the subroutine.cpp and there are no IFDEFs in the lines you indicated. Could you post your subroutine.cpp?
Also it is not a good idea to use noarch. We have optimizations for most Intel architectures like Skylake. If you have another system like AMD or ARM we are always interested in optimizing SeisSol for such architectures.
The netcdfDir flag tells scons where to look for the netcdf library. You seem to use it correctly.

Best regards,
Sebastian

**Comment by uphoffc** [comment]
Could you please add which version of libxsmm is loaded?
