### ISSUE TITLE
Northridge Kinematic Example incorrectly interpreting .nrf file

### ISSUE THREAD

**Issue by labraha2** [SeisSol/SeisSol#228]
**Describe the bug**
I attempted to run the Northridge kinematic example. I can see SeisSol is reading in the kinematic nrf file; however, the results in the output receiver files and paraview files show all zeros, which makes me think SeisSol may not be reading the nrf file correctly.

I see in the output files that SeisSol is reading in the northridge.nrf file,
**Wed Jul 22 13:18:02, Info:  Reading ./northridge.nrf**
however, in receiver output, it shows the time steps but all other values (sigma xx … u, v,w) remain zero.
**TITLE = "Temporal Signal for receiver number 00001"
VARIABLES = "Time","xx","yy","zz","xy","yz","xz","u","v","w"
 x1       0.000000000000e+00
 x2       2.300000000000e+04
 x3       0.000000000000e+00
  0.000000000000000e+00  0.000000000000000e+00  0.000000000000000e+00  0.000000000000000e+00  0.000000000000000e+00  0.000000000000000e+00  0.000000000000000e+00  0.000000000000000e+00  0.000000000000000e+00  0.000000000000000e+00
  5.000000000000000e-03  0.000000000000000e+00  0.000000000000000e+00  0.000000000000000e+00  0.000000000000000e+00  0.000000000000000e+00  0.000000000000000e+00  0.000000000000000e+00  0.000000000000000e+00  0.000000000000000e+00
  1.000000000000000e-02  0.000000000000000e+00  0.000000000000000e+00  0.000000000000000e+00  0.000000000000000e+00  0.000000000000000e+00  0.000000000000000e+00  0.000000000000000e+00  0.000000000000000e+00  0.000000000000000e+00
  1.500000000000000e-02  0.000000000000000e+00  0.000000000000000e+00  0.000000000000000e+00  0.000000000000000e+00  0.000000000000000e+00  0.000000000000000e+00  0.000000000000000e+00  0.000000000000000e+00  0.000000000000000e+00
  2.000000000000000e-02  0.000000000000000e+00  0.000000000000000e+00  0.000000000000000e+00  0.000000000000000e+00  0.000000000000000e+00  0.000000000000000e+00  0.000000000000000e+00  0.000000000000000e+00  0.000000000000000e+00
  2.500000000000000e-02  0.000000000000000e+00  0.000000000000000e+00  0.000000000000000e+00  0.000000000000000e+00  0.000000000000000e+00  0.000000000000000e+00  0.000000000000000e+00  0.000000000000000e+00  0.000000000000000e+00
…
  9.995000000000163e+00  0.000000000000000e+00  0.000000000000000e+00  0.000000000000000e+00  0.000000000000000e+00  0.000000000000000e+00  0.000000000000000e+00  0.000000000000000e+00  0.000000000000000e+00  0.000000000000000e+00**
 

**Expected behavior**
I would expect that after reading the .nrf file it would create an initial condition/forcing that is reflected in the receiver outputs. 

**To Reproduce**
I pulled the files from your directory here:
https://github.com/daisy20170101/SeisSol_Cookbook/tree/master/Northridge

Note: I did not produce the nrf file nor do I know how to visualize it, so it may be an error in the nrf vs an error in the code. If I could obtain more information on how to create the nrf file that would be very helpful.

Thank you,
Lauren Abrahams

**Comment by daisy20170101** [comment]
Hi, Lauren,
I will check the nrf file and try to fix the problem.

**Comment by sebwolf-de** [comment]
Hi Lauren, you can use [h5dump](https://support.hdfgroup.org/HDF5/doc/RM/Tools/h5dump.htm) to show the nrf file. It is a really basic command line tool and just gives you raw data. We do not have any tools to visualize the nrf files. [krfviewer](https://github.com/SeisSol/Geodata/tree/master/krfviewer) can be used to visualize srf files.

**Comment by daisy20170101** [comment]
Hi Lauren,
I just updated a new northridge.nrf file. This works well in our cluster. Please check if it works now.

**Comment by labraha2** [comment]
Perfect, the nrf file is working correctly now!

And excellent the h5dump helps me view the nrf file. 

Could I have more information on how the nrf file gets created?  So I could create a file if I wanted to run a different kinematic problem/ scenario?

**Comment by uphoffc** [comment]
https://seissol.readthedocs.io/en/latest/standard-rupture-format.html

**Comment by daisy20170101** [comment]
Updating the .nrf file has fixed the issue.
