### ISSUE TITLE
CMake: Gemm tools

### ISSUE THREAD

**Issue by uphoffc** [SeisSol/SeisSol#250]
The default for -DGEMM_TOOLS is currently Eigen. I think the default here should depend on the selected architecture (skx, hsw, arm, etc.)

GEMM_TOOLS is also not documented here: https://seissol.readthedocs.io/en/latest/compilation.html (but installing libxsmm is, which does not make sense.)

**Comment by ravil-mobile** [comment]
Hi, I guess one of the reasons was that Eigen can work on all platforms. The second reason was that Eigen is in submodules and always available. But, I agree with you that 99% of time we use x86 and it makes sense to make libxsmm as the default option

**Comment by krenzland** [comment]
So I see two ways of dealing with this:
- Set the defaults from the platform (e.g. use psamm/libxsmm for skylake)
- Keep eigen as default and print a warning.

First option can potentially be confusing, second one might be missed by some users.

@ravil-mobile Can I assign you for this? I'll deal with the external projects.

**Comment by krenzland** [comment]
Fixed by #260.
