### ISSUE TITLE
GCC + rate and state friction very slow

### ISSUE THREAD

**Issue by uphoffc** [SeisSol/SeisSol#256]
**Describe the bug**
DR is really slow with gcc 9.2.0

**Expected behavior**
Should as fast as with icc 19.1.0

**To Reproduce**
1. Which version do you use? master
2. Which build settings do you use? gcc 9.2.0 
3. On which machine does your problem occur? Sandy bridge (16 core) and Xeon gold (40c) machine
4. Provide parameter/material files. No.

**Screenshots/Console output**
gcc:
Thu Oct 15 15:46:17, Info:  "computeLocalIntegration" ( per element ): 3.39284e-07 (sample size: 437 , standard error: 8.62748e-10 )
Thu Oct 15 15:46:17, Info:  "computeNeighboringIntegration" ( per element ): 2.87025e-07 (sample size: 437 , standard error: 1.33964e-09 )
Thu Oct 15 15:46:17, Info:  "computeDynamicRupture" ( per element ): **0.000136992** (sample size: 409 , standard error: 4.52834e-07 )

icc:
Thu Oct 15 16:01:38, Info:  "computeLocalIntegration" ( per element ): 3.3736e-07 (sample size: 437 , standard error: 5.50422e-10 )
Thu Oct 15 16:01:38, Info:  "computeNeighboringIntegration" ( per element ): 2.90504e-07 (sample size: 437 , standard error: 1.22483e-09 )
Thu Oct 15 16:01:38, Info:  "computeDynamicRupture" ( per element ): **3.32489e-06** (sample size: 409 , standard error: 1.49403e-08 )

**Comment by krenzland** [comment]
I have compared gcc vs Intel on Mahti as well. They use AMD Rome base CPUs. I've ran our Palu scenario which uses a fast-velocity-weakening friction law.
Performance with gcc was roughly 300GFLOP/s per node, with intel roughly 2k GFLOP/s per node.
Running the same setup without DR (Dr faces retagged as interior cells) I also reached 2k GFLOP/s per node with gcc.

Interestingly, the load balance was at roughly 80% for the gcc. I assume some of the performance loss comes also comes from the load imbalance resulting from the slower FL computation. So it's probably unfair to say that gfortran is 10 times slower. But it is definitely **significantly slower**!

**Comment by AliceGabriel** [comment]
Just a quick note that this effects our training example of Palu, which will be next used Friday in a week and then again in the ChEESE training workshop (if we use the Docker image)....

**Comment by krenzland** [comment]
Just for reference, unsafe math is very dangerous and we should be cautious when using it. But: Intel compiler have this on by default when running with optimizations.

**Comment by Thomas-Ulrich** [comment]
dr/merge_master, intel

```
Fri Jul 15 16:03:45, Info:  "computeLocalIntegration" ( constant ): 1.5758e-05 (sample size: 47528 , standard error: 2.66698e-10 )
Fri Jul 15 16:03:45, Info:  "computeLocalIntegration" ( per element ): 1.50248e-07 (sample size: 47528 , standard error: 2.66698e-10 )
Fri Jul 15 16:03:45, Info:  "computeNeighboringIntegration" ( constant ): 3.93338e-05 (sample size: 47528 , standard error: 3.13674e-10 )
Fri Jul 15 16:03:45, Info:  "computeNeighboringIntegration" ( per element ): 1.71343e-07 (sample size: 47528 , standard error: 3.13674e-10 )
Fri Jul 15 16:03:45, Info:  "computeDynamicRupture" ( constant ): 9.46435e-05 (sample size: 36872 , standard error: 2.98477e-09 )
Fri Jul 15 16:03:45, Info:  "computeDynamicRupture" ( per element ): 2.43506e-06 (sample size: 36872 , standard error: 2.98477e-09 )
```
dr/merge_master, gcc:
```
Fri Jul 15 16:05:16, Info:  "computeLocalIntegration" ( constant ): 0.000153771 (sample size: 45400 , standard error: 2.02317e-10 )
Fri Jul 15 16:05:16, Info:  "computeLocalIntegration" ( per element ): 1.67568e-07 (sample size: 45400 , standard error: 2.02317e-10 )
Fri Jul 15 16:05:16, Info:  "computeNeighboringIntegration" ( constant ): 0.000161139 (sample size: 45400 , standard error: 1.76177e-10 )
Fri Jul 15 16:05:16, Info:  "computeNeighboringIntegration" ( per element ): 1.9141e-07 (sample size: 45400 , standard error: 1.76177e-10 )
Fri Jul 15 16:05:16, Info:  "computeDynamicRupture" ( constant ): 0.00041729 (sample size: 29840 , standard error: 7.46057e-09 )
Fri Jul 15 16:05:16, Info:  "computeDynamicRupture" ( per element ): 3.1823e-06 (sample size: 29840 , standard error: 7.46057e-09 )
```

**Comment by Thomas-Ulrich** [comment]
this has been fixed by merging dr/cpp.
