### ISSUE TITLE
Travis CI: 1000min limit

### ISSUE THREAD

**Issue by krenzland** [SeisSol/SeisSol#267]
Last week, Travis CI updated the limitations of their free plan (which we are using).
See [here](https://blog.travis-ci.com/2020-11-02-travis-ci-new-billing.) for details.

> For those of you who have been building on public repositories (on travis-ci.com, with no paid subscription), we will upgrade you to our trial (free) plan with a 10K credit allotment (which allows around 1000 minutes in a Linux environment).
As one of our builds takes roughly 70 minutes (17 min * 4 sub-jobs), we can test only 14 commits/PR per month!

While there seems to be the possibility of increasing the number of free minutes:

> We will be offering an allotment of OSS minutes that will be reviewed and allocated on a case by case basis. Should you want to apply for these credits please open a request with Travis CI support stating that you’d like to be considered for the OSS allotment. Please include:
> 
>     Your account name and VCS provider (like travis-ci.com/github/[your account name] )
>     How many credits (build minutes) you’d like to request (should your run out of credits again you can repeat the process to request more or discuss a renewable amount)
this is likely going to be very annoying.

So we should consider some alternatives **soon**.

**Comment by krenzland** [comment]
Azure-CI seems to be the best free option (10 parallel jobs, unlimited time even for free tier). I have a configuration that should already work here: https://github.com/SeisSol/SeisSol/tree/azure-pipelines.
Output would then look like this: https://dev.azure.com/lukas0172/SeisSol/_build/results?buildId=29&view=results
(Not sure whether it still builds with current master)

**Comment by ravil-mobile** [comment]
But, maybe azure-CI will end up like Travis at some point? I mean it will become limited or fully paid. I think that in any case we can reduce our test-time a bit  if we switch to our containers for testing

**Comment by krenzland** [comment]
I don't see how containers can reduce the build time.
And sure, maybe it's going to end up like travis. But that's also not really helpful, because we need some solution soon. And our self-hosted (or rather LRZ hosted) option still needs some time.

**Comment by ravil-mobile** [comment]
I meant containers could reduce time *a bit* because you won't need to install yaml-cpp, netcdf-4.6.1, libxsmm again and again

**Comment by sebwolf-de** [comment]
True, it always makes me cringe, when I think about how often we compiled yaml-cpp, ... with the same settings. But that's the topic for another discussion.
But I guess using a container with precompiled yaml-cpp, netcdf, ... doesn't significantly reduce the build time. Unfortunately there aren't any timers in the azure output to quantify. 
Right _now_ azure has unlimited minutes for open source projects, so I'd be in favour of changing. Also thanks to Lukas' previous work, switching would not be a major overhead.

**Comment by krenzland** [comment]
Yes, I'm currently working a bit on the azure stuff. Build works currently, parallel builds not yet.
