### ISSUE TITLE
Problem with output mesh in HDF5 as well as raw binary formats

### ISSUE THREAD

**Issue by sonVishal** [SeisSol/SeisSol#27]
#26 The commit [Simplify vertexInBox](https://github.com/SeisSol/SeisSol/commit/627aa27124ca93cf65db31768a2e260d9eee032b) has somehow broken the default behaviour when the output region bounds are not provided by the user. Restoring to the old function (that is replacing the code on the latest commit by the old code) solves this issue.

This issue is valid for both HDF5 and raw binary outputs. The behaviour in case the output region is specified by the user is unchanged and works as expected.

In the default behaviour, i.e. when the entire mesh is to be outputted, the HDF5 format outputs the mesh with a small chunk missing while in the raw binary format we see only a couple of chunks of the mesh.

**Comment by rettenbs** [comment]
Solved in #28
