### ISSUE TITLE
Memory allocation problem

### ISSUE THREAD

**Issue by AlexV321** [SeisSol/SeisSol#270]
Good day, 

I am trying to test Seissol on the "tpv33" data step by step as described in the Documentation. I have compiled seissol with hybrid parallelization option using cmake.
My execution is : mpiexec -np 4 ./Seissol parameters.par 
After succsessful reading of the input file i got the following errors:

In file '/home/alex/work/SS/SeisSol/src/Initializer/dg_setup.f90', around line 2354: Error allocating 384309531648 bytes: Cannot allocate memory
--------------------------------------------------------------------------
Primary job  terminated normally, but 1 process returned
a non-zero exit code. Per user-direction, the job has been aborted.
--------------------------------------------------------------------------
In file '/home/alex/work/SS/SeisSol/src/Initializer/dg_setup.f90', around line 2354: Error allocating 176423869440 bytes: Cannot allocate memory
--------------------------------------------------------------------------
mpiexec detected that one or more processes exited with non-zero status, thus causing
the job to be terminated. The first process to do so was:

  Process name: [[55934,1],2]
  Exit code:    1

I just wonder does this problem related to hardware? i mean, what are the minimum requirements to RAM and to disk space for succsessful execution of Seissol on the test data "tpv33"?

I have attached full terminal output of the Seissol execution.
[term_output.txt](https://github.com/SeisSol/SeisSol/files/5530611/term_output.txt)

**Comment by Thomas-Ulrich** [comment]
Hi,

On which machine does your problem occur? cluster?
How much RAM do you have?

**Comment by AlexV321** [comment]
Hello Thomas-Ulrich,

I have 8GB RAM, i am trying to execute it on my laptop with 8 CPU cores.

**Comment by Thomas-Ulrich** [comment]
Maybe 8Gb of ram is not sufficient for a 1mio mesh with order 6? Could you try order 3?

**Comment by AlexV321** [comment]
Thank you, i tried both cases -DORDER=3 and even -DORDER=2 with cmake and executions
mpiexec -np 4 ./Seissol_Release_dnoarch_3_elastic parameters.par
mpiexec -np 4 ./Seissol_Release_dnoarch_2_elastic parameters.par
give me the same kind of error.
But now, for order 2, i noticed that the required amount of memory to allocate is 10 times less than in case of order 6, i. e.
O2: 28615011840 bytes to allocate
O6: 384309531648 bytes to allocate

but if i am not mistaking 28615011840 bytes ~ 28 GB, so 8GB is still not enough right?

**Comment by sebwolf-de** [comment]
Hi, 28GB is indeed a lot here. 
Maybe unrelated, but: `Stack size of 8192 [kb] is lower than recommended minimum of 2097152 [kb]. You can increase the stack size by running the command: ulimit -Ss unlimited`. That's worth a try.
Also as you are running SeisSol only on your Laptop (i.e. one node) you can try to run SeisSol without mpiexec and rely on OpenMP only.

**Comment by krenzland** [comment]
I've had a similar bug on our cluster when running more than one mpi rank. I wasn't able to find the exact reason but switching some packages worked.

So please try running with only one MPI rank. Especially on one (small) machine, MPI doesn't make much sense anyway.

You should also follow Sebastian's comment and try the ulimit command. It's not related to this issue but can lead to other crashes for some scenarios.

**Comment by AlexV321** [comment]
Ok, thanks for feedback, i am not sure how to run seissol with MPI rank 1 properly. I mean how to set MPI rank equal to 1 before execution? I noticed that compiling seissol with options OpenMP=ON but with MPI=OFF just fails.

**Comment by sebwolf-de** [comment]
To run it with one rank use `mpiexec -n 1 ./SeisSol...` or just `./SeisSol...`

**Comment by AlexV321** [comment]
Ok, done, some errors still appear, like
SeisSol_Release_dnoarch_2_elastic: src/common/id-generator/id-generator.c:76: id_gen_safe_register: Assertion `s_id_gen_safe_table != NULL' failed.

Output file is attached
[mpirun_2.txt](https://github.com/SeisSol/SeisSol/files/5566054/mpirun_2.txt)

**Comment by Thomas-Ulrich** [comment]
I would disable the communication thread (see in ccmake) and use `export OMP_NUM_THREADS=4` before running seissol.

**Comment by sebwolf-de** [comment]
Hi, some remarks: 

- Compile with your actual architecture and not noarch. Use `cat /etc/

**Comment by sebwolf-de** [comment]
Sorry, misclicked.

**Comment by AlexV321** [comment]
Sorry, i haven't idea what should i set for HOST_ARCH if i have intel architecture of my processor. command "more /proc/cpuinfo" gives me
processor	: 2
vendor_id	: GenuineIntel
cpu family	: 6
model		: 142
model name	: Intel(R) Core(TM) i5-8250U CPU @ 1.60GHz
stepping	: 10
cpu MHz		: 1800.001
cache size	: 6144 KB
physical id	: 0
siblings	: 4

**Comment by krenzland** [comment]
HOST_ARCH=hsw should work well.

**Comment by AlexV321** [comment]
Sorry, i forgot to add, i am using virtual machine so i have only 4GB RAM and 4 cpu cores. Don't know if it is too few. But i did all suggested manipulations and still got this
--------------------------------------------------------------------------
Primary job  terminated normally, but 1 process returned
a non-zero exit code. Per user-direction, the job has been aborted.
--------------------------------------------------------------------------
--------------------------------------------------------------------------
mpiexec noticed that process rank 0 with PID 0 on node localhost exited on signal 11 (Segmentation fault).

Maybe the best way would be try it on another machine.

**Comment by sebwolf-de** [comment]
Can you give the output of SeisSol before the segfault?

**Comment by AlexV321** [comment]
Yes, attached one below.
[mpirun_3.txt](https://github.com/SeisSol/SeisSol/files/5566701/mpirun_3.txt)

**Comment by krenzland** [comment]
I'm not sure that this error has anything directly to do with SeisSol. When I google the path where the job fails ("src/common/id-generator/id-generator.c", I can only find some references to https://en.wikipedia.org/wiki/Parallel_Virtual_File_System#PVFS2. What kind of vm are you using?

**Comment by AlexV321** [comment]
I am using Oracle VMware 6.1.14 r140239 (Qt5.6.2)

**Comment by sebwolf-de** [comment]
Can you build a Debug Version of SeisSol (use ccmake). Then do `gdb --ex=r --args ./Seis.. parameters.par`. Once the program stopped, type `bt` to see where the error happens.

**Comment by krenzland** [comment]
Sorry, I meant what operating system?

**Comment by AlexV321** [comment]
I am using fedora32 linux 64 bit version.
Well, i tried to complete backtrace after execution.  But after the execution was done, i had to run gdb once more to type "bt" to open gdb prompt again. And it tells me only "No stack size". Please see attachments of seissol debug version execution.
[debug_1.txt](https://github.com/SeisSol/SeisSol/files/5568082/debug_1.txt)

**Comment by sebwolf-de** [comment]
Okay, the process has been killed now, which is different from the segfault before. If you contact me via email, I can give you access to a virtual box image, where SeisSol is running.

**Comment by AlexV321** [comment]
Yes, could you provide your e-mail? As i understand pumgen package installed there too?

**Comment by sebwolf-de** [comment]
The email is wolf.sebastian [at] in.tum.de. I have installed pumgen there.

**Comment by sebwolf-de** [comment]
I guess this is fixed now
