### ISSUE TITLE
Add a check for METIS separately

### ISSUE THREAD

**Issue by ravil-mobile** [SeisSol/SeisSol#275]
Despite it is written in the documentation that one needs to copy metis.h and libmetis to $HOME/include and $HOME/lib, there are people - e.g., Ravil - who can easily forget about this. As a result, cmake complains about ParMetis, however, the real issue is metis. It becomes confusing and leads to several hours of debugging. Therefore, we need to introduce additional cmake fille. 

https://github.com/SeisSol/SeisSol/blob/370b23223352da2ad56a26d8ee01869c05c69626/CMakeLists.txt#L222

**Comment by sebwolf-de** [comment]
I've stumbled across the same problem once ;-)
There is already a check for metis here: https://github.com/SeisSol/SeisSol/blob/370b23223352da2ad56a26d8ee01869c05c69626/cmake/FindParMETIS.cmake#L70, but the error handling is not good enough.

**Comment by sebwolf-de** [comment]
Will be fixed by #279 .
