### ISSUE TITLE
Code of Conduct

### ISSUE THREAD

**Issue by krenzland** [SeisSol/SeisSol#288]
Hi all,

in our meeting today we came to the conclusion that it would be nice to have a code of conduct (CoC).
@AliceGabriel suggested something similar to the PETSc CoC which is based on the [contributor covenant.](https://www.contributor-covenant.org/version/2/0/code_of_conduct/).
Of course, we are open for other suggestions!

Personally, I like the suggested one, as it's basically "be nice to each other" and does not include anything which could lead to controversies. I especially like that it separates behavior in private and when representing this project. I also like that conflicts should be handled anonymous.

I suggest that we add this (or a similar CoC). I also suggest that we nominate ~2 people from LMU/TUM each to represent both communities as contact persons.This CoC would then apply to all repositories hosted by this Github organization.

What do you think? If no one complains in about a week or so, I'll open a pull request to this repo.

Cheers,
Lukas

**Comment by Thomas-Ulrich** [comment]
Honestly, I doubt it would be of any help but I m not against trying.

**Comment by krenzland** [comment]
I also don't see it as a necessity but I do not see any downsides. If we have one, we signal that we care about inclusion/openness to all collaborators, etc.

**Comment by ravil-mobile** [comment]
hmmm, it is a pity. I collected some information about Code of Conduct, Contribution, etc from other projects like llvm, singularity, spack, docker, etc but I forgot to press om `comment`. Ok, I will repeat the process again

**Comment by krenzland** [comment]
@ravil-mobile I would like to create a PR for a CoC soon. Should we wait for your contribution or can we go ahead with the contributor covenant?

For all others, please state possible objections in this issue! This should be a community effort and not something that is decided by a small minority. Thanks!

**Comment by ravil-mobile** [comment]
Sorry for delay. I will do it today

**Comment by ravil-mobile** [comment]
### Code of conduct
[llvm](https://llvm.org/docs/CodeOfConduct.html) - it is very nice. I like this style

[singularity](https://github.com/sylabs/singularity-cri/blob/master/CODE_OF_CONDUCT.md) - a template 

[spack](https://github.com/spack/spack/blob/develop/.github/CODE_OF_CONDUCT.md) - a template 

[docker](https://github.com/docker/code-of-conduct/blob/master/code-of-conduct-EN.md) - I guess it is a good example

[rocm](https://github.com/RadeonOpenCompute/rocm-spack/blob/develop/.github/CODE_OF_CONDUCT.md) - a template 

[netcdf](https://github.com/Unidata/netcdf-c/blob/master/.github/CODE_OF_CONDUCT.md) - a template

[pytorch](https://github.com/pytorch/pytorch/blob/master/CODE_OF_CONDUCT.md) - a template

[FEniCS](https://github.com/FEniCS/dolfinx/blob/master/CODE_OF_CONDUCT.md) - a template

---
### Contributing

[singularity](https://github.com/hpcng/singularity/blob/master/CONTRIBUTING.md) - so so

[spack](https://github.com/spack/spack/blob/develop/.github/CONTRIBUTING.md) - a reference to their [documentation](https://spack.readthedocs.io/en/latest/contribution_guide.html#git-workflows) (describes github workflow)

[docker](https://github.com/moby/moby/blob/master/CONTRIBUTING.md) - a detailed explanation of the entire process 

[hdf5](https://github.com/KxSystems/hdf5/blob/master/CONTRIBUTING.md) - basically describes a general github workflow and talks about a style of comments

[netcdf](https://github.com/Unidata/netcdf-c/blob/master/.github/CONTRIBUTING.md) - I like ["The characteristics of an accepted pull request"](https://github.com/Unidata/netcdf-c/blob/master/.github/CONTRIBUTING.md#the-characteristics-of-an-accepted-pull-request-) section

[pytorch](https://github.com/pytorch/pytorch/blob/master/CONTRIBUTING.md) - overkill for us

**Comment by krenzland** [comment]
Thanks! That's very valuable research!
I'll focus only on the CoC here, but your "contributing" examples will be very useful for that discussion.

Singularity/spack/rocm-spack/netcdf/pytorch/fenics all use the contributor's covenant so it seems to be pretty standard. Likely a good choice for us as well then.

Any objections?

They all have a mailing list as contact point, which goes to all maintainers. We do not have something like that (seissol-dev is open to pretty much anyone who works actively on SeisSol development).

@AliceGabriel, @baderml What do you think about this? Who should be a contact person for CoC violations?

**Comment by labraha2** [comment]
This is super great to hear that you are developing a code of conduct. Having a published COC or respectful community policy is important to outwardly show your group values, norms, and expectations. Each individual may walk in with different presumptions of what is acceptable behavior in this group. It is important to understand each other perspectives and create a space with clearly defined rules and expectations. This, in turn, will make a more inclusive community and lead to strong collaborations.

Here is Stanford's recent policy respectful and inclusive behavior: https://earth.stanford.edu/sites/default/files/inline-files/SE3%20Policy%20on%20Respectful%20and%20Inclusive%20Behavior.2020.10.16_1.pdf
Even though this document covers a lot of fieldwork policy, it shows the school's values, how they practice these values,  and definitions for different behaviors. If this policy is just for TUM/LMU there may be places to report or seek advice for conflict, which would be good to list. But if this is a broader collaborative policy, at least outlining values, how they practice these values,  and definitions for different behaviors is important.

**Comment by krenzland** [comment]
@labraha2 thank you for your comment!

> If this policy is just for TUM/LMU there may be places to report or seek advice for conflict, which would be good to list. But if this is a broader collaborative policy, at least outlining values, how they practice these values, and definitions for different behaviors is important.

The intention is for this to be a CoC for contributing to the SeisSol project. 

What do you think of the [contributor covenant](https://www.contributor-covenant.org/version/2/0/code_of_conduct/)? Would be very interesting to have your perspective on that as an external contributor! Do you think that it would help to convey the values, norms and expectations that we as SeisSol developers have?

**Comment by labraha2** [comment]
I think the contributor covenant is well thought out, and it would be great to have the SeisSol project pledge to it. 

The only thing I noticed is much of it is privately done (which is okay in some circumstances). To guarantee success, each community member should be aware of the pledge and be encouraged to be an active "upstander" (someone who will stand up for others vs. someone who would stand by).  For example, suppose two people were writing comments on GitHub and something inappropriate/offensive was said. In that case, a third person could come in and say, "hey, we don't use that language in this community, let's get back to the science," to remind everyone in the community we don't want to see that. Setting these kinds of norms sometimes allows those at different power levels (students, postdoc, professor/faculty) to still make a statement that reflects the community values. 

In addition, to taking the pledge, if the group wanted to show that a COC is vital to their values, having somewhere on the GitHub and/or SeisSol page (such as a tab) to state these ideas is important. This way, it does not get lost in the many great things happening within the group. Really terrific work taking the initiative and thinking more about this!
