### ISSUE TITLE
Time step width is always = 0.0 in classic version

### ISSUE THREAD

**Issue by swollherr** [SeisSol/SeisSol#29]
When running a simulation with the classic version the time step width is always equal to zero and therefore the simulation does not advance in time.
Djamel was testing a setup with one of the old point sources but I run into the same problem when I use a dynamic rupture setup.

**Comment by rettenbs** [comment]
Do we still need to support the classic version? Are there any features not yet available with generated kernels?

**Comment by rettenbs** [comment]
I am closing this bug report since we no longer support the classic version.
