### ISSUE TITLE
cmake SeisSol compilation - which SuperMucNG modules required (potentially wrong documentation)

### ISSUE THREAD

**Issue by AliceGabriel** [SeisSol/SeisSol#295]
**Describe the bug**
I am following along a new Seissol on SuperMucNG user. SeisSol's documented description on using cmake to compile fails, due to 'malfunctioning' mpiicc.

The documentation is here https://seissol.readthedocs.io/en/latest/supermuc.html?highlight=supermuc#supermuc-ng.
I tried two things: loading the recommended modules (leading to error 1 below) and also hand-loading the modules I think are required as follows:
di34pac4@login01:~/SeisSol/build-release> module list
Currently Loaded Modulefiles:
 1) admin/1.0            6) mkl/2019_gcc        11) inspector_xe/2019      16) parmetis/4.0.3-intel-impi-i64-r64          
 2) tempdir/1.0          7) mpi.intel/2019_gcc  12) devEnv/GCC/7-IntelMPI  17) metis/5.1.0-intel-i64-r64                  
 3) spack/release/19.2   8) itac/2019           13) cmake/3.14.4           18) numactl/2.0.11                             
 4) lrz/1.0              9) advisor_xe/2019     14) python/3.6_intel       19) hdf5/1.8.21-impi-cxx-frt-threadsafe        
 5) gcc/7               10) amplifier_xe/2019   15) libszip/2.1.1          20) netcdf/4.6.1-intel-impi-hdf5v1.8-parallel  

Trying to run a simple test
di34pac4@login01:~/SeisSol/build-release> mpiicc a.c 

<img width="339" alt="Screenshot 2021-02-15 at 22 59 32" src="https://user-images.githubusercontent.com/9365956/107996770-78cda580-6fe1-11eb-91fa-4ed33d500f13.png">

leads to
/lrz/sys/intel/impi2019u6/impi/2019.6.154/intel64/bin/mpiicc: line 545: icc: command not found

**Expected behavior**
Compiling.

**To Reproduce**
checkout current master and follow the documentation.

**Screenshots/Console output**

di34pac4@login01:~/SeisSol/build-release> cmake -DCOMMTHREAD=ON -DASAGI=ON -DCMAKE_BUILD_TYPE=Release -DHOST_ARCH=skx -DPRECISION=single -DORDER=4 -DCMAKE_INSTALL_PREFIX=$(pwd)/build-release -DGEMM_TOOLS_LIST=LIBXSMM,PSpaMM -DPSpaMM_PROGRAM=~/bin/pspamm.py ..
-- The C compiler identification is unknown
-- The CXX compiler identification is unknown
-- The Fortran compiler identification is unknown
/lrz/sys/intel/impi2019u6/impi/2019.6.154/intel64/bin/mpiifort: line 709: ifort: command not found
-- Check for working C compiler: /lrz/sys/intel/impi2019u6/impi/2019.6.154/intel64/bin/mpiicc
-- Check for working C compiler: /lrz/sys/intel/impi2019u6/impi/2019.6.154/intel64/bin/mpiicc -- broken
CMake Error at /dss/dsshome1/lrz/sys/spack/release/19.2/opt/x86_avx512/cmake/3.14.4-gcc-c2wamsw/share/cmake-3.14/Modules/CMakeTestCCompiler.cmake:60 (message):
  The C compiler

    "/lrz/sys/intel/impi2019u6/impi/2019.6.154/intel64/bin/mpiicc"

  is not able to compile a simple test program.

  It fails with the following output:

    Change Dir: /dss/dsshome1/08/di34pac4/SeisSol/build-release/CMakeFiles/CMakeTmp
    
    Run Build Command(s):/usr/bin/gmake cmTC_e3238/fast 
    /usr/bin/gmake -f CMakeFiles/cmTC_e3238.dir/build.make CMakeFiles/cmTC_e3238.dir/build
    gmake[1]: Entering directory '/dss/dsshome1/08/di34pac4/SeisSol/build-release/CMakeFiles/CMakeTmp'
    Building C object CMakeFiles/cmTC_e3238.dir/testCCompiler.c.o
    /lrz/sys/intel/impi2019u6/impi/2019.6.154/intel64/bin/mpiicc    -o CMakeFiles/cmTC_e3238.dir/testCCompiler.c.o   -c /dss/dsshome1/08/di34pac4/SeisSol/build-release/CMakeFiles/CMakeTmp/testCCompiler.c
    /lrz/sys/intel/impi2019u6/impi/2019.6.154/intel64/bin/mpiicc: line 558: icc: command not found
    CMakeFiles/cmTC_e3238.dir/build.make:65: recipe for target 'CMakeFiles/cmTC_e3238.dir/testCCompiler.c.o' failed
    gmake[1]: *** [CMakeFiles/cmTC_e3238.dir/testCCompiler.c.o] Error 127
    gmake[1]: Leaving directory '/dss/dsshome1/08/di34pac4/SeisSol/build-release/CMakeFiles/CMakeTmp'
    Makefile:121: recipe for target 'cmTC_e3238/fast' failed
    gmake: *** [cmTC_e3238/fast] Error 2

**Additional context**
Is it really required to build the mpi library with gnu ? Why?

**Comment by AliceGabriel** [comment]
loading 
`module unload devEnv` 
on top of my hand load option may do the trick (to be validated tomorrow)

**Comment by krenzland** [comment]
I think the modules might be wrong. Can you try with the following:
```
gcc/8
cmake/3.14.4
python/3.6_intel
libszip/2.1.1
parmetis/4.0.3-intel-impi-i64-r64
metis/5.1.0-intel-i64-r64
numactl/2.0.11
hdf5/1.8.20-intel-impi-frt-threadsafe
netcdf/4.6.1-intel-impi-hdf5v1.8-parallel
intel/19.0
mkl/2019
mpi.intel/2019
devEnv/Intel/2019
```
(some lrz/debugging modules omitted)

Maybe the modules in the documentation aren't up-to-date. My setup uses intel compiler. With these modules, compilation works (just tested it).

**Comment by Thomas-Ulrich** [comment]
If I do not set any module in my ~/.bashrc, the following modules are 
loaded:
1) admin/1.0   2) tempdir/1.0   3) spack/release/19.2   4) intel/19.0   
5) mkl/2019   6) mpi.intel/2019   7) itac/2019   8) advisor_xe/2019   9) 
amplifier_xe/2019  10) inspector_xe/2019  11) devEnv/Intel/2019  12) lrz/1.0

This is not consistent with what you (Alice) wrote.
(e.g. mpi.intel/2019_gcc)

**Comment by AnikoWirp** [comment]
I had a problem with cmake before. 
Including module load spack/master to the bashrc fixed the problem.

**Comment by krenzland** [comment]
I would not recommend that - the spack/release/19.2 module is loaded by default and should be supported by LRZ. Not sure what happens if you use spack/master?

**Comment by Thomas-Ulrich** [comment]
I tested the workflow described in the readthedocs. It works.
If for you it does not work, it means you are doing something wrong.
I think the problem can be that you did not source the bashrc file after modifying it.

**Comment by AliceGabriel** [comment]
This should not be closed. I would like to try Lukas modules and update the
documentation. I dont see any sense in using gnu.

**Comment by AliceGabriel** [comment]
Also the current documentation did not work in my case and Aniko's case. I
just need the time to test it :)

**Comment by uphoffc** [comment]
The doc should state that you should have loaded devEnv/Intel for the instructions to work.

I'd also change
$ export FC=mpiifort
$ export CXX=mpiicpc
$ export CC=mpiicc

to 

$ export FC=mpif90
$ export CXX=mpiCC
$ export CC=mpicc

**Comment by Thomas-Ulrich** [comment]
I closed the issue just out of wickedness :-)
devEnv/Intel is loaded by default on supermuc.
Maybe we should add something like:
`we assume that no modules are loaded except for the default modules of supermuc`

**Comment by krenzland** [comment]
Do you have to load devEnv/intel? I certainly do not load that (but I load intel/19)

CMake doesnt rely on the MPI compiler wrappers, so in principle, you can skip CC/CXX/FC. (not recommended as untested on ng!)

Why do you want to change the FC/CXX/CC? I'm using CC=mpiicc CXX=mpiicpc FC=mpiifort? What exactly is the difference?

**Comment by AliceGabriel** [comment]
The problem with defaults and bashrc's assumptions is that users may have
more codes they compile on SuperMuc-NG - I dont want to have these modules
in my bashrc, eg.
The documentation should simply state the modules required to be loaded.

**Comment by uphoffc** [comment]
> Why do you want to change the FC/CXX/CC? I'm using CC=mpiicc CXX=mpiicpc FC=mpiifort? What exactly is the difference?

mpicc/CC/f90 respect the current devEnv. Therefore, the instructions might work even when devEnv/GCC is loaded.

Or to put in other words: If you put export CC=mpicc, etc., in your .bashrc then you can still compile your stuff when you change the devEnv

**Comment by krenzland** [comment]
Ah, I see. Didn't know that. Is this whole devEnv stuff new?

Regarding the modules, we should clearly state that we provide support if and only if the loaded modules are exactly the ones that we have. However they are loaded.

**Comment by uphoffc** [comment]
Maybe, yes. But mpicc and mpiCC/mpicxx are general wrappers which are often available and are configured to work with the current "dev env". (Cray has a similar system, e.g.) Thus, I nowadays prefer the general wrappers instead of the intel-compiler-specific wrappers.

Why not test for GCC as well? Could even work with the same modules.

**Comment by krenzland** [comment]
You're right, works also for devEnv/GCC/8-IntelMPI (otherwise same modules).
So better to switch to the general wrappers.

**Comment by krenzland** [comment]
@AliceGabriel Did this solve your issue or do you need further support?

**Comment by Thomas-Ulrich** [comment]
> The doc should state that you should have loaded devEnv/Intel for the instructions to work.
> 
> I'd also change
> $ export FC=mpiifort
> $ export CXX=mpiicpc
> $ export CC=mpiicc
> 
> to
> 
> $ export FC=mpif90
> $ export CXX=mpiCC
> $ export CC=mpicc

I can confirm that this does the trick for compiling with gcc.
I will update the documentation.

**Comment by jbiemiller** [comment]
I followed the updated documentation and the modules and instructions listed there now seem to have worked fine.

Only minor suggestion is in the pspamm installation instructions (https://seissol.readthedocs.io/en/latest/compilation.html#installing-pspamm): for new SuperMucNG users with few established directories, make sure to 'mkdir $HOME/bin' before doing 'ln -s $(pwd)/PSpaMM/pspamm.py $HOME/bin'

**Comment by sebwolf-de** [comment]
Seems to be fixed.
