### ISSUE TITLE
Generated kernel version of SeisSol cannot be debugged, as debug-mode fails to run for wave-prop

### ISSUE THREAD

**Issue by alheinecke** [SeisSol/SeisSol#3]
when running Intel-toolchain compiled binaries of SeisSol, Fortran runtime checks fail in the time marching loop:

forrtl: severe (408): fort: (7): Attempt to use pointer SLIP when it is not associated with a target

Image              PC                Routine            Line        Source             
SeisSol_debug_gen  00000000013D1EA0  Unknown               Unknown  Unknown
SeisSol_debug_gen  00000000011CA09D  inioutput_seissol         185  inioutput_seissol.f90
SeisSol_debug_gen  00000000004735AF  fortran_main              212  seissolxx.f90
SeisSol_debug_gen  0000000000488901  main                       55  main.cpp
libc.so.6          00002AB06FBCBAF5  Unknown               Unknown  Unknown
SeisSol_debug_gen  0000000000470819  Unknown               Unknown  Unknown

for wave propagation problem as dynamic rupture data structures do not exist. Probably this call (in inioutput_seissol.f90) needs to be guarded by a dynamic rupture check?!

#ifdef GENERATEDKERNELS
    call c_interoperability_initializeIO(           &
        i_mu        = disc%DynRup%mu,        &
        i_slipRate1 = disc%DynRup%slipRate1, &
        i_slipRate2 = disc%DynRup%slipRate2, &
        i_slip     = disc%DynRup%slip,      &
        i_slip1     = disc%DynRup%slip1,    &
        i_slip2     = disc%DynRup%slip2,    &
        i_state     = disc%DynRup%stateVar,  &
        i_strength  = disc%DynRup%strength,  &
        i_numSides  = mesh%fault%nSide,      &
        i_numBndGP  = disc%galerkin%nBndGP   )
#else

**Comment by alheinecke** [comment]
it fails also when running tpv12, which is actually a dynamic rupture scenario

**Comment by alheinecke** [comment]
GNU is affected as well:
At line 189 of file src/ResultWriter/inioutput_seissol.f90
Fortran runtime error: Pointer actual argument 'disc' is not associated

**Comment by rettenbs** [comment]
Can you please check commit c7d6715ed95c70139a14ac75965bf0c6f65569a4. It solved the problem for me (Intel and GCC).

**Comment by alheinecke** [comment]
great! Yes, this fixes the problem on my end as well for both tool chains.
