### ISSUE TITLE
ear related error on SuperMUC-NG

### ISSUE THREAD

**Issue by git-taufiq** [SeisSol/SeisSol#324]
**Describe the bug**
I got an error while scaling tests with 2000 nodes (large job partition). I would like to compare it to the results with 500 (general partition job) and 1000 nodes (large job partition) that already finished.
The job with 2000 nodes gave me error messages related to the ear below:
ERROR: eards: writting req_service in ear_daemon_client_connect (Invalid argument)
ERROR: eards: writting req_service in ear_daemon_client_connect (Invalid argument)
ERROR: eards: writting req_service in ear_daemon_client_connect (Invalid argument)
ERROR: eards: writting req_service in ear_daemon_client_connect (Invalid argument)
Above error messages are the only messages written on error log.

**Expected behavior**
I would like to have the job with 2000 nodes result without ear problem to compare with lower nodes results.

**To Reproduce**
I used SeisSol Commits Mar 25, 2021. SeisSol compiled following https://seissol.readthedocs.io/en/latest/compilation.html 

job file:
#!/bin/bash

#SBATCH -J R2000
#SBATCH --output=log-R2000_mesh120M.o%j
#SBATCH --error=log-R2000_mesh120M.e%j
#SBATCH --workdir=./
#SBATCH --mail-type=ALL
#SBATCH --mail-user=taufiqurrahman@outlook.de
#SBATCH --time=00:10:00
#SBATCH --no-requeue
#SBATCH --export=NONE
#SBATCH --account=pr63qo
#SBATCH --partition=large
#SBATCH --nodes=2000
#SBATCH --ntasks-per-node=1

export MP_SINGLE_THREAD=no
unset KMP_AFFINITY
export OMP_NUM_THREADS=94
export OMP_PLACES="cores(47)"

export XDMFWRITER_ALIGNMENT=8388608
export XDMFWRITER_BLOCK_SIZE=8388608
export SC_CHECKPOINT_ALIGNMENT=8388608
export SEISSOL_CHECKPOINT_ALIGNMENT=8388608
export SEISSOL_CHECKPOINT_DIRECT=1
export ASYNC_MODE=THREAD
export ASYNC_BUFFER_ALIGNMENT=8388608
export SEISSOL_ASAGI_MPI_MODE=OFF
source /etc/profile.d/modules.sh

ulimit -Ss unlimited
echo $SLURM_NTASKS
srun --export=ALL SeisSol_Release_dskx_6_elastic_plasticity parameters_mesh120M.par

**Comment by git-taufiq** [comment]
@krenzland and @uphoffc suggested to add --ear=of in the job file. I tried it but the initialization was very slow. It was still initializing step when the job got killed due to time limit (10 minutes).

**Comment by Thomas-Ulrich** [comment]
maybe you need more that 10min to initialize the mesh?

**Comment by git-taufiq** [comment]
Rank:        0 | Info    | <--------------------------------------------------------->
Rank:        0 | Info    | <     Start inioutput_SeisSol ...                         >
Rank:        0 | Info    | <--------------------------------------------------------->
16:48:48, Info:  Initializing free surface integrator.
16:48:48, Info:  Initializing free surface integrator. Done.
16:48:48, Info:  Wave field writer thread affinity: "----------|----------|----------|----------|-------7--|----------|----------|----------|----------|-----5"
16:48:48, Info:  Initializing XDMF wave field output.
16:48:48, Info:  Refinement Strategy is "Divide by 4"
16:48:48, Info:  Refinement class initialized
16:48:48, Info:  VariableSubsampler initialized
16:48:48, Info:  Initialize low order output
16:57:12, Info:  High order output initialized

Above is the output log for the test with --ear=off. It was not caused by mesh initialization, but high order output initialization process or after.

**Comment by uphoffc** [comment]
How many refinement levels do you use?

**Comment by git-taufiq** [comment]
I set refinement to 1, should I change to 0?
but the test with 1000nodes worked well. I asked about this problem at the LRZ service desk, maybe they have some explanation.

**Comment by AliceGabriel** [comment]
I would like to revoke this issue, since the results are important for a MSc thesis and upcoming collaboration. Taufiq said that he heard back from LRZ yesterday (maybe you can include here what they write). To me it seems very weird that only Taufiq's setup seems to be not initialising correctly at these scales.

**Comment by git-taufiq** [comment]
This is what they said:
Can you try the following: module switch devEnv/Intel/2020
Compile and run your batch job.

I compiled it already and test queued with 1500nodes and 2000 nodes.

**Comment by git-taufiq** [comment]
using 'module switch devEnv/Intel/2020' fixed this ear issue.
