### ISSUE TITLE
an error in SeisSol compilation on SupermucNG

### ISSUE THREAD

**Issue by daisy20170101** [SeisSol/SeisSol#358]
I compiled Seissol with the new modules but got an error:

[ 98%] Building CXX object CMakeFiles/SeisSol-bin.dir/src/Equations/elastic/Kernels/Time.cpp.o
[100%] Linking CXX executable SeisSol_Release_dskx_4_elastic
ld: CMakeFiles/SeisSol-bin.dir/src/Geometry/PUMLReader.cpp.o: in function `seissol::PUMLReader::partition(PUML::PUML<(PUML::TopoType)0>&, seissol::initializers::time_stepping::LtsWeights*, double, char const*, bool, char const*)':
PUMLReader.cpp:(.text+0x50a2): undefined reference to `ParMETIS_V3_PartMeshKway'
ld: PUMLReader.cpp:(.text+0x5e11): undefined reference to `ParMETIS_V3_PartMeshKway'
ld: CMakeFiles/SeisSol-bin.dir/src/Geometry/PUMLReader.cpp.o: in function `seissol::PUMLReader::PUMLReader(char const*, char const*, seissol::initializers::time_stepping::LtsWeights*, double, bool)':
PUMLReader.cpp:(.text+0x6e67): undefined reference to `ParMETIS_V3_PartMeshKway'
ld: CMakeFiles/SeisSol-bin.dir/src/Geometry/PUMLReader.cpp.o: in function `seissol::PUMLReader::PUMLReader(char const*, char const*, seissol::initializers::time_stepping::LtsWeights*, double, bool)':
PUMLReader.cpp:(.text+0x8257): undefined reference to `ParMETIS_V3_PartMeshKway'
ld: CMakeFiles/SeisSol-bin.dir/src/Geometry/PUMLReader.cpp.o: in function `PUML::PartitionMetis<(PUML::TopoType)0>::partition(int*, int const*, int, double*, double)':
PUMLReader.cpp:(.text._ZN4PUML14PartitionMetisILNS_8TopoTypeE0EE9partitionEPiPKiiPdd[_ZN4PUML14PartitionMetisILNS_8TopoTypeE0EE9partitionEPiPKiiPdd]+0x681): undefined reference to `ParMETIS_V3_PartMeshKway'
make[3]: *** [CMakeFiles/SeisSol-bin.dir/build.make:244: SeisSol_Release_dskx_4_elastic] Error 1
make[2]: *** [CMakeFiles/Makefile2:166: CMakeFiles/SeisSol-bin.dir/all] Error 2
make[1]: *** [CMakeFiles/Makefile2:173: CMakeFiles/SeisSol-bin.dir/rule] Error 2
make: *** [Makefile:157: SeisSol-bin] Error 2

I already updated to new module loaded:
Currently Loaded Modulefiles:
 1) admin/1.0      5) intel/19.0.5           9) libszip/2.1.1     13) slurm_setup/1.0                            17) numactl/2.0.12-intel19  
 2) tempdir/1.0    6) intel-mkl/2019        10) gcc/9.3.0         14) parmetis/4.0.3-intel19-impi-i64-r64        
 3) lrz/1.0        7) intel-mpi/2019-intel  11) cmake/3.16.5      15) metis/5.1.0-intel19-i64-r64                
 4) spack/21.1.1   8) lrztools/2.0          12) python/3.6_intel  16) netcdf-hdf5-all/4.6_hdf5-1.8-intel19-impi  

`ParMETIS_V3_PartMeshKway' is defined in $PARMETIS_BASE/include/parmetis.h, whose directory is in CPATH already. But I don't know why it cannot find it. What did I miss?

Thanks!

**Comment by daisy20170101** [comment]
/dss/dsshome1/lrz/sys/spack/release/21.1.1/opt/x86_64/intel-mpi/2019.8.254-gcc-vyzek4m/compilers_and_libraries_2020.2.254/linux/mpi/intel64/bin/mpiicpc   -std=c++11 -qopenmp -O3 -DNDEBUG   -qopenmp CMakeFiles/SeisSol-bin.dir/src/main.cpp.o CMakeFiles/SeisSol-bin.dir/src/Checkpoint/h5/Wavefield.cpp.o CMakeFiles/SeisSol-bin.dir/src/Checkpoint/h5/Fault.cpp.o CMakeFiles/SeisSol-bin.dir/src/Geometry/PUMLReader.cpp.o CMakeFiles/SeisSol-bin.dir/src/Initializer/time_stepping/LtsWeights.cpp.o CMakeFiles/SeisSol-bin.dir/src/SourceTerm/NRFReader.cpp.o CMakeFiles/SeisSol-bin.dir/src/Reader/AsagiModule.cpp.o CMakeFiles/SeisSol-bin.dir/src/Equations/elastic/Kernels/DirichletBoundary.cpp.o CMakeFiles/SeisSol-bin.dir/src/Equations/elastic/Kernels/Local.cpp.o CMakeFiles/SeisSol-bin.dir/src/Equations/elastic/Kernels/Neighbor.cpp.o CMakeFiles/SeisSol-bin.dir/src/Equations/elastic/Kernels/Time.cpp.o  -o SeisSol_Release_dhsw_4_elastic  -Wl,-rpath,/dss/dsshome1/lrz/sys/spack/release/21.1.1/opt/skylake_avx512/hdf5/1.8.22-intel-ko2qcoz/lib libSeisSol-lib.a ../build_cmake/yaml-cpp-install/lib/libyaml-cpp.a ImpalaJIT-install/lib/libimpalajit.a /dss/dsshome1/lrz/sys/spack/release/21.1.1/opt/skylake_avx512/hdf5/1.8.22-intel-ko2qcoz/lib/libhdf5_hl.so /dss/dsshome1/lrz/sys/spack/release/21.1.1/opt/skylake_avx512/hdf5/1.8.22-intel-ko2qcoz/lib/libhdf5.so -lpthread -lsz /usr/lib64/libz.so /usr/lib64/libdl.so -lm -L/dss/dsshome1/02/di52lak2/myLib/ASAGI2/build/lib -L/dss/dsshome1/lrz/sys/spack/release/21.1.1/opt/skylake_avx512/numactl/2.0.12-intel-oaf54jj -L/dss/dsshome1/lrz/sys/spack/release/21.1.1/opt/skylake_avx512/netcdf-c/4.6.3-intel-romsvd7/lib -lasagi -lnuma -lnetcdf -lpnetcdf -lhdf5_hl -lhdf5 -lm -lsz -lz -lifport -lifcoremt

parmetis/metis is not linked here.  I addedd  -DMETIS_LIBRARY=$METIS_BASE/lib -DPARMETIS_LIBRARY=$PARMETIS_BASE/lib tags in cmake, is that correct?

**Comment by sebwolf-de** [comment]
Hi, these are partly still the old modules.
Normally you would not need to add these tags to cmake. 
What happens if you execute 
```
mkdir build-after-update && cd build-after-update
CC=mpicc CXX=mpiCC FC=mpif90  cmake -DCOMMTHREAD=ON -DNUMA_AWARE_PINNING=ON -DASAGI=ON -DCMAKE_BUILD_TYPE=Release -DHOST_ARCH=skx -DPRECISION=single -DORDER=4 -DGEMM_TOOLS_LIST=LIBXSMM,PSpaMM -DPSpaMM_PROGRAM=~/bin/pspamm.py ..
make -j 48
```
?

**Comment by daisy20170101** [comment]
I created a new build folder and used this new configure but still the same issue. I manually added -lparmetis to link.txt and now it is fixed. 

PS: If I didn't tag **-DPARMETIS_LIBRARY=$PARMETIS_BASE/lib**,  I will have the following error:
CMake Error at /dss/dsshome1/lrz/sys/spack/release/21.1.1/opt/x86_64/cmake/3.16.5-gcc-cviwur4/share/cmake-3.16/Modules/FindPackageHandleStandardArgs.cmake:146 (message):
  Could NOT find ParMETIS (missing: PARMETIS_LIBRARY PARMETIS_TEST_RUNS)
  (found version "4.0")
Call Stack (most recent call first):
  /dss/dsshome1/lrz/sys/spack/release/21.1.1/opt/x86_64/cmake/3.16.5-gcc-cviwur4/share/cmake-3.16/Modules/FindPackageHandleStandardArgs.cmake:393 (_FPHSA_FAILURE_MESSAGE)
  cmake/FindParMETIS.cmake:120 (find_package_handle_standard_args)
  CMakeLists.txt:222 (find_package)

**Comment by sebwolf-de** [comment]
`(missing: PARMETIS_LIBRARY PARMETIS_TEST_RUNS) (found version "4.0")` indicates, that cmake actually finds parmetis, but the test runs fail.
Can you post the output of `CMakeFiles/CMakeError.log`

**Comment by sebwolf-de** [comment]
Hi, there hasn't been an answer in a week. I suppose you've solved the problem and I can close the issue?

**Comment by krenzland** [comment]
The instructions also work for me, so I believe they are correct.
