### ISSUE TITLE
filesystem error when compiling SeisSol on Shaheen II

### ISSUE THREAD

**Issue by palgunadi1993** [SeisSol/SeisSol#377]
**Describe the bug**
I got error that described cmake does not support for C++ filesystem.

**Expected behavior**
No filesystem error

**To Reproduce**
1. Which version do you use? master branch, commit bde3b8fe395ef5b92c369a109d0cfde6e99503ce
2. Intel 19.0.5
3. Shaheen II, loaded module: PrgEnv-intel, cdt, python/3.8.0-cdl
4. cmake version: 3.16.2

**Screenshots/Console output**
![filesystem](https://user-images.githubusercontent.com/35545825/129866656-101e3cca-41dd-474e-abf3-8e7ed3041ddb.png)

**CMakeOutput and CMakeList**
[CMakeCache.txt](https://github.com/SeisSol/SeisSol/files/7005849/CMakeCache.txt)
[CMakeOutput.log](https://github.com/SeisSol/SeisSol/files/7005851/CMakeOutput.log)

**Comment by ravil-mobile** [comment]
Hi,

Can you try to load any gcc (version 8.3.0 or higher) compiler and then load Intel compiler?

**Comment by palgunadi1993** [comment]
Hi,
The problem is solved by loading the gcc version > 8.3.0 (I used gcc/9.3.0).

Thank you for your help.

Cheers,
Kadek

**Comment by palgunadi1993** [comment]
Hi,

When updating SeisSol and try to recompile it with the upgraded OS on Shaheen, I got the same problem that the compiler could not recognize filesystem. In the previous Shaheen's OS version, this problem is solved by loading gcc version > 8.3.0. However, it doesn't the case now. 
Here is the module I load on Shaheen:
Currently Loaded Modulefiles:
  1) modules/3.2.11.4                                 15) ugni/6.0.14.0-7.0.3.1_3.13__gdac08a5.ari
  2) craype-network-aries                             16) pmi/5.0.17
  3) intel/2021.4.0                                   17) dmapp/7.1.1-7.0.3.1_2.26__g93a7e9f.ari
  4) craype/2.7.10                                    18) gni-headers/5.0.12.0-7.0.3.1_2.15__gd0d73fe.ari
  5) cray-mpich/7.7.18                                19) xpmem/2.2.27-7.0.3.1_2.10__gada73ac.ari
  6) slurm/slurm                                      20) job/2.2.4-7.0.3.1_2.21__g36b56f4.ari
  7) dws/3.0.36-7.0.3.1_2.28__g6985c90.ari            21) dvs/2.12_2.2.224-7.0.3.1_2.25__gc77db2af
  8) eproxy/2.0.24-7.0.3.1_2.18__g8e04b33.ari         22) alps/6.6.67-7.0.3.1_2.25__gb91cd181.ari
  9) craype-haswell                                   23) rca/2.2.20-7.0.3.1_2.27__g8e3fb5b.ari
 10) xalt/1.1.2                                       24) atp/3.14.5
 11) darshan/3.3.1                                    25) perftools-base/21.09.0
 12) ksl/ksl                                          26) PrgEnv-intel/6.0.10
 13) cray-libsci/20.09.1                              27) gcc/11.2.0
 14) udreg/2.3.2-7.0.3.1_2.19__g5f0d670.ari           28) cce/12.0.3

Error:
-- Performing Test _FILESYSTEM_NATIVE
-- Performing Test _FILESYSTEM_NATIVE - Failed
-- Performing Test _FILESYSTEM_STDCPPFS
-- Performing Test _FILESYSTEM_STDCPPFS - Failed
-- Performing Test _FILESYSTEM_CPPFS_RESULT
-- Performing Test _FILESYSTEM_CPPFS_RESULT - Failed
CMake Error at cmake/FindFILESYSTEM.cmake:52 (message):
  C++ compiler does not support std::filesystem
Call Stack (most recent call first):
  CMakeLists.txt:335 (find_package)


Do you have any idea?

Thank you!

Regards,
Kadek

**Comment by palgunadi1993** [comment]
The issue is solved by changing to intel compiler intel/19.0.5.281.

Thank you!
