### ISSUE TITLE
Code Smell?

### ISSUE THREAD

**Issue by ravil-mobile** [SeisSol/SeisSol#387]
This seems like a bunch redundant statements. I am working on this part of the code. Shall I delete it? As for me there is not effect out of it. 

https://github.com/SeisSol/SeisSol/blob/a638918acc1299065a0a19215f44ad66008f3adc/src/Initializer/time_stepping/LtsWeights.cpp#L212-L213

**Comment by Thomas-Ulrich** [comment]
That's the associated commit:
https://github.com/SeisSol/SeisSol/commit/08365b4f21bfa36e5f8fcc2bef1288eb60964af1
(if you did not think of git blame).

**Comment by ravil-mobile** [comment]
Hi @Thomas-Ulrich but there was not `PUML::Upward::cells(mesh, faces[faceids[face]], cellIds);` in `computeWeights` in `08365b4`.  
According to git blame, @krenzland added it.

**Comment by uphoffc** [comment]
yes you can delete these two lines

**Comment by ravil-mobile** [comment]
Thanks
