### ISSUE TITLE
SeisSol modified for allowing larger number of fault tags crashes during initializing

### ISSUE THREAD

**Issue by palgunadi1993** [SeisSol/SeisSol#392]
This is not really a bug or a general enhancement for SeisSol. I would like to ask for help to review changes I made for SeisSol to be able to read 64bits mesh. 

PUMGen change to create mesh is compared here:
https://github.com/SeisSol/PUMGen/compare/master...palgunadi1993:PUMGenEdited?expand=1

PUML submodule:
https://github.com/TUM-I5/PUML2/compare/master...palgunadi1993:PUML_64?expand=1

SeisSol:
https://github.com/SeisSol/SeisSol/compare/master...palgunadi1993:SeisSolPUMGen?expand=1

I run a test case using boundary conditions 3 and 600 for 2 planar fault planes. It seems that I still failed to read the mesh using PUML reader. The final output I got as follows:
```
Sun Sep 26 14:57:18, Info:  Node weights: mean = 1.42599  std = 0.157594  min = 1.19914  median = 1.4324  max = 1.64002
Sun Sep 26 14:57:18, Info:  Reading PUML mesh mesh/testPohang
Sun Sep 26 14:57:18, Info:  Found 293642 cells
Sun Sep 26 14:57:18, Info:  Found 50935 vertices
Sun Sep 26 14:57:18, Info:  Computing LTS weights.
Sun Sep 26 14:57:19, Info:  Computing LTS weights. Done.  (2193 reductions.)
Sun Sep 26 14:57:20, Info:  Reading mesh. Done.
Sun Sep 26 14:57:20, Info:  Extracting fault information
Sun Sep 26 14:57:20, Info:  Mesh initialized in: 2.57169 (min: 2.48391, max: 2.67801)
```
The error log is:
```
terminate called after throwing an instance of 'std::runtime_error'
  what():  Korea_nucleation_stress_dip.yaml@24: Could not find model for point [ -339.115 -1043.47 -4184.87 ] in group 0.
terminate called after throwing an instance of 'std::runtime_error'
  what():  Korea_nucleation_stress_dip.yaml@24: Could not find model for point [ -51.7471 139.562 -4675.2 ] in group 0.
terminate called after throwing an instance of 'std::runtime_error'
  what():  Korea_nucleation_stress_dip.yaml@24: Could not find model for point [ 1106.1 1721.72 -3822.6 ] in group 0.
```

Although there is no group 0 in the mesh, SeisSol is still read as group 0 which very likely failed to read the right group number. If I read the mesh using Paraview, it shows the right group number and fault tag. So I don't think the problem is coming from the mesh generated by PUMGen. 

I'm sure that I messed up somewhere but probably I overlook it. Therefore, I would like to ask for a little help to review my changes.

Thank you for all your help.

Best regards,
Kadek

**Comment by Thomas-Ulrich** [comment]
```query.group(cell) = static_cast<int64_t>(material[cell]);```
Should be 
```query.group(cell) = static_cast<int>(material[cell]);```

**Comment by uphoffc** [comment]
> `query.group(cell) = static_cast<int64_t>(material[cell]);`
> Should be
> `query.group(cell) = static_cast<int>(material[cell]);`

No: https://github.com/SeisSol/PUMGen/compare/master...palgunadi1993:PUMGenEdited?expand=1#diff-47e6ce4bc230c437836f73d59b47fe05ad85a42f78f03e7e88dc38a5a04779f6L335

**Comment by Thomas-Ulrich** [comment]
But what about this one:
https://github.com/SeisSol/easi/blob/master/include/easi/Query.h#L46

**Comment by palgunadi1993** [comment]
I use int64 because in PUMLReader.cpp the group tag is read by this function: https://github.com/TUM-I5/PUML2/blob/bbdfa200fb65bec8118409ef077239e22ffbc41d/PUML.h#L283 which forces the same data type to boundary

**Comment by palgunadi1993** [comment]
Hi,

I'm still confused, I created the mesh using the PUMGenEdited version and it loaded successfully in Paraview. Paraview identified the group within data range [1,1]. Does paraview read the group correctly or did I still make a mistake in PUMLReader function?

I tried Thomas suggestions (change material to int type) and use mesh with group tag 32-type but still stuck in the same error.

**Comment by palgunadi1993** [comment]
Thank you for the correction and help Thomas!
