### ISSUE TITLE
simulation with TP is slow

### ISSUE THREAD

**Issue by daisy20170101** [SeisSol/SeisSol#398]
**Describe the bug**
Simulations with TP is much slower than without. I am wondering how it should be improved.

The parameters are the same except for some additional TP features.
without TP:
585.673 GFLOPS on rank 0
with TP:
 204.139 GFLOPS on rank 0 

What's more, when running on 16 nodes in Test queue, it takes 7 mins and 30 mins to finish a 2.5-sec simulation, respectively. 

**Expected behavior**
Could it be improved somehow?

**To Reproduce**
1. Which version do you use? Provide branch and commit id.
Master branch
Version: 201807_Kaikoura-1130-g73d59a4d (modified)
a638918acc1299065a0a19215f44ad66008f3adc

2. Which build settings do you use? Which compiler version do you use? 
cmake
elastic, skx, hdf5=ON, nectcdf=ON, metis=ON (what else should I provide?)
3. On which machine does your problem occur? If on a cluster: Which modules are loaded?
NG
1) admin/1.0      6) intel-mkl/2019          11) gcc/9.3.0                            16) metis/5.1.0-intel19-i64-r64                
 2) tempdir/1.0    7) intel-mpi/2019-intel    12) cmake/3.14.5                         17) netcdf-hdf5-all/4.6_hdf5-1.8-intel19-impi  
 3) lrz/1.0        8) lrztools/2.0            13) python/3.6_intel                     
 4) spack/21.1.1   9) numactl/2.0.12-intel19  14) slurm_setup/1.0                      
 5) intel/19.0.5  10) libszip/2.1.1           15) parmetis/4.0.3-intel19-impi-i64-r64 

4. Provide parameter/material files.
model directory: /hppfs/work/pr63qo/di52lak2/AlaskaTest

**Screenshots/Console output**
If you suspect a problem in the numerics/physics add a screenshot of your output.

If you encounter any errors/warnings/... during execution please provide the console output.

**Additional context**

**Comment by krenzland** [comment]
I'm not too familiar with TP, if the cost changes during runtime it will lead to load imbalance. Dynamic load balancing is not planned, would be a whole new PhD thesis.

> We have an AGU talk attempting to show SeisSol simulation with TP. It will be great to have TP optimized :-)

Well, good luck ;)
This would need to be done at the LMU group, I don't think any of us at TUM has much interest/time for TP currently. Maybe when we tackle the Fortran -> C++ conversion. Not sure what the timeline for that is though.

**Comment by sebwolf-de** [comment]
@Duo, can you check the branch dr/performance to see, whether your setup benefits from the Fortran -> C++ port?
