### ISSUE TITLE
Add instructions about include path in compilation guide

### ISSUE THREAD

**Issue by yzs981130** [SeisSol/SeisSol#40]
With current compilation guide, `icc` fails to find header files in `$HOME/include`. I suggest to add instructions of adding this directory to include path, like `export C_INCLUDE_PATH=$HOME/include:$C_INCLUDE_PATH` and `export CPLUS_INCLUDE_PATH=$HOME/include:$CPLUS_INCLUDE_PATH`.

**Comment by Thomas-Ulrich** [comment]
hi, which header in your $HOME/include icc fails to find? It might be related to your system and not to SeisSol?

**Comment by yzs981130** [comment]
It's `"hdf5.h"`.
I confirm that all instructions in the wiki were followed and parallel studio was installed by its official instruction `sh install.sh`.

**Comment by Thomas-Ulrich** [comment]
Hi, 
Now that I have read again the wiki, it seems that your suggestion could make sense. 
I ve then added the 2 proposed lines in the the wiki:
https://github.com/SeisSol/SeisSol/wiki/Compilation#a-inital-adjustments-to-bashrc
Thx for your feedback,
Thomas
