### ISSUE TITLE
SeisSol terminated with no update error

### ISSUE THREAD

**Issue by palgunadi1993** [SeisSol/SeisSol#406]
**Describe the bug**
SeisSol is terminated without showing an obvious error. The error log only shows it is terminated because there is no update.

**Expected behavior**
SeisSol will continue to run and update the output.

**To Reproduce**
1. Which version do you use? SeisSol patch with 64bit version (https://github.com/SeisSol/SeisSol/blob/master/Documentation/fault-tagging.rst); last master branch: 31340e34c28c776fec5534f5fc1c0388cfee699f
2. Which build settings do you use? Which compiler version do you use? 
![setting](https://user-images.githubusercontent.com/35545825/138235268-6be65ed2-b15b-4721-90fc-02643d1e83f7.png)
3. On which machine does your problem occur? If on a cluster: Which modules are loaded? Shaheen II
4. Provide parameter/material files.
Parameter file: 
[parameters.txt](https://github.com/SeisSol/SeisSol/files/7387128/parameters.txt)
Fault files:
[faultLPalgunadiEtAlMesh1.txt](https://github.com/SeisSol/SeisSol/files/7387134/faultLPalgunadiEtAlMesh1.txt)
[initial_stress.txt](https://github.com/SeisSol/SeisSol/files/7387135/initial_stress.txt)
[material.txt](https://github.com/SeisSol/SeisSol/files/7387136/material.txt)
[nucleation_stress.txt](https://github.com/SeisSol/SeisSol/files/7387137/nucleation_stress.txt)

**Screenshots/Console output**
![sc1output](https://user-images.githubusercontent.com/35545825/138236546-e3354df6-e866-4ab8-a957-ff20684bb2ee.png)

**Error Log**
![sc2errorOutput](https://user-images.githubusercontent.com/35545825/138236628-5c97cd64-3f03-4bea-9786-72e077f43840.png)

**Mesh Info**
1. Number of grid: 54mio
2. Number of dynamic rupture tags: 856

What would be the cause of this error?
Thank you.

Best regards,
Kadek

**Comment by Thomas-Ulrich** [comment]
Can we close the issue?
