### ISSUE TITLE
Number of data from off-fault receivers output is not consistent

### ISSUE THREAD

**Issue by aimanyongki** [SeisSol/SeisSol#42]
Hi, 

I ran simulation on easi branch with enabling ascii receivers output and set certain Pickpoint Sampling and EndTime (for Abort Criteria) in parameter file.
However, the resulted files don't have the same number of data, e.g. receiver 1 contains 8751 data but receiver 5 contains 8760 data.

Here is my setup and I also attached examples of the output. 
https://drive.google.com/drive/folders/1rbpSi1NxNQnvcdFejD8iewhfLLfJdnMv?usp=sharing

**Comment by Thomas-Ulrich** [comment]
I cannot reproduce the issue, probably fixed.
