### ISSUE TITLE
Incorrect results with Clang@11 compiler

### ISSUE THREAD

**Issue by ravil-mobile** [SeisSol/SeisSol#439]
**Describe the bug**
One can obtain incorrect numerical results when SeisSol compiled with clang, clang++ and GNU gfortran. 
All SeisSol dependencies were compiled with GNU compiler collection v9.3.0

**Expected behavior**
To obtain correct numerical results with clang 11 or 12

**To Reproduce**
Install clang from sources, compiler SeisSol with it and run TPV5

**Screenshots/Console output**
On the top: SeisSol compiled with GNU compiler collection (v9.3.0); bottom: clang@11 clang++@11 and GNU gfortran@9.3.0.
![gcc-vs-clang](https://user-images.githubusercontent.com/19637079/145555802-f8a5d4ae-4727-4b35-8734-5230f5944f51.png)

**Additional context**
Probably, it was caused by compiler flags or the fact that all SeisSol dependencies were compiled with gcc and linked to the code compiled to clang.

**Comment by krenzland** [comment]
Does the problem occur only for dynamic rupture simulations?

**Comment by ravil-mobile** [comment]
Yes. I ran `convergence_elastic` test with both clang@11 and clang@14 (dpcpp both on CPU and on GPU) and everything were ok.

**Comment by krenzland** [comment]
Ok, then I suspect that there is something strange going on. Does this also occur with -O0?

**Comment by ravil-mobile** [comment]
The same happen with `Debug` build. I've just installed llvm with `flang`. Let me try it out

**Comment by ravil-mobile** [comment]
Ok. flang doesn't quite work with `cmake`. I even tried cmake@3.21.4 and it couldn't configure SeisSol

**Comment by ravil-mobile** [comment]
Interestingly, if one uses clang@11 but runs SeisSol with GPUs then results are correct. When we run with GPUs then all wave propagation stuff is running on GPUs. Only dynamic rupture is handled by CPUs. I also tried to use Eigen backend for yateto with a pure CPU build but I still got incorrect results.

**Comment by ravil-mobile** [comment]
Hi, yet another update: The results are correct if SeisSol is compiled with clang and `OMP_NUM_THREADS` is set `1`. clang@11 provides `OpenMP@5`. I don't know whether OpenMP is buggy in clang or the 5th standard has some changes which are not addressed in SeisSol.

I only know about some differences and changes in the standard with respect to GPU offloading i.e., local variables defined outside of a `target` parallel region are `firstprivate` by default in OpenMP5. I don't know whether there were some changes for traditional CPU multi-threading.
