### ISSUE TITLE
Asagi: warning our of range

### ISSUE THREAD

**Issue by daisy20170101** [SeisSol/SeisSol#44]
Hi, 
I am using Asagi to input stress tensor. I got the warning:
   26 Wed Jul 18 11:43:44, Warn:  ASAGI: Coordinate in dimension 0  is out of range. Fixing.
   27 Wed Jul 18 11:43:44, Warn:  ASAGI: Coordinate in dimension 1  is out of range. Fixing.

It does not disturb SeisSol and the stress looks fine on the fault.
Is it because the range in Asagi is smaller than the model domain?

Thanks!

**Comment by swollherr** [comment]
Hi,

yes, that's the case.
You can find that by looking for the warning in the code directly:

https://github.com/TUM-I5/ASAGI/blob/8c0a3fa8451371c0266c7d560b2944585de7f4ae/grid/level/level.h#L362

All coordinates that are smaller than the coordinate of the first entry will get the value/index of the first entry. Similarly for the last entry.
