### ISSUE TITLE
Minimal HW set-up

### ISSUE THREAD

**Issue by fvella** [SeisSol/SeisSol#45]
Hi,

I am trying to run SeisSol in a small cluster / single multi-core node. 
I successfully compiled Seisol in hybrid mode with Intel compilers. 

You can easily reproduce my installation by using [Collective-Knowledge Framework](https://github.com/ctuning/ck) and  following the instruction [here](https://github.com/ctuning/ck-cluster18). 

To run Seissol
``` 
$ ck run program:seissol-netcdf
``` 
and selecting the default command.

In ```$ cd `ck find program:seissol-netcdf`/tmp/ ```
I have the following files:
```
003_topo30sec_wSplays_sim5_pumgenSM2.dtc1-v2-suma.20.nc  1003_topo30sec_wSplays_sim5_pumgenSM2_rec.dat  DGPATH  parameters.par
```
All of them are automatically downloded from [here](https://zenodo.org/record/439946/#.W09Zl9gzbVo) 

I would love to know how to set-up Seissol to run in a small cluster or single node multi-core system.

How can I determine the minumum number of MPI processes/number of OMP threads ? TBoMK this number depeds on the mesh size. 

Many thanks in advance

**Comment by uphoffc** [comment]
Hi,

sorry for the very late answer. You are only limited by the available memory, regarding the number of nodes. As a rule of thumb, you can use the following rule

#nodes >= 10 * E * B * Q * P / memoryPerNode,

where
E = number of elements in your mesh
B = number of basis functions = order*(order+1)*(order+2) / 6
Q = number of quantities (9 for elastic, 9 + 6*(number of mechanisms) for viscoelastic)
P = precision (8 = double, 4 = single)

You should use a single MPI rank per node. For best performance, pin the threads in a compact manner with a maximum of 2 threads per core and leave the last core free if you use a communication thread. Example settings:

# dual-socket Intel Xeon E5-2698 v3
export OMP_NUM_THREADS=62
export KMP_AFFINITY=compact,granularity=thread
# single-socket Intel Xeon Phi 7250
export OMP_NUM_THREADS=65
export KMP_AFFINITY=proclist=[2-66],explicit,granularity=thread

Regards,
Carsten
