### ISSUE TITLE
using standard rupture format

### ISSUE THREAD

**Issue by daisy20170101** [SeisSol/SeisSol#47]
Hi All,

Has anyone used SRF or NRF of source type before?
I am preparing the SCEC source rupture model with rconv.

rconv -i northbridge.srf -m "+proj=merc  +lat_ts=34 +lon_0=-118 +datum=WGS84 +units=m +axis=enu" -o northbridge.nrf -x  northbridge.xdmf 

or 

rconv -i northbridge.srf -m "+proj=utm  +zone=12  +datum=WGS84 +units=m +axis=enu" -o northbridge.nrf -x  northbridge.xdmf 

But I got a wired coordinates and 0.01 m slip patch length.
Attached here is the SRF downloaded from SCEC wiki.

1.0
PLANE 1
 -118.5150   34.3440    20    25    20.00    25.00
 122   40     5.00     0.00    18.75
POINTS 500
 -118.6049   34.3864    5.3214  122   40  1.00000e+10     7.4390  1.00000e-01
  90    18.67     16     0.00      0     0.00      0
  0.00000e+00  1.21778e+00  2.43557e+00  9.76408e-01  8.95040e-01  8.13673e-01
  7.32306e-01  6.50938e-01  5.69571e-01  4.88204e-01  4.06837e-01  3.25469e-01
  2.44102e-01  1.62735e-01  8.13673e-02  0.00000e+00
.....

I guess I missed some thing important here.

Thanks.

**Comment by AliceGabriel** [comment]
Hi Duo
Could you share the benchmark description? Quite some people used this
before - Carsten and thomas would be to ask specifically

**Comment by daisy20170101** [comment]
Hi Alice,

This is not a standard benchmark. Last time we discussed about adding kinematic source in SeisSol manual. This is what I want to test. I used the similar model as the usual finite-fault inversion results.

Refer to this: http://hypocenter.usc.edu/research/SRF/srf-v2.0_rev1.pdf <http://hypocenter.usc.edu/research/SRF/srf-v2.0_rev1.pdf>
This model is the 1994 north bridge earthquake in California.
http://hypocenter.usc.edu/research/SRF/nr6.70-s0000-h0000.txt <http://hypocenter.usc.edu/research/SRF/nr6.70-s0000-h0000.txt>

Duo


—————————————————
Dr. Duo Li
Department of Earth and Environmental Sciences
Geophysics
Ludwig-Maximilians-Universität München
Theresienstr. 41
80333 Munich 
Germany
liduoduo07@gmail.com

**Comment by AliceGabriel** [comment]
Hi Duo

Its great you chose the Northridge EQ since I am working on a dynamic
rupture model for this event since quite some time. I assume you have read
the wiki page on using kinematic sources in SRF format:
https://github.com/SeisSol/SeisSol/wiki/Standard-Rupture-Format

It seems as if we don't have an example input file online yet ... Would be
great to collect one from previous users and add it to the repo.

Alice

**Comment by daisy20170101** [comment]
We can use x- and y-translation feature to fix the reference point of the converted coordinates. For example, using Mercator projection like:
rconv -i input.srf -o output.nrf -m “+proj=merc +lon_0=central_longtitude +y_0=translation_along_y +x_0=translation_along_x +units=m +axis=enu” -x visualization.xdmf
