### ISSUE TITLE
checkpointing issues

### ISSUE THREAD

**Issue by Thomas-Ulrich** [SeisSol/SeisSol#48]
1) ~~checkpointing does not work with PUML meshes (the simulation always starts at t=0)~~
2) checkpointing does not work with RS friction (as the state variable is not checkpointed).
3)  ~~checkpointing does not work properly (even with a netcdf mesh) if the friction is initialised with ASAGI.~~
4) ~~checkpointing is not well documented in readthedoc (easy fix).~~
5) Checkpointing with attenuation is not working properly

**Comment by Thomas-Ulrich** [comment]
actually 3 is probably due to the fact that the 'smoothslip' variable is not checkpointed.

**Comment by Thomas-Ulrich** [comment]
1. Partitionning is now saved in a hdf5 file, which should allow checkpointing with PUML meshes (and to compare fault and wavefield outputs from 2 simulations). 
2. the state variable is actually checkpointed. Yet is seems there is still a problem with slip and RS.
4. documentation added

**Comment by Thomas-Ulrich** [comment]
Checkpointing with attenuation is not working properly. I got the following error when writing the first CP:
```
Sun Mar 24 19:51:41, Info:  Checkpoint: Waiting for last.
Sun Mar 24 19:51:41, Info:  Checkpoint: Writing at time 0.02.
Sun Mar 24 19:51:41, Info:  Checkpoint: Writing at time 0.02. Done.
Sun Mar 24 19:51:41, Info:  Checkpoint backend: Writing.
Sun Mar 24 19:51:41, Info:  198.333 GFLOPS on rank 0
Sun Mar 24 19:51:43, Error: Error in the MPI checkpoint module: Other I/O error , error stack:
ADIOI_NFS_WRITECONTIG(76): Other I/O error Bad address
```

**Comment by uphoffc** [comment]
partition -> @krenzland
attenuation -> @uphoffc  

Please try to post one issue per issue
