### ISSUE TITLE
Dr/cpp attenuation

### ISSUE THREAD

**Issue by ravil-mobile** [SeisSol/SeisSol#482]
Does it work with attenuation?

https://github.com/SeisSol/SeisSol/blob/a7448bec28bcb41edac30ccc2c7f9d5be628df79/src/DynamicRupture/FrictionLaws/BaseFrictionLaw.h#L157

**Comment by Thomas-Ulrich** [comment]
Probably yes, as 9 is also hardcoded in master branch:
https://github.com/SeisSol/SeisSol/blob/181fc85d5c405a8c44fe21869fe736ab1f0206d5/src/Solver/f_ctof_bind_interoperability.f90#L180

**Comment by krenzland** [comment]
Aren't the quantities separately stored for attenuation? At least they are treated separately in the time kernel...

**Comment by ravil-mobile** [comment]
It can be solved by:
```

template <typename Tensor, int Dim>
constexpr size_t dimSize() noexcept {
  return Tensor::Stop[Dim] - Tensor::Start[Dim];
}

template <typename Tensor>
constexpr size_t leadDim() noexcept {
  return Tensor::Stop[0] - Tensor::Start[0];
  return dimSize<Tensor, 0>();
}

/**
 * Number of gauss points padded to match the vector register length.
 */
static constexpr inline size_t numPaddedPoints = leadDim<init::QInterpolated>();
constexpr int numQuantities = misc::dimSize<init::QInterpolated, 1>();
```

What do you think?

**Comment by sebwolf-de** [comment]
I just tested commit 654dbb34 with tpv5 and a modified viscoelastic material. I did not make a proper comparison to the master, but the eyeball norm confirms that it is working ;-)
