### ISSUE TITLE
Marenostrum architecture and SeisSol

### ISSUE THREAD

**Issue by monterrubio-velasco** [SeisSol/SeisSol#50]
Hello, 
We are trying to install SeisSol as a module in the Marenostrum 4 but we saw that the target architecture for 'Skylake' is not available. Is a big problem to choose another? Or is possible to provide it?
Thank you 

Marisol

**Comment by uphoffc** [comment]
Hi Marisol,

please use the latest commit (ff3f642fd7b67cf05cbcb58b956608f3d2800c55) and compile with arch=dskx (or sskx for single precision). 

Best regards,
Carsten
