### ISSUE TITLE
vtable for WeightsModels not created

### ISSUE THREAD

**Issue by LukasvdWiel** [SeisSol/SeisSol#515]
**Describe the bug**
When compiling SeisSol, an undefined reference for the vtables is presented when linking SeisSol_Release_dhsw_6_elastic

libSeisSol-lib.a(MeshReaderFBinding.cpp.o): In function 

`seissol::initializers::time_stepping::getLtsWeightsImplementation(seissol::initializers::time_stepping::LtsWeightsTypes, seissol::initializers::time_stepping::LtsWeightsConfig const&)':

MeshReaderFBinding.cpp:(.text+0xbf0): undefined reference to `vtable for seissol::initializers::time_stepping::ExponentialBalancedWeights'

MeshReaderFBinding.cpp:(.text+0xd00): undefined reference to `vtable for seissol::initializers::time_stepping::ExponentialWeights'

MeshReaderFBinding.cpp:(.text+0xe10): undefined reference to `vtable for seissol::initializers::time_stepping::EncodedBalancedWeights'

collect2: error: ld returned 1 exit status

make[2]: *** [SeisSol_Release_dhsw_6_elastic] Error 1

make[1]: *** [CMakeFiles/SeisSol-bin.dir/all] Error 2

make: *** [all] Error 2

**Expected behavior**
Would expect SeisSol to compile without errors

**To Reproduce**
Install GCC 10.2.0.
Our installation has compiled countless programs already and we are confident that the compiler functions properly.
Compile SeisSol gives the errors almost at end, when linking SeisSol_Release_dhsw_6_elastic

**Additional context**
A well known programming mistake causing this error is apparently including the destructors in the header file in stead of in the C++ file. So I moved the destructors from header file to cpp file, but that did not change the compiling process.

**Comment by sebwolf-de** [comment]
Hi Lukas,
unfortunately I can't reproduce the bug with gcc 10.2.0 on SuperMUC-NG, and I can compile/link without problems.
Did you also try to mark the destructors virtual? This should make the difference. Try the branch `sebastian/fix-515`.

**Comment by sebwolf-de** [comment]
Great to hear that the fix works! I'll open a PR to master.
I don't completely understand your remark about metis and netcdf. The variable is set here: https://github.com/SeisSol/SeisSol/blob/928dd006c0b900aef5ada468c67e79f8fab76a57/cmake/FindMETIS.cmake#L89

**Comment by LukasvdWiel** [comment]
Oh! Apologies. I was not thinking clearly, mixing up METIS and NetCDF in my mind.
I had a warning about IDXTYPEWIDTH not being equal to 64, which is the assert in SeisSol/cmake/FindMETIS.cmake line 71, but I fixed that in METIS. It was not a SeisSol issue.
Thank you again for all the help!

**Comment by sebwolf-de** [comment]
@LukasvdWiel I haven't heard from you in a while. I guess the issue is solved now. If not, don't hesitate to contact us again :-)
