### ISSUE TITLE
False #include labels

### ISSUE THREAD

**Issue by dimsavv** [SeisSol/SeisSol#534]
While trying to compile the whole project in **Code::Blocks**, I notice some _#include_ labels in header files which do not exist in the project. For example, in the _src/Equations/elastic/Model/datastructures.hpp_ file I see an _#include <generated_code/kernel.h>_, and the _generate_code_ subfolder of the project in here only has **Python** (.py) files. As a result, compiling the project from the file _src/main.cpp_ leads to the following console output: _fatal error: generated_code/kernel.h: No such file or directory_ I also have issues with a folder named _Eigen_ which I cannot find inside the project either. Could someone please give me a hint?

![bug](https://user-images.githubusercontent.com/96953432/163438923-5fad2443-13a9-434a-8301-5f330371a9b3.PNG)

**Comment by sebwolf-de** [comment]
Hi,
1. when you build SeisSol with cmake, one build step is to generate the required files by calling the python scripts.
2. Eigen is a dependency, which should be installed on the system level: https://seissol.readthedocs.io/en/latest/compilation.html#installing-eigen3
3. It seems to me, that you are trying to compile SeisSol on Windows, which is not supported by us. Use linux, in particular Ubuntu 20.04. (e.g. https://github.com/SeisSol/SeisSol/blob/master/azure-pipelines-seissol-template.yml)

**Comment by krenzland** [comment]
> It seems to me, that you are trying to compile SeisSol on Windows, which is not supported by us. Use linux, in particular Ubuntu 20.04. (e.g. https://github.com/SeisSol/SeisSol/blob/master/azure-pipelines-seissol-template.yml)

You can build in the Windows Subsystem for Linux (WSL). Builds on Windows might work for some configurations but is not tested. In general, we assume that the system is Linux, because we use some libraries that only exist of such systems (e.g. libnuma)
