### ISSUE TITLE
Weird stripes in fault variables using TP modeling

### ISSUE THREAD

**Issue by daisy20170101** [SeisSol/SeisSol#544]
**Describe the bug**
There are wired stripes in Tmp and other fault variables, except for ASl, when using TP modeling. The stripes have larger sizes than triangles so it doesn't looks like a result of bad meshing.

Figures showing Tmp and ASl, respectively,
![tmp-tp20l](https://user-images.githubusercontent.com/33549997/166884613-e59482a5-9bca-4f2b-83d6-8ff8a9955bf3.jpg)

![asl-tp20l](https://user-images.githubusercontent.com/33549997/166884666-72dd5a28-ed07-448d-988a-9008b20adc06.jpg)

Figure showing Tmp with mesh:
![tmp-tp20l-mesh](https://user-images.githubusercontent.com/33549997/166884693-13eedbf4-a768-4d06-8b20-d2db15ea2e3b.jpg)

**Expected behavior**
Whether it is a numerical issue in TP or what else. Need a fix for proper results. 

**To Reproduce**

compiled with branch:
thomas/optimize_TP
commit e75fa3083492514ef669d27d06dcfbe102aa9b0f 

modules:
Currently Loaded Modulefiles:
 1) admin/1.0                         6) intel-mkl/2020          11) gcc/11.2.0                           16) metis/5.1.0-intel21-i64-r64                 
 2) tempdir/1.0                       7) intel-mpi/2019-intel    12) cmake/3.21.4                         17) netcdf-hdf5-all/4.7_hdf5-1.10-intel21-impi  
 3) lrz/1.0                           8) lrztools/2.0            13) python/3.8.11-extended               18) yaml-cpp/0.7.0-intel21                      
 4) spack/22.2.1                      9) numactl/2.0.14-intel21  14) slurm_setup/1.0                      
 5) intel-oneapi-compilers/2021.4.0  10) libszip/2.1.1           15) parmetis/4.0.3-intel21-impi-i64-r64 

parameter files are here:
/hppfs/work/pr63qo/di52lak2/Shared/AlaskaNew

**Comment by Thomas-Ulrich** [comment]
I think these are the sharp edges of the mesh (of the CAD mesh -> of slab 2.0).
I don't think that's a bug. You need to refine and smooth the mesh to get rid of that.
See here:
https://seissol.readthedocs.io/en/latest/generating-a-megathrust-geometry.html

![image](https://user-images.githubusercontent.com/13536910/166888051-e191df26-f1df-4cad-adcf-1e5ab773e00d.png)

**Comment by daisy20170101** [comment]
thanks Thomas, I will try!

**Comment by daisy20170101** [comment]
i think this can be closed since it is related to the code.
