### ISSUE TITLE
error when Compiling easi

### ISSUE THREAD

**Issue by jjeeffff** [SeisSol/SeisSol#545]
When I compile easi with the command

> cmake -DCMAKE_PREFIX_PATH=$HOME -DCMAKE_INSTALL_PREFIX=$HOME -DASAGI=ON -DIMPALAJIT=ON $EASI_SRC

It came up with an error 

> -- Checking for module 'yaml-cpp'

> --   No package 'yaml-cpp' found

But  I do have the yaml-cpp folder at $HOME/include/. Could you please tell me how to solve this problem?

**Comment by Thomas-Ulrich** [comment]
Hi,
what do you have in ~/lib and ~/include?

**Comment by jjeeffff** [comment]
> Hi, what do you have in ~/lib and ~/include?

Hi, here are the files in ~/lib and ~/include,
/lib
cmake        libhdf5.a           libhdf5_hl.a          libhdf5hl_fortran.la  libhdf5.settings  libmisc.la    libnetcdf.settings  pkgconfig
libasagi.a   libhdf5_fortran.a   libhdf5_hl_fortran.a  libhdf5_hl.la         libimpalajit.a    libnetcdf.a   libparmetis.a
libbzip2.la  libhdf5_fortran.la  libhdf5hl_fortran.a   libhdf5.la            libmetis.a        libnetcdf.la  libyaml-cpp.a

/include
asagi.f90     H5Dpublic.h   H5FDdirect.h  H5FDros3.h           h5_gen.mod    h5lib.mod       H5overflow.h  H5Rpublic.h     h5z.mod        netcdf.h
asagi.h       h5ds.mod      H5FDfamily.h  H5FDsec2.h           h5global.mod  h5l.mod         H5PLextern.h  h5s.mod         H5Zpublic.h    netcdf_mem.h
H5ACpublic.h  H5DSpublic.h  H5FDhdfs.h    H5FDsplitter.h       h5g.mod       H5Lpublic.h     H5PLpublic.h  H5Spublic.h     hdf5.h         netcdf_meta.h
h5a.mod       h5e.mod       H5FDlog.h     H5FDstdio.h          H5Gpublic.h   h5lt_const.mod  h5p.mod       h5tb_const.mod  hdf5_hl.h      netcdf_par.h
H5api_adpt.h  H5Epubgen.h   H5FDmirror.h  H5FDwindows.h        h5im.mod      h5lt.mod        H5Ppublic.h   h5tb.mod        hdf5.mod       parmetis.h
H5Apublic.h   H5Epublic.h   H5FDmpi.h     h5f.mod              h5i.mod       H5LTpublic.h    H5PTpublic.h  H5TBpublic.h    impalajit      yaml-cpp
H5Cpublic.h   H5f90i_gen.h  H5FDmpio.h    h5fortkit.mod        H5IMpublic.h  H5MMpublic.h    H5pubconf.h   h5t.mod         impalajit.f90
h5d.mod       H5f90i.h      H5FDmulti.h   h5fortran_types.mod  H5Ipublic.h   h5o.mod         H5public.h    H5Tpublic.h     impalajit.hh
H5DOpublic.h  H5FDcore.h    H5FDpublic.h  H5Fpublic.h          H5LDpublic.h  H5Opublic.h     h5r.mod       H5version.h     metis.h

**Comment by Thomas-Ulrich** [comment]
I would check that you used the same compilers for both (specifying CC, CXX and FC as detailed in https://easyinit.readthedocs.io/en/latest/compiling_dependencies.html). 
You can also check in the log of cmake for the exact problem (CMakeFiles/CMakeError.log).

**Comment by jjeeffff** [comment]
> I would check that you used the same compilers for both (specifying CC, CXX and FC as detailed in https://easyinit.readthedocs.io/en/latest/compiling_dependencies.html). You can also check in the log of cmake for the exact problem (CMakeFiles/CMakeError.log).

Hi, thanks for answering. I have installed easi successfully, but I met another error when install the Seissol,
`Target "cmTC_3060f" requires the language dialect "CXX17" , but CMake does
  not know the compile flags to use to enable it.`
It seems that the problem is my gcc and g++ don't support CXX17, but I don't have the root authority to update it. So I installed gcc 5.4.0 in conda environment, but still have the same dialect "CXX17" error.  Do you know how to solve it？

**Comment by jjeeffff** [comment]
> I would check that you used the same compilers for both (specifying CC, CXX and FC as detailed in https://easyinit.readthedocs.io/en/latest/compiling_dependencies.html). You can also check in the log of cmake for the exact problem (CMakeFiles/CMakeError.log).

Hi, thanks for answering. I have installed easi without reporting errors, but it came up with an error when I installing the Seissol,
`include could not find load file:
/home/usr/easi/easiTargets.cmake`
And it also reported an error at the end,
`Could NOT find NUMA (missing: NUMA_ROOT_DIR NUMA_INCLUDE_DIR NUMA_LIBRARY)`
Do you know how to solve it?

**Comment by Thomas-Ulrich** [comment]
Yes, Probably you need a more recent gcc. Where are you trying to install? Your desktop? If it is just for testing you can use the docker version of seissol/training. 

Le 7 mai 2022 09:41:44 GMT+02:00, jjeeffff ***@***.***> a écrit :

**Comment by jjeeffff** [comment]
> Yes, Probably you need a more recent gcc. Where are you trying to install? Your desktop? If it is just for testing you can use the docker version of seissol/training. Le 7 mai 2022 09:41:44 GMT+02:00, jjeeffff ***@***.***> a écrit :
> […](#)
> > I would check that you used the same compilers for both (specifying CC, CXX and FC as detailed in https://easyinit.readthedocs.io/en/latest/compiling_dependencies.html). You can also check in the log of cmake for the exact problem (CMakeFiles/CMakeError.log). Hi, thanks for answering. I have installed easi successfully, but I met another error when install the Seissol, `Target "cmTC_3060f" requires the language dialect "CXX17" , but CMake does not know the compile flags to use to enable it.` It seems that the problem is my gcc and g++ don't support CXX17, but I don't have the root authority to update it. So I installed gcc 5.4.0 in conda environment, but still have the same dialect "CXX17" error. Do you know how to solve it？ -- > Reply to this email directly or view it on GitHub: [#545 (comment)](https://github.com/SeisSol/SeisSol/issues/545#issuecomment-1120157454) You are receiving this because you commented. Message ID: ***@***.***>

Thanks for reply, I have solved the CXX17 problem. But I met the 'easiTargets.cmake' and 'NUMA' problems as I mentioned above. It occurs to me that I meet the same NUMA problem when install the ASAGI. And the documentation says turn off Numa by adding -DNONUMA=on. Is this a required dependency of Seissol?

**Comment by jjeeffff** [comment]
The command that occurred error in CMakeLists.txt is `find_package(easi 1.0.0 REQUIRED)`. This command found the easiConfig.cmake file in the directory into which I've cloned the easi source. But I have installed the easi in $HOME  in which I installed all dependencies. There is easiTargets.cmake file in $HOME/lib64/cmake/easi/.
