### ISSUE TITLE
PSpamm isn't needed?

### ISSUE THREAD

**Issue by chaoxinchen** [SeisSol/SeisSol#549]
Hello, I would like to ask if SeisSol has abandoned the PSpamm library. I installed seissol according to the SeisSol Documentation at that time, but unfortunately an error occurred, undefined reference to `pspammsparse, I plan to install it according to github The latest docker file above to install
![image](https://user-images.githubusercontent.com/104721358/168375083-829609a3-76bc-4c4b-9cbd-05cf25eeaf13.png)
thank you very much !

**Comment by sebwolf-de** [comment]
Hi,
PSpaMM is still needed for the `skx` version. We recently changed how SeisSol is built. So, I would encourage you to try a completely new build, according to https://seissol.readthedocs.io/en/latest/compilation.html

**Comment by krenzland** [comment]
Hi, can you please provide details about:

> Steps to reproduce the behavior:
> 1. Which version do you use? Provide branch and commit id.
> 2. Which build settings do you use? Which compiler version do you use? 
> 3. On which machine does your problem occur? If on a cluster: Which modules are loaded?
> 4. Provide parameter/material files.

(Well, points 1-3).

For future issues, please use the issue template.

**Comment by chaoxinchen** [comment]
> Hi, PSpaMM is still needed for the `skx` version. We recently changed how SeisSol is built. So, I would encourage you to try a completely new build, according to https://seissol.readthedocs.io/en/latest/compilation.html



> Hi, PSpaMM is still needed for the `skx` version. We recently changed how SeisSol is built. So, I would encourage you to try a completely new build, according to https://seissol.readthedocs.io/en/latest/compilation.html
Thank you for your reply. I compiled it according to the link you mentioned, but I still encountered this problem. Now I compile it according to the link below. It doesn't seem to need papamm, and it has been compiled successfully. May I ask the following version Can it work normally?
https://github.com/SeisSol/Training/blob/main/Dockerfile

**Comment by chaoxinchen** [comment]
> Hi, can you please provide details about:
> 
> > Steps to reproduce the behavior:
> > 
> > 1. Which version do you use? Provide branch and commit id.
> > 2. Which build settings do you use? Which compiler version do you use?
> > 3. On which machine does your problem occur? If on a cluster: Which modules are loaded?
> > 4. Provide parameter/material files.
> 
> (Well, points 1-3).
> 
> For future issues, please use the issue template.

1. I am using the following version:
https://seissol.readthedocs.io/en/latest/compilation.html
2. my build settings
CC=mpiicc CXX=mpiicpc FC=mpiifort CMAKE_PREFIX_PATH=~:$CMAKE_PREFIX_PATH PKG_CONFIG_PATH=~/lib/pkgconfig/:$PKG_CONFIG_PATH cmake -DNETCDF=ON -DMETIS=ON -DCOMMTHREAD=ON -DASAGI=OFF -DHDF5=ON -DCMAKE_BUILD_TYPE= Release -DTESTING=OFF -DLOG_LEVEL=warning -DLOG_LEVEL_MASTER=info -DHOST_ARCH=skx -DPRECISION=double ..
my compiler version:
gcc10.2.1
cmake 3.14.0
python3.9
And the libraries I use are in accordance with the installation guide, the hdf version is 1.12.0
3. My machine is centos7
4. https://github.com/chaoxinchen/pspamm-error-files

**Comment by chaoxinchen** [comment]
> Hi, PSpaMM is still needed for the `skx` version. We recently changed how SeisSol is built. So, I would encourage you to try a completely new build, according to https://seissol.readthedocs.io/en/latest/compilation.html

Can I use the hsw version to run the example in this link as you said? Since I'm a beginner, I'm not very clear on what each version can do，because I can successfully compile the hsw version in ubutu 18.05

**Comment by chaoxinchen** [comment]
> Hi, PSpaMM is still needed for the `skx` version. We recently changed how SeisSol is built. So, I would encourage you to try a completely new build, according to https://seissol.readthedocs.io/en/latest/compilation.html

I had the same problem in ubuntu18.05 while I compile the sky version:
libSeisSol-lib.a(kernel.cpp.o): In function `seissol::kernel::volume::execute()':
kernel.cpp:(.text+0x14a3): undefined reference to `pspammsparse_33f3061583206b1313c415ced24e4498_m40_n9_k9_ldA56_ldB0_ldC40_alpha1_beta0_alignedA1_alignedC1_transAFalse_transBFalse_pfsigonly(double const*, double const*, double*, double, double, double const*)'
kernel.cpp:(.text+0x14dc): undefined reference to `pspammsparse_33f3061583206b1313c415ced24e4498_m40_n9_k9_ldA56_ldB0_ldC40_alpha1_beta0_alignedA1_alignedC1_transAFalse_transBFalse_pfsigonly(double const*, double const*, double*, double, double, double const*)'
kernel.cpp:(.text+0x1515): undefined reference to `pspammsparse_33f3061583206b1313c415ced24e4498_m40_n9_k9_ldA56_ldB0_ldC40_alpha1_beta0_alignedA1_alignedC1_transAFalse_transBFalse_pfsigonly(double const*, double const*, double*, double, double, double const*)'
libSeisSol-lib.a(kernel.cpp.o): In function `seissol::kernel::derivative::execute1()':
kernel.cpp:(.text+0x6e4f): undefined reference to `pspammsparse_33f3061583206b1313c415ced24e4498_m40_n9_k9_ldA40_ldB0_ldC40_alpha1_beta0_alignedA1_alignedC1_transAFalse_transBFalse_pfsigonly(double const*, double const*, double*, double, double, double const*)'
kernel.cpp:(.text+0x6e8d): undefined reference to `pspammsparse_33f3061583206b1313c415ced24e4498_m40_n9_k9_ldA40_ldB0_ldC40_alpha1_beta1_alignedA1_alignedC1_transAFalse_transBFalse_pfsigonly(double const*, double const*, double*, double, double, double const*)'
kernel.cpp:(.text+0x6ecb): undefined reference to `pspammsparse_33f3061583206b1313c415ced24e4498_m40_n9_k9_ldA40_ldB0_ldC40_alpha1_beta1_alignedA1_alignedC1_transAFalse_transBFalse_pfsigonly(double const*, double const*, double*, double, double, double const*)'
libSeisSol-lib.a(kernel.cpp.o): In function `seissol::kernel::derivative::execute2()':
kernel.cpp:(.text+0x6f70): undefined reference to `pspammsparse_33f3061583206b1313c415ced24e4498_m24_n9_k9_ldA24_ldB0_ldC24_alpha1_beta0_alignedA1_alignedC1_transAFalse_transBFalse_pfsigonly(double const*, double const*, double*, double, double, double const*)'
kernel.cpp:(.text+0x6faf): undefined reference to `pspammsparse_33f3061583206b1313c415ced24e4498_m24_n9_k9_ldA24_ldB0_ldC24_alpha1_beta1_alignedA1_alignedC1_transAFalse_transBFalse_pfsigonly(double const*, double const*, double*, double, double, double const*)'
kernel.cpp:(.text+0x6fee): undefined reference to `pspammsparse_33f3061583206b1313c415ced24e4498_m24_n9_k9_ldA24_ldB0_ldC24_alpha1_beta1_alignedA1_alignedC1_transAFalse_transBFalse_pfsigonly(double const*, double const*, double*, double, double, double const*)'
libSeisSol-lib.a(kernel.cpp.o): In function `seissol::kernel::derivative::execute3()':
kernel.cpp:(.text+0x7090): undefined reference to `pspammsparse_33f3061583206b1313c415ced24e4498_m16_n9_k9_ldA16_ldB0_ldC16_alpha1_beta0_alignedA1_alignedC1_transAFalse_transBFalse_pfsigonly(double const*, double const*, double*, double, double, double const*)'
kernel.cpp:(.text+0x70cf): undefined reference to `pspammsparse_33f3061583206b1313c415ced24e4498_m16_n9_k9_ldA16_ldB0_ldC16_alpha1_beta1_alignedA1_alignedC1_transAFalse_transBFalse_pfsigonly(double const*, double const*, double*, double, double, double const*)'
kernel.cpp:(.text+0x710e): undefined reference to `pspammsparse_33f3061583206b1313c415ced24e4498_m16_n9_k9_ldA16_ldB0_ldC16_alpha1_beta1_alignedA1_alignedC1_transAFalse_transBFalse_pfsigonly(double const*, double const*, double*, double, double, double const*)'
libSeisSol-lib.a(kernel.cpp.o): In function `seissol::kernel::derivative::execute4()':
kernel.cpp:(.text+0x71b0): undefined reference to `pspammsparse_33f3061583206b1313c415ced24e4498_m8_n9_k9_ldA8_ldB0_ldC8_alpha1_beta0_alignedA1_alignedC1_transAFalse_transBFalse_pfsigonly(double const*, double const*, double*, double, double, double const*)'
kernel.cpp:(.text+0x71ef): undefined reference to `pspammsparse_33f3061583206b1313c415ced24e4498_m8_n9_k9_ldA8_ldB0_ldC8_alpha1_beta1_alignedA1_alignedC1_transAFalse_transBFalse_pfsigonly(double const*, double const*, double*, double, double, double const*)'
kernel.cpp:(.text+0x722e): undefined reference to `pspammsparse_33f3061583206b1313c415ced24e4498_m8_n9_k9_ldA8_ldB0_ldC8_alpha1_beta1_alignedA1_alignedC1_transAFalse_transBFalse_pfsigonly(double const*, double const*, double*, double, double, double const*)'
libSeisSol-lib.a(kernel.cpp.o): In function `seissol::kernel::derivative::execute5()':
kernel.cpp:(.text+0x72d0): undefined reference to `pspammsparse_33f3061583206b1313c415ced24e4498_m8_n9_k9_ldA8_ldB0_ldC8_alpha1_beta0_alignedA1_alignedC1_transAFalse_transBFalse_pfsigonly(double const*, double const*, double*, double, double, double const*)'
kernel.cpp:(.text+0x730f): undefined reference to `pspammsparse_33f3061583206b1313c415ced24e4498_m8_n9_k9_ldA8_ldB0_ldC8_alpha1_beta1_alignedA1_alignedC1_transAFalse_transBFalse_pfsigonly(double const*, double const*, double*, double, double, double const*)'
kernel.cpp:(.text+0x734e): undefined reference to `pspammsparse_33f3061583206b1313c415ced24e4498_m8_n9_k9_ldA8_ldB0_ldC8_alpha1_beta1_alignedA1_alignedC1_transAFalse_transBFalse_pfsigonly(double const*, double const*, double*, double, double, double const*)'
libSeisSol-lib.a(kernel.cpp.o): In function `seissol::kernel::subTriangleVelocity::execute0()':
kernel.cpp:(.text+0xbd2e): undefined reference to `pspammsparse_e60658f2bd24617a41c922e81bd775a8_m8_n3_k3_ldA8_ldB0_ldC8_alpha1_beta0_alignedA1_alignedC1_transAFalse_transBFalse_pfsigonly(double const*, double const*, double*, double, double, double const*)'
libSeisSol-lib.a(kernel.cpp.o): In function `seissol::kernel::subTriangleVelocity::execute1()':
kernel.cpp:(.text+0xbdce): undefined reference to `pspammsparse_e60658f2bd24617a41c922e81bd775a8_m8_n3_k3_ldA8_ldB0_ldC8_alpha1_beta0_alignedA1_alignedC1_transAFalse_transBFalse_pfsigonly(double const*, double const*, double*, double, double, double const*)'
libSeisSol-lib.a(kernel.cpp.o): In function `seissol::kernel::subTriangleVelocity::execute2()':
kernel.cpp:(.text+0xbe6e): undefined reference to `pspammsparse_e60658f2bd24617a41c922e81bd775a8_m16_n3_k3_ldA16_ldB0_ldC16_alpha1_beta0_alignedA1_alignedC1_transAFalse_transBFalse_pfsigonly(double const*, double const*, double*, double, double, double const*)'
libSeisSol-lib.a(kernel.cpp.o): In function `seissol::kernel::subTriangleVelocity::execute3()':
kernel.cpp:(.text+0xbef6): undefined reference to `pspammsparse_e60658f2bd24617a41c922e81bd775a8_m56_n3_k3_ldA56_ldB0_ldC56_alpha1_beta0_alignedA1_alignedC1_transAFalse_transBFalse_pfsigonly(double const*, double const*, double*, double, double, double const*)'
libSeisSol-lib.a(kernel.cpp.o): In function `seissol::kernel::addVelocity::execute0()':
kernel.cpp:(.text+0xbfb3): undefined reference to `pspammsparse_e60658f2bd24617a41c922e81bd775a8_m24_n3_k3_ldA24_ldB0_ldC24_alpha1_beta1_alignedA1_alignedC1_transAFalse_transBFalse_pfsigonly(double const*, double const*, double*, double, double, double const*)'
libSeisSol-lib.a(kernel.cpp.o): In function `seissol::kernel::addVelocity::execute1()':
kernel.cpp:(.text+0xc053): undefined reference to `pspammsparse_e60658f2bd24617a41c922e81bd775a8_m24_n3_k3_ldA24_ldB0_ldC24_alpha1_beta1_alignedA1_alignedC1_transAFalse_transBFalse_pfsigonly(double const*, double const*, double*, double, double, double const*)'
libSeisSol-lib.a(kernel.cpp.o): In function `seissol::kernel::addVelocity::execute2()':
kernel.cpp:(.text+0xc0f3): undefined reference to `pspammsparse_e60658f2bd24617a41c922e81bd775a8_m24_n3_k3_ldA24_ldB0_ldC24_alpha1_beta1_alignedA1_alignedC1_transAFalse_transBFalse_pfsigonly(double const*, double const*, double*, double, double, double const*)'
libSeisSol-lib.a(kernel.cpp.o): In function `seissol::kernel::addVelocity::execute3()':
kernel.cpp:(.text+0xc193): undefined reference to `pspammsparse_e60658f2bd24617a41c922e81bd775a8_m24_n3_k3_ldA24_ldB0_ldC24_alpha1_beta1_alignedA1_alignedC1_transAFalse_transBFalse_pfsigonly(double const*, double const*, double*, double, double, double const*)'
libSeisSol-lib.a(kernel.cpp.o): In function `seissol::kernel::computeMInvJInvPhisAtSources::execute()':
kernel.cpp:(.text+0x269a): undefined reference to `pspamm_m56_n1_k56_ldA56_ldB56_ldC56_alphageneric_beta0_alignedA1_alignedC1_transAFalse_transBFalse_pfsigonly(double const*, double const*, double*, double, double, double const*)'
collect2: error: ld returned 1 exit status
CMakeFiles/SeisSol-bin.dir/build.make:356: recipe for target 'SeisSol_Release_dskx_6_elastic' failed
make[2]: *** [SeisSol_Release_dskx_6_elastic] Error 1
CMakeFiles/Makefile2:224: recipe for target 'CMakeFiles/SeisSol-bin.dir/all' failed
make[1]: *** [CMakeFiles/SeisSol-bin.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....

**Comment by chaoxinchen** [comment]
> 

In fact, according to this installation guide, I did not encounter problems in each of the previous steps, until the final make when there was a problem, in fact, I don't know where the problem is.

**Comment by chaoxinchen** [comment]
> Hi, can you please provide details about:
> 
> > Steps to reproduce the behavior:
> > 
> > 1. Which version do you use? Provide branch and commit id.
> > 2. Which build settings do you use? Which compiler version do you use?
> > 3. On which machine does your problem occur? If on a cluster: Which modules are loaded?
> > 4. Provide parameter/material files.
> 
> (Well, points 1-3).
> 
> For future issues, please use the issue template.

would you please tell me the difference between skx and hsw version, now I have successfully compiled the hsw version, but I don't know whether it works or not for the guide.

https://seissol.readthedocs.io/en/latest/compilation.html

 I would appreciate if you could give me a little help

**Comment by krenzland** [comment]
Great! It seems to be working. 

skx/hsw refers to the architecture of your CPU. skx only works, if the CPU uses the Skylake sever architecture (or maybe also more recent architectures). If the CPU does not support the architecture and you compile with the skx setting, it won't work.
Both versions compute the same thing.

I'm closing this issue because the compilation was successful!

**Comment by chaoxinchen** [comment]
感谢您帮我解决这个问题，我现在可以在centos7和Ubuntu18.05上成功编译了。



-----原始邮件-----
发件人:"Lukas Krenz" ***@***.***>
发送时间:2022-05-17 15:49:41 (星期二)
收件人: SeisSol/SeisSol ***@***.***>
抄送: chaoxinchen ***@***.***>, Author ***@***.***>
主题: Re: [SeisSol/SeisSol] PSpamm isn't needed? (Issue #549)






伟大的！它似乎正在工作。

skx/hsw 指的是你的 CPU 的架构。skx 仅适用于 CPU 使用 Skylake 服务器架构（或者也可能是更新的架构）的情况。如果 CPU 不支持该架构并且您使用 skx 设置进行编译，它将无法工作。
两个版本计算相同的东西。

我正在关闭这个问题，因为编译成功了！

—
直接回复此邮件，在 GitHub 上查看，或取消订阅。
您收到此消息是因为您编写了该主题。Message ID: ***@***.***>

**Comment by chaoxinchen** [comment]
I appreciate you helping me solve this problem, I can now successfully compile it on centos7 and Ubuntu18.05.


-----原始邮件-----
发件人:"Lukas Krenz" ***@***.***>
发送时间:2022-05-17 15:49:41 (星期二)
收件人: SeisSol/SeisSol ***@***.***>
抄送: chaoxinchen ***@***.***>, Author ***@***.***>
主题: Re: [SeisSol/SeisSol] PSpamm isn't needed? (Issue #549)






Great! It seems to be working.

skx/hsw refers to the architecture of your CPU. skx only works, if the CPU uses the Skylake sever architecture (or maybe also more recent architectures). If the CPU does not support the architecture and you compile with the skx setting, it won't work.
Both versions compute the same thing.

I'm closing this issue because the compilation was successful!
