### ISSUE TITLE
error compiling with gcc 7.1 - error=strict-aliasing

### ISSUE THREAD

**Issue by casarotti** [SeisSol/SeisSol#55]
error during compiling using gcc 7.1.0 openmpi/2.0.2_gcc_7.1.0

mpicxx -o build/build_relWithDebInfo_generatedKernels_dsnb_mpi_none_9_4/src/Checkpoint/Backend.o -c -Wall -Werror -ansi -Wno-error=unknown-pragmas -mavx -g -O2 -std=c++11 -DENABLE_MATRIX_PREFETCH -DOMPI_SKIP_MPICXX -DALIGNMENT=32 -DREAL_SIZE=8 -DNDEBUG -DCONVERGENCE_ORDER=4 -DNUMBER_OF_QUANTITIES=9 -DNUMBER_OF_RELAXATION_MECHANISMS=0 -DPARALLEL -DUSE_MPI -DGENERATEDKERNELS -DCLUSTERED_LTS -DLOGLEVEL=1 -DLOGLEVEL0=2 -DLOG_LEVEL=2 -DGLM_FORCE_CXX98 -DH5Dcreate_vers=2 -DH5Dopen_vers=2 -DH5Gcreate_vers=2 -DH5Gopen_vers=2 -DH5Acreate_vers=2 -DH5Eget_auto_vers=2 -DH5Eset_auto_vers=2 -DUSE_HDF -DUSE_NETCDF -DUSE_METIS -Isubmodules -Isubmodules/glm -I/home/seissol/include -Isubmodules/yaml-cpp/include -Isubmodules/ImpalaJIT/include -Isubmodules/easi/include -Isubmodules/async -Isrc -Isrc/Equations/elastic -Ibuild/build_relWithDebInfo_generatedKernels_dsnb_mpi_none_9_4 src/Checkpoint/Backend.cpp
In file included from submodules/utils/env.h:42:0,
                 from src/Checkpoint/Wavefield.h:48,
                 from src/Checkpoint/Backend.h:43,
                 from src/Checkpoint/Backend.cpp:42:
submodules/utils/stringutils.h: In static member function ‘static std::vector<T> utils::StringUtils::parseArray(const string&)’:
submodules/utils/stringutils.h:148:32: error: dereferencing type-punned pointer will break strict-aliasing rules [-Werror=strict-aliasing]
   while (std::getline(f, s, ':'))
                                ^
cc1plus: all warnings being treated as errors

**Comment by casarotti** [comment]
I was able to overcome the problem using -fno-strict-aliasing instruction 
but not sure if this will lead some errors during the execution

**Comment by uphoffc** [comment]
Sorry, I cannot reproduce the error message. Could you please post the exact options passed to scons?
