### ISSUE TITLE
Error launching Seissol, after reading mesh

### ISSUE THREAD

**Issue by francescomosconi** [SeisSol/SeisSol#559]
Hi all

**Describe the bug** 
During the code launching it crash after reading mesh 
<img width="734" alt="Schermata 2022-05-31 alle 12 59 20" src="https://user-images.githubusercontent.com/84501864/171158639-1c46a784-d573-4494-a69f-9459068e4fb8.png">

**Expected behavior**
No crash 
**To reproduce**

1. Which version do you use? Provide branch and commit id.
202103_Sumatra-702-g5d85df97

2. Which build settings do you use? Which compiler version do you use?
<img width="758" alt="Schermata 2022-05-31 alle 12 52 09" src="https://user-images.githubusercontent.com/84501864/171157506-39386347-06ed-43d3-b02b-70de48ca709a.png">

3. On which machine does your problem occur? If on a cluster: Which modules are loaded? 
Marconi100 
<img width="593" alt="Schermata 2022-05-31 alle 13 15 51" src="https://user-images.githubusercontent.com/84501864/171161292-2b78a53e-16cd-4902-b183-91adf04e85e2.png">

4.Provide parameter/material files 
[parameter.txt](https://github.com/SeisSol/SeisSol/files/8804550/parameter.txt)

Batch script
`#!/bin/sh
#SBATCH --account=fmosconi
#SBATCH --partition=m100_usr_prod
#SBATCH --qos=m100_qos_dbg
#SBATCH --time=02:00:00
#SBATCH --nodes=2
#SBATCH --ntasks-per-node=4
#SBATCH --cpus-per-task=32
#SBATCH --gres=gpu:4
#SBATCH --gpu-bind=closest
#SBATCH --mem=161070
#SBATCH --job-name=seissol
#SBATCH --mail-type=ALL
#SBATCH --mail-user=mosconi.1767949@studenti.uniroma1.it
#SBATCH --output=seissol.out
#SBATCH --error=seissol.err
#SBATCH --exclusive

SLURM_CPUS_PER_TASK=32
SLURM_NTASKS_PER_NODE=4

NUM_CORES=$(expr $SLURM_CPUS_PER_TASK / 4)
NUM_COMPUTE_CORES=$(expr $NUM_CORES - 1)

export OMP_NUM_THREADS=$NUM_COMPUTE_CORES
export OMP_PLACES="cores($NUM_COMPUTE_CORES)"
export PROC_BIND=spread

export DEVICE_STACK_MEM_SIZE=1.5
export UCX_MEMTYPE_CACHE=n

mpirun --report-bindings --map-by ppr:$SLURM_NTASKS_PER_NODE:node:pe=$NUM_CORES \
-x UCX_MAX_EAGER_RAILS=2 -x UCX_MAX_RNDV_RAILS=2 -x UCX_NET_DEVICES=mlx5_0:1,mlx5_1:1 \
-x UCX_MEM_MMAP_HOOK_MODE=none \
/m100/home/userexternal/fmosconi/Download/SeisSol/build/SeisSol_Release_ssm_70_cuda_6_elastic ./parameters.par`

**Comment by Thomas-Ulrich** [comment]
Hi, can you use the issue template?
Without it, we cannot tell which version of the code you use.  are you running the GPU version of the code?
I suggest you double-checking your boundary conditions.
(you could try using this script https://github.com/SeisSol/Meshing/tree/master/vizualizeBoundaryConditions).
Else you could try running in debug mode.

**Comment by francescomosconi** [comment]
Hope now it's more clearly.
The boundary conditions seems to be ok

**Comment by Thomas-Ulrich** [comment]
ok, so this one is for @ravil-mobile , the developer of the GPU version.
Note that without the full setup, he won't be able to fix the bug (if any).
Also note that the GPU version is under strong development, and almost not used yet.
(in particular dynamic rupture part runs on CPUs).

**Comment by ravil-mobile** [comment]
Hi, I guess the problem comes from easi. In particular impalajit. The default impalajit variant supports only `x86` architecture but Marconi 100 is power9 architecture.

There are 2 possible solutions: 1) install easi with LUA backend or 2) install llvm variant of impalajit and use it for as a backend for easi

**Comment by francescomosconi** [comment]
Yes, the fault.yaml have some function in.

This are the input files with which it crash:
[fault.txt](https://github.com/SeisSol/SeisSol/files/8809197/fault.txt)
[material.txt](https://github.com/SeisSol/SeisSol/files/8809199/material.txt)

Then i tried with a fault.yaml with fixed parameters and the code go on the point where before was interrupted but give another error for memory.

Here the fixed parameters file: 
[fault_2.txt](https://github.com/SeisSol/SeisSol/files/8809227/fault_2.txt)

Here the error:
<img width="914" alt="Schermata 2022-05-31 alle 22 05 59" src="https://user-images.githubusercontent.com/84501864/171278555-42a5ae46-2aff-4005-b7ba-170336a44a9c.png">

**Comment by ravil-mobile** [comment]
How large is your mesh? Here are some notes about memory requirements: https://seissol.readthedocs.io/en/latest/memory-requirements.html. 

You can add the following to your parameters.par file
under Discretization:
LtsWeightTypeId = 1

Alternatively, you can increase the number of nodes

**Comment by krenzland** [comment]
Sorry, added the bug label again.
@ravil-mobile Any idea what we can do here? This should at least give an error message. In my opinion, ImpalaJIT should be deprecated anyway, because it offers no advantage over Lua. But many setups still use ImpalaJIT.

**Comment by francescomosconi** [comment]
Just to give a more clear vision.
If a launching the code with fix parameters fault.yaml it don't give the error after reading mesh, but start calculating and then crash after it has printed the 0.000s output.

[fault_2.txt](https://github.com/SeisSol/SeisSol/files/8827642/fault_2.txt)

<img width="686" alt="Schermata 2022-06-02 alle 22 26 12" src="https://user-images.githubusercontent.com/84501864/171732899-a6fbb614-ce21-4e41-8ddf-464452eedcab.png">

Here the batch script to submit the job: <img width="783" alt="Schermata 2022-06-02 alle 22 26 37" src="https://user-images.githubusercontent.com/84501864/171732957-fc586a5b-f736-4ec1-abcd-cbc46fd815f0.png">

I hope it can be helpful

**Comment by ravil-mobile** [comment]
@francescomosconi, thanks for the bug report. I am going to have a look at it. I haven't tested SeisSol GPU version on multiple GPUs since @krenzland , merged `actor model` (I am not sure whether it is the exact reason). My project has been expired on M100 and I need to find another machine where I can test SeisSol with at least 4 GPUs. 

PS I guess you added `LtsWeightTypeId = 1` to `parameters.par` file and I can see that memory was much better balanced i.e., you didn't get any `out of memory` error.

**Comment by ravil-mobile** [comment]
Hi @francescomosconi , I checked the master branch on one machine with 4 GPUs and everything was ok. Can I ask you which MPI you were using? Can you configure SeisSol with `RelWithDebInfo` and try it again?

In order to help you further with your run I would need your setup i.e., mesh and all parameter files.

**Comment by francescomosconi** [comment]
I'm using: 
-- ompi-4.1.1
-- easi with LUA backend installed with this configuration:
`cmake -DCMAKE_PREFIX_PATH=$HOME -DCMAKE_INSTALL_PREFIX=$SEISSOL_INSTALL -DASAGI=ON -DLUA=ON -DIMPALAJIT=OFF`
-- Seissol configuration with `-DCMAKE_BUILD_TYPE=RelWithDebInfo`
-- Mesh and parameters file by tpv5 example 
This setup give an error on the fault.yaml file 
<img width="1041" alt="Schermata 2022-06-05 alle 21 30 48" src="https://user-images.githubusercontent.com/84501864/172067626-a033211c-f777-4d35-bdd7-a83a28714b31.png">

-- If i use instead the fault.yaml of tpv5 this file [fault_2.txt](https://github.com/SeisSol/SeisSol/files/8840635/fault_2.txt) the output is:
 <img width="739" alt="Schermata 2022-06-05 alle 21 38 36" src="https://user-images.githubusercontent.com/84501864/172067748-8be9921d-ecd3-45ad-8d93-2613f5da5dc4.png">

**Comment by ravil-mobile** [comment]
Did you install `openmpi` and `ucx` by yourself? If yes, then I would suggest to re-install. Here is our documentation:
https://seissol.readthedocs.io/en/latest/marconi.html

I wrote it a few months ago. Probably it is still valid

**Comment by francescomosconi** [comment]
Already followed the tutorial.
I compiled again ucx, ompi and Seissol, but another error appears, when running.
<img width="783" alt="Schermata 2022-06-07 alle 18 26 43" src="https://user-images.githubusercontent.com/84501864/172433807-da87be3a-8b95-41ca-bda5-cc77ba6bae1b.png">


 
Ucx config info:
<img width="1142" alt="Schermata 2022-06-07 alle 17 38 17" src="https://user-images.githubusercontent.com/84501864/172430113-0f8fef5f-2f55-42b0-8100-89d697952799.png">

Ompi config info:
<img width="1093" alt="Schermata 2022-06-07 alle 18 01 30" src="https://user-images.githubusercontent.com/84501864/172430173-235f2d07-ef1f-4283-9cc3-8734d24a0947.png">

These are printed lines during compilation of OMPI, should be relevant this temporarily unavailable tool?
<img width="571" alt="Schermata 2022-05-27 alle 12 36 37" src="https://user-images.githubusercontent.com/84501864/172430457-8e9af1c2-de3e-48f4-ac35-0b51934db813.png">

I have no idea of what's going wrong

**Comment by ravil-mobile** [comment]
Hi @francescomosconi ,

Now, the error message is clear. It says
```
Error: Detected Inf/NaN in receiver output. Aborting
```

It means that some computations went wrong. It can be either SeisSol-GPU specific bug (most likely) or a general SeisSol one.

1) I would try to compile with `double` precision and test it.
2) Try to compile SeisSol-CPU version (`DEVICE_ARCH=none DEVIVE_BACKEND=none GEMM_TOOLS_LIST=Eigen`) and test it.

It would be nice if you can share your setup with me and I will try to debug where the error occurs

**Comment by francescomosconi** [comment]
Hi,
i compile with double precision and the output was always this:
<img width="766" alt="Schermata 2022-06-08 alle 11 13 10" src="https://user-images.githubusercontent.com/84501864/172602711-870e7b31-86e7-4f3f-b466-a523e3ff724c.png">

Then i tried with CPU version of SeisSol with this configuration:
`CC=mpicc CXX=mpicxx FC=mpifort cmake .. \
-DCMAKE_BUILD_TYPE=Release \
-DDEVICE_BACKEND=none \
-DDEVICE_ARCH=none \
-DHOST_ARCH=power9 \
-DPRECISION=single \
-DGEMM_TOOLS_LIST=Eigen`

And the output was:
<img width="639" alt="Schermata 2022-06-08 alle 11 34 29" src="https://user-images.githubusercontent.com/84501864/172602956-8a2a03ef-931a-424b-a117-f5c663e83fe4.png">


Please correct me if the configuration setup has something wrong.
Sorry for the misunderstanding, but what do you mean with my setup? I'm glad to help as possible.
Many thanks

**Comment by francescomosconi** [comment]
I'm thinking on what could be wrong in the installation.
During the installation of the libxsmm library i follow this link [https://libxsmm.readthedocs.io/en/latest/libxsmm_valid/](url) to  work around an error, about the compatibility with the architecture. (Follow the error)

<img width="1382" alt="Schermata 2022-06-09 alle 11 47 26" src="https://user-images.githubusercontent.com/84501864/172818815-b3353b1b-31e1-41d9-8a16-a90af9b2abde.png">


`make PLATFORM=1 DBG=1` Using this everything working.

Could be this the problem?

**Comment by francescomosconi** [comment]
Furthermore, which is the recommended SeisSol branch to use for marconi 100?

**Comment by ravil-mobile** [comment]
Hi, @francescomosconi. 

>  Furthermore, which is the recommended SeisSol branch to use for marconi 100?

It is supposed to be the master branch. 

> During the installation of the libxsmm library i follow this link [https://libxsmm.readthedocs.io/en/latest/libxsmm_valid/](https://github.com/SeisSol/SeisSol/issues/url) to work around an error, about the compatibility with the architecture. (Follow the error)

Libsxmm was not tested by us on power9 architecture. You don't need to install it. Use `Eigen` backend instead. It is much more reliable.

`-DGEMM_TOOLS_LIST=Eigen` - this was correct.  It is strange what it crashed. Probably you use `mpirun` launch parameters which were adjusted for the GPU version. Try to launch the CPU version with a plain `mpirun` parameters. I mean `mpirun -n <num_proc> ./SeisSol_* ./parameters.par

 > Sorry for the misunderstanding, but what do you mean with my setup?
I mean `mesh files`, `parameters.par` and all `yaml` files. I will run it on a local x86 machine.

**Comment by francescomosconi** [comment]
Should this UCS error the problem?

<img width="584" alt="Schermata 2022-06-21 alle 12 00 36" src="https://user-images.githubusercontent.com/84501864/174773742-0735e265-7678-4a65-8e2a-213492fab907.png">

I'm using the tpv5 example setup, i just converted the mesh file with pumgen
Many thanks

**Comment by ravil-mobile** [comment]
It is strange to observe `Inf/Nan`. Can you try to take seissol source code from our `dr/cpp` branch. In `dr/cpp` branch we implemented Dynamic Rupture with OpenMP GPU offloading. It requires to used `nvhpc` compiler collection >= 22.3 version. Of course, it entails recompiling all seissol dependencies with `nvhpc`

**Comment by francescomosconi** [comment]
Hi @ravil-mobile, we are in trouble to install the last version of UCX, whit `nvhpc`.
This is the configuration file we are using:


$ git clone https://github.com/openucx/ucx.git
$ ./autogen.sh
$ mkdir build && cd build

$ CC=/m100/home/userexternal/fmosconi/usr/local/openmpi/Linux_ppc64le/22.5/compilers/bin/nvc CXX=/m100/home/userexternal/fmosconi/usr/local/openmpi/Linux_ppc64le/22.5/compilers/bin/nvcc FC=/m100/home/userexternal/fmosconi/usr/local/openmpi/Linux_ppc64le/22.5/compilers/bin/nvfortran \
../contrib/configure-opt \
--prefix=$SEISSOL_INSTALL_GPU \
--build=powerpc64le-redhat-linux-nvc \
--host=powerpc64le-redhat-linux-nvc \
--disable-logging --disable-debug \
--disable-assertions --disable-params-check \
--disable-params-check --enable-optimizations \
--disable-assertions --disable-logging --with-pic \
--without-java \
--enable-mt \
--enable-compiler-opt=1 \
--with-cuda=/cineca/prod/opt/compilers/cuda/11.0/none \
--with-gdrcopy \
--with-knem=/opt/knem-1.1.3.90mlnx1 \
--without-xpmem

$ make -j

 
After the make command the process end with this error:
<img width="1253" alt="err_last_ucx" src="https://user-images.githubusercontent.com/84501864/178705335-18d49be4-102e-4d87-a065-519f0bfca6ef.png">

How we can procede?
Many thanks in advance.
