### ISSUE TITLE
possible mistake in `saveDynamicStressOutput` in `dr/cpp`

### ISSUE THREAD

**Issue by ravil-mobile** [SeisSol/SeisSol#562]
https://github.com/SeisSol/SeisSol/blob/81179a747b4d6d33aaf17906d41e52c6051b3e70/src/DynamicRupture/FrictionLaws/LinearSlipWeakening.h#L136-L146

why do we use `this->dynStressTimePending[pointIndex]` in line 139 instead of
 `this->dynStressTimePending[ltsFace][pointIndex]`

**Comment by sebwolf-de** [comment]
Closed with #566
