### ISSUE TITLE
Error in running SeisSol in supermuc

### ISSUE THREAD

**Issue by daisy20170101** [SeisSol/SeisSol#57]

**Comment by daisy20170101** [comment]
Got the error but don't understand

Thread 25 (Thread 0x2b01ea17a700 (LWP 37576)):
#0  0x00002b01e41b8d03 in epoll_wait () from /lib64/libc.so.6
#1  0x00002b01e9b0ac78 in poe_exiting_thread () from /opt/ibmhpc/pe1404/base/intel/lib64/libpoe.so
#2  0x00002b01e21d3806 in start_thread () from /lib64/libpthread.so.0
#3  0x00002b01e41b867d in clone () from /lib64/libc.so.6
#4  0x0000000000000000 in ?? ()
Thread 24 (Thread 0x2b01ea37b700 (LWP 37577)):
#0  0x00002b01e41b8d03 in epoll_wait () from /lib64/libc.so.6
#1  0x00002b01e9b09576 in pm_child_sig_thread () from /opt/ibmhpc/pe1404/base/intel/lib64/libpoe.so
#2  0x00002b01e21d3806 in start_thread () from /lib64/libpthread.so.0
#3  0x00002b01e41b867d in clone () from /lib64/libc.so.6
#4  0x0000000000000000 in ?? ()
Thread 23 (Thread 0x2b01ea57c700 (LWP 37578)):
#0  0x00002b01e21db527 in do_sigwait () from /lib64/libpthread.so.0
#1  0x00002b01e21db5cd in sigwait () from /lib64/libpthread.so.0
#2  0x00002b01e9b0a4ca in pm_async_thread () from /opt/ibmhpc/pe1404/base/intel/lib64/libpoe.so
#3  0x00002b01e21d3806 in start_thread () from /lib64/libpthread.so.0
#4  0x00002b01e41b867d in clone () from /lib64/libc.so.6
#5  0x0000000000000000 in ?? ()
.....

Thread 16 (Thread 0x2b02311cf780 (LWP 37586)):
#0  0x00002b01e21d766c in pthread_cond_wait@@GLIBC_2.3.2 () from /lib64/libpthread.so.0
#1  0x00002b01e3bd90c9 in ___kmp_suspend_template_aux (th_gtid=<optimized out>, th=<optimized out>, flag=<optimized out>) at ../../src/z_Linux_util.cpp:1571
#2  __kmp_suspend_template (th_gtid=<optimized out>, flag=<optimized out>) at ../../src/z_Linux_util.cpp:1700
#3  __kmp_suspend_64 (th_gtid=-376968892, flag=0x80) at ../../src/z_Linux_util.cpp:1809
#4  0x00002b01e3b77d3b in suspend (this=<optimized out>, th_gtid=<optimized out>) at ../../src/kmp_wait_release.h:590
#5  __kmp_wait_template (this_thr=<optimized out>, flag=<optimized out>, final_spin=<optimized out>, itt_sync_obj=<optimized out>) at ../../src/kmp_wait_release.h:318
#6  wait (this=<optimized out>, this_thr=<optimized out>, final_spin=<optimized out>, itt_sync_obj=<optimized out>) at ../../src/kmp_wait_release.h:601
#7  _INTERNAL_25_______src_kmp_barrier_cpp_ac7c2c73::__kmp_hyper_barrier_release (bt=3917998404, this_thr=0x80, gtid=11, tid=-1, propagate_icvs=-376968960, itt_sync_obj=0x5) at ../../src/kmp_barrier.cpp:866
#8  0x00002b01e3b7927d in __kmp_fork_barrier (gtid=-376968892, tid=128) at ../../src/kmp_barrier.cpp:2178
#9  0x00002b01e3ba28e0 in __kmp_launch_thread (this_thr=0x2b01e987e944) at ../../src/kmp_runtime.cpp:5696
#10 0x00002b01e3bd51b4 in _INTERNAL_26_______src_z_Linux_util_cpp_b2df00d9::__kmp_launch_worker (thr=0x2b01e987e944) at ../../src/z_Linux_util.cpp:585
#11 0x00002b01e21d3806 in start_thread () from /lib64/libpthread.so.0
#12 0x00002b01e41b867d in clone () from /lib64/libc.so.6
#13 0x0000000000000000 in ?? ()
Thread 15 (Thread 0x2b02315d0800 (LWP 37587)):
#0  0x00002b01e21d766c in pthread_cond_wait@@GLIBC_2.3.2 () from /lib64/libpthread.so.0
#1  0x00002b01e3bd90c9 in ___kmp_suspend_template_aux (th_gtid=<optimized out>, th=<optimized out>, flag=<optimized out>) at ../../src/z_Linux_util.cpp:1571
#2  __kmp_suspend_template (th_gtid=<optimized out>, flag=<optimized out>) at ../../src/z_Linux_util.cpp:1700
#3  __kmp_suspend_64 (th_gtid=-376974268, flag=0x80) at ../../src/z_Linux_util.cpp:1809
#4  0x00002b01e3b77d3b in suspend (this=<optimized out>, th_gtid=<optimized out>) at ../../src/kmp_wait_release.h:590
#5  __kmp_wait_template (this_thr=<optimized out>, flag=<optimized out>, final_spin=<optimized out>, itt_sync_obj=<optimized out>) at ../../src/kmp_wait_release.h:318
#6  wait (this=<optimized out>, this_thr=<optimized out>, final_spin=<optimized out>, itt_sync_obj=<optimized out>) at ../../src/kmp_wait_release.h:601
#7  _INTERNAL_25_______src_kmp_barrier_cpp_ac7c2c73::__kmp_hyper_barrier_release (bt=3917993028, this_thr=0x80, gtid=11, tid=-1, propagate_icvs=-376974336, itt_sync_obj=0x5) at ../../src/kmp_barrier.cpp:866
#8  0x00002b01e3b7927d in __kmp_fork_barrier (gtid=-376974268, tid=128) at ../../src/kmp_barrier.cpp:2178
#9  0x00002b01e3ba28e0 in __kmp_launch_thread (this_thr=0x2b01e987d444) at ../../src/kmp_runtime.cpp:5696
#10 0x00002b01e3bd51b4 in _INTERNAL_26_______src_z_Linux_util_cpp_b2df00d9::__kmp_launch_worker (thr=0x2b01e987d444) at ../../src/z_Linux_util.cpp:585
#11 0x00002b01e21d3806 in start_thread () from /lib64/libpthread.so.0
#12 0x00002b01e41b867d in clone () from /lib64/libc.so.6
#13 0x0000000000000000 in ?? ()

.....

**Comment by Thomas-Ulrich** [comment]
which branch? which commit? where does it crash in the out log?

**Comment by daisy20170101** [comment]
Hi, 

I found the error: there is a 'return' missing in the yaml file. 
I was just wondering whether there can be a better error report for debugging?

Thx
