### ISSUE TITLE
Run SeisSol on personal computer

### ISSUE THREAD

**Issue by Yonatan298** [SeisSol/SeisSol#578]
Hi,
My name is Yonatan, and I am an incoming Ph.D. student at Scripps in UCSD and expected to work with Prof.
Alice Gabriel. I am trying to set the SeisSol platform on my windows PC (Ubuntu-Virtual machine) and my MacBook Air m1.
On my Ubuntu machine, I managed to install all the required packages. However, I faced an issue when I tried to compile the SeiSol when typing the make -j48 command. Log attached:
[Log_Ubuntu.txt](https://github.com/SeisSol/SeisSol/files/8909060/Log_Ubuntu.txt)

On my MacBook Air, I failed to install ASAGI and installed easi without it. However, when I tried to compile SeiSol via cmake
I got the following error: Could NOT find NUMA. I tried to use -DNONUMA=on, but it didn't work. I know that the platform is not intended for Mac os, but I do manage to overcome some challenges, and I believe it would be beneficial if more users could run the platform using their Macs, including me, during my research.
I have attached the terminal output of the Mac:
[Terminal Saved Output_Mac_os.txt](https://github.com/SeisSol/SeisSol/files/8909122/Terminal.Saved.Output_Mac_os.txt)

I will greatly appreciate your assistance in helping me to solve this issue.

**Comment by Thomas-Ulrich** [comment]
Hi,
I think the first issue is related to pspamm.py not beeing found/executed by SeisSol, earlier in the log. Can you check?

**Comment by Thomas-Ulrich** [comment]
for asagi, maybe try to run ccmake ..  to see with the GUI if you  -DNONUMA=ON was correctly understood by cmake?

**Comment by Thomas-Ulrich** [comment]
But I think the chip is not supported anyway, so it might not be worth trying to install.

**Comment by Yonatan298** [comment]
Hi, Thank you for the prompt responses! If I am going to run SeisSol on a cluster, it is indeed unnecessary to 
install it on my Mac (especially if there is no support). However, I want to practice running the platform before enrolling, so I will proceed with Ubuntu. I found PSpaMM here: https://github.com/peterwauligmann/PSpaMM. So just git clone it to my &Home directory or anything else is required (different place or compilation)?

**Comment by sebwolf-de** [comment]
Sure, I also like to try out small scale simulations on my personal computer, before I scale things up. Could you run `lscpu` in your VM. Then we can decide, which hardware architecture is the best to use. I have the feeling that you do not need PSpaMM at all on your local computer. 
For completeness, this is how you install PSpaMM: https://seissol.readthedocs.io/en/latest/compilation.html#installing-pspamm

**Comment by Yonatan298** [comment]
Yeah, I see now that I have pspamm.py in my &Home/bin directory. Here is the log of lscpu command:
[lscpu_log.txt](https://github.com/SeisSol/SeisSol/files/8909513/lscpu_log.txt)

**Comment by sebwolf-de** [comment]
Thx, try `-DHOST_ARCH=hsw` or if that doesn't work `-DHOST_ARCH=snb`.

**Comment by Yonatan298** [comment]
Thanks! -DHOST_ARCH=hsw worked: 
[Log_upd.txt](https://github.com/SeisSol/SeisSol/files/8909915/Log_upd.txt)

**Comment by sebwolf-de** [comment]
Okay, can I close the issue then?

**Comment by Yonatan298** [comment]
It seems that it was cutted. Here is the command :OMP_NUM_THREADS=<threads> mpiexec  -np <n> ./SeisSol_<configuration> parameters_master.par and I asked specifically about the <threads> and <configuration>

**Comment by Yonatan298** [comment]
OMP_NUM_THREADS=<threads> and SeisSol_<configuration>

**Comment by Yonatan298** [comment]
Never mind, my question is what to put in each <..> (threads and configurations)?

**Comment by sebwolf-de** [comment]
Strange, I try to answer as good as possible ;-)
We have a hybrid parallelization:  MPI for inter-node parallelism and OpenMP for intra-node parallelism.
If you only run on your laptop, the number of nodes is `1`. The number of threads depends on your machine, for your VM it seems to be `4`.
Then you execute 
```
OMP_NUM_THREADS=4
mpiexec -np 1 ./SeisSol_[...] parameters.par
```
If you only have one node, you can actually leave out the `mpiexec -np 1`.

**Comment by Yonatan298** [comment]
Ok. and what about the "configuration" [...] in your comment?

**Comment by Yonatan298** [comment]
Seems that there is some kind of a problem with the HDF5. 
[Log.txt](https://github.com/SeisSol/SeisSol/files/8910468/Log.txt)
 Also, I don't have the "parameters_master.par" file, only "parameters.par".

**Comment by sebwolf-de** [comment]
The file does `tpv33_gmsh` does not exist. Did you generate the mesh? And it doesn't matter, how you create your mesh.
Anyway, I am closing this issue now, since SeisSol runs on your personal computer now. If you have any further problems, please open a new issue/discussion.

**Comment by Yonatan298** [comment]
Ok. Thanks a lot!
