### ISSUE TITLE
dr/cpp fault receiver output

### ISSUE THREAD

**Issue by sebwolf-de** [SeisSol/SeisSol#583]
A few things, which need to be done:

- [ ] The faultreceiver output stops at the last timestep before the final time. The output at the final time is not written.
- [x] Receivers are numbered from `0` to `n-1`, on the master, they are numbered from `1` to `n`.
- [x] DS is not correct for tpv5.

**Comment by sebwolf-de** [comment]
I understand your point. The receivers in the volume are numberd from `1` to `n`, so I thought we might want it to be consistent.
https://github.com/SeisSol/SeisSol/blob/a8294e6f60577b1680389efbaa8d8e9c0ac81c5a/src/ResultWriter/ReceiverWriter.cpp#L93

**Comment by ravil-mobile** [comment]
Ok. I can do it. Regarding to the fist issue, I realized that I was no flushing data from the cache.
https://github.com/SeisSol/SeisSol/blob/a4fe0b0e48f003694b536c51aab53829e67633b8/src/DynamicRupture/Output/OutputManager.cpp#L262-L295

It is related to `currentCacheLevel`. Maybe I need to implement a so-call `flush` method and call it from the destructor

**Comment by sebwolf-de** [comment]
Great! I'll take care of the DS output

**Comment by ravil-mobile** [comment]
The fault receiver output of the last time step has been fixed in #585 PR
