### ISSUE TITLE
allocation problem with FL=103

### ISSUE THREAD

**Issue by daisy20170101** [SeisSol/SeisSol#59]
When using FL=103, error occurs as:
Error: could not allocate all variables!

No such error with the previous version of SeisSol

**Comment by uphoffc** [comment]
Could you give a few more details about this bug? How many elements does your mesh have? Which order? How many nodes? Which cluster? Which version did work?

**Comment by daisy20170101** [comment]
this can also be closed, as I don't have this problem anymore.
