### ISSUE TITLE
error in submodules

### ISSUE THREAD

**Issue by daisy20170101** [SeisSol/SeisSol#61]
submodules/glm/glm/detail/../detail/func_common.inl(631): error: the global scope has no "isnan"
  					return ::isnan(x) != 0;
  					         ^

submodules/glm/glm/detail/../detail/func_common.inl(665): error: the global scope has no "isinf"
  					return ::isinf(x);
  					         ^

I manually fixed it to be std::isnan and std::isinf and now it works.

**Comment by uphoffc** [comment]
Could you please post the compile settings you used? This issue is not related to SeisSol but GLM and we might need to post a bug report to the GLM developers.

**Comment by daisy20170101** [comment]
I am using these modules:   
1) intel-lm/1.0     2) intel/2017       3) mpi.intel/2017   4) mkl/11.3

**Comment by krenzland** [comment]
I had the exact same issue when installing locally at my workstation (Ubuntu 16.04 LTS, Intel Compiler) while following the installation procedure exactly. I used the same fix as @daisy20170101.

I think the issue stems from a missing preprocessor definition, I will look into this in the near future.

**Comment by ravil-mobile** [comment]
I remember I had a similar issue while I was installing some sub-modules. In my case, I used intel 19.0 compiler

**Comment by Thomas-Ulrich** [comment]
Hi Duo/Lukas,

Maybe you can create a pull request with your fix if you already have a fix, right?

Thomas.

**Comment by daisy20170101** [comment]
I don't have this issue with intel-mpi/2018 in Durham/hamilton cluster. And this is with glm. Should we ask them to fix it?

**Comment by krenzland** [comment]
This is an issue with GLM probably, the fix is editing their source code.
There might be some issue with our compiler settings but I've currently got no idea how to fix this.

**Comment by ravil-mobile** [comment]
I strongly believe that either glm developers or Intel ones messed up something with their C macros in their source codes. I left an issue in their github repo of glm but I haven't gotten any answer.

**Comment by krenzland** [comment]
@sebwolf-de started porting all code that uses GLM to eigen some time ago. This would be the best way out of this.

**Comment by sebwolf-de** [comment]
Fixed by #216
