### ISSUE TITLE
dr/cpp: no similar flexibility in initializing stress as on master yet

### ISSUE THREAD

**Issue by Thomas-Ulrich** [SeisSol/SeisSol#618]
**Describe the bug**
We should be able to initialize stress with s_ij or T_i and nucleation with nu_ij or T_nuc_i on dr/cpp as on master.
But currently, it seems we can only have (s_ij, nuc_ij) or (T_i, T_nuc_i) but not (s_ij, T_nuc_i) or (T_i, nuc_ij).

**Expected behavior**
same flexibility as on master.

**Comment by sebwolf-de** [comment]
Fixed with #628
