### ISSUE TITLE
Inf/NaN in receiver output

### ISSUE THREAD

**Issue by francescomosconi** [SeisSol/SeisSol#619]
**Describe the bug**
Error Inf/NaN in receiver output after the 0s print, when are used AxisAlignedCuboidalDomainFilter in the parameter.yaml file.

**Expected behavior**
It should end the process correctly

**To Reproduce**
1. Verison: 202103_Sumatra-713-g115018ad. Master branch
2. Using SeisSol version for CPU, with the `easi` package installed with `lua` backend. 
3. Working on marconi100-Cineca. Load module are cmake/3.20.0 and python/3.8.2
4. The setup is the same as tpv5 example,  except for the fault.yaml that is replaced by:
[fault_axis_filter.txt](https://github.com/SeisSol/SeisSol/files/9122128/fault_axis_filter.txt)

**Screenshots/Console output**
That's the error file:
[seissol_err.txt](https://github.com/SeisSol/SeisSol/files/9122091/seissol_err.txt)

**Additional context**
The process end here:
[seissol_out.txt](https://github.com/SeisSol/SeisSol/files/9122098/seissol_out.txt)

**Comment by Thomas-Ulrich** [comment]
I cannot reproduce on supermuc double precision o4.

**Comment by Thomas-Ulrich** [comment]
I also tried single precision o6, and it starts running (e.g. writes energy output at 0.05s).

**Comment by francescomosconi** [comment]
Thank you for your time. 
Do you have any suggest to understand the error?

**Comment by ravil-mobile** [comment]
Hi, I ran tpv5 on M100 with ImpalaJIT-llvm backend and obtained correct numerical results.
