### ISSUE TITLE
Error with tpv12 example (Seissol GPU)

### ISSUE THREAD

**Issue by francescomosconi** [SeisSol/SeisSol#654]
**Describe the bug**
When running the tpv12 example the process hangs after initializing fault

**Expected behavior**
The process work well and start calculating 

**To Reproduce**
Version: 202103_Sumatra-1024-g6cb274ac ; branch: dr/sycl
Using Seissol GPU version with ImpalaJit-llvm on marconi100
Loaded module:
<img width="730" alt="Schermata 2022-08-26 alle 14 37 26" src="https://user-images.githubusercontent.com/84501864/186904922-0b2a0af0-1426-468a-bdfa-2d8cf9b7f5ad.png">

Provide parameter/material files:

https://drive.google.com/drive/folders/1JIJqIVpzgfyP9Rs01zUK0-Tjc4BLRvhr?usp=sharing

Here there are all the files i used and the correspondent output and error. The only exception from the original file of the tpv12 is the addition of the nuc stress in the fault.yaml for the FL=16

Many thanks,
Francesco
P.s. I hope you are able to reach all the input files, if not let me know

**Comment by Thomas-Ulrich** [comment]
Could it be related to the async output? In that case you could try:
xdmfWriterBackend = 'posix'

**Comment by francescomosconi** [comment]
Hi, 
this line is already in the parameters file.
Just to have more clear view, the tpv5 example work correctly if i use the LSW. But if i try to implement the forced rupture time function always in the tpv5 this same error occur.
