### ISSUE TITLE
Constantly slipping elements in TPV12

### ISSUE THREAD

**Issue by NicoSchlw** [SeisSol/SeisSol#660]
**Describe the bug**
The TPV12 setup from the SeisSol repo produces constantly slipping elements near the bottom of the fault, leading to high absolute slips when running for longer times (to analyze waveforms). There is a strong initial stress discontinuity, so maybe the problem is just ill-posed? Or it is related to the slip artifacts in TPV5 when using a non-symmetric mesh?

**Expected behavior**
No constantly slipping elements

**To Reproduce**
1. Which version do you use? Master c952a4a
2. Which build settings do you use? Which compiler version do you use?  Elastic, Order 4, double precision
![image](https://user-images.githubusercontent.com/42612980/187395048-1a35cc54-d274-4328-b0ce-94c940e9deb6.png)

3. On which machine does your problem occur? If on a cluster: Which modules are loaded? SupermucNG
4. Provide parameter/material files. [parameters.txt](https://github.com/SeisSol/SeisSol/files/9451410/parameters.txt)

**Screenshots/Console output**
ASl after 50s:
![image](https://user-images.githubusercontent.com/42612980/187396744-f9004f97-f7a8-4ea4-8a86-b14fa4a7dfa0.png)

Td0 at 0s:
![image](https://user-images.githubusercontent.com/42612980/187397080-7833693e-04f7-4ff6-afa9-7759ec3b92e6.png)

**Comment by ravil-mobile** [comment]
Hi, Can you try the following commit 80a266e3e44a293b69051281d580bbdc36b896e6 ?

**Comment by Thomas-Ulrich** [comment]
(or let say the latest master)

**Comment by NicoSchlw** [comment]
I tried it again with 80a266e but the problem still persists 

ASl at 50s:
![image](https://user-images.githubusercontent.com/42612980/187870558-c1203abb-c99e-48fe-9d82-4da6cfde33fa.png)

SRd at 50s:
![image](https://user-images.githubusercontent.com/42612980/187870689-eab28762-fd88-40d6-978d-a95e3189f85a.png)

Files:
[parameters.txt](https://github.com/SeisSol/SeisSol/files/9468196/parameters.txt)
[2311512.tpv12.txt](https://github.com/SeisSol/SeisSol/files/9468198/2311512.tpv12.txt)

**Comment by sebwolf-de** [comment]
If I remove the sharp stress interface at 12km depth, I get a smooth result for ASl after 50s:
```
[s_xx, s_yy, s_zz]: !FunctionMap
  map:
    depth: return abs(z);
    s_max_minus_Pf: return 9.8 * (2700.0 - 1000.0);
  components:
    # Upper region (includes fault)
    - !AxisAlignedCuboidalDomainFilter
      limits:
        depth:          [0, .inf]
        s_max_minus_Pf: [-.inf, .inf]
      components: !FunctionMap
        map:
          # Round to two significant digits as in benchmark description
          s_xx: return -0.01 * round(100.0 * (0.5 * (1.0 + 0.3496) * s_max_minus_Pf)) * depth;
          s_yy: return -0.01 * round(100.0 *               (0.3496 * s_max_minus_Pf)) * depth;
          s_zz: return -s_max_minus_Pf * depth;
```
So, this indicates that it is not the same problem as in #546, but still doesn't solve the problem.
The stress boundary is sharp, but the current mesh doesn't support that. I have created a mesh, which also includes the stress-boundary, see attached geo file. [tpv12_13_example.txt](https://github.com/SeisSol/SeisSol/files/9732710/tpv12_13_example.txt)
ASl after 50s with continuous background stress:
![ASl_continuous-stress](https://user-images.githubusercontent.com/24592027/194536442-e82b83c9-1301-4a53-be72-de8eb73fb354.png)
ASl after 50s with the interface explicitely meshed:
![ASl_explicit-boundary](https://user-images.githubusercontent.com/24592027/194536552-b5570312-fff6-4443-8c74-ee0e65441fa1.png)
