### ISSUE TITLE
Different behaviors when nucleating by s_xy and nuc_xy after the merge of the two linear slip-weakening regimes (FL=2 & FL=16)

### ISSUE THREAD

**Issue by JeenaYun** [SeisSol/SeisSol#688]
**Describe the bug**
Hi, I used to use the FL=2 option for my simulation, nucleating by increasing the s_xy value inside a weak nucleation patch.
However, after the update in SeisSol, FL=2 is merged with FL=16, and seems like it requires defining either nucleation stresses or tractions (nuc/Tnuc). I was not sure how they work, so I tested them as follows:
|   | s_xx  | s_yy | s_zz  | s_xy | s_yz  | s_xz | nuc_xx  | nuc_yy | nuc_zz  | nuc_xy | nuc_yz  | nuc_xz | 
| :---: | :---: | :---: | :---: | :---: | :---: | :---: | :---: | :---: | :---: | :---: | :---: | :---: |
| Case 1 | -120e6 | -120e6 | -120e6 | -70e6 (elsewhere) <br>-81.6e6 (nuc. zone) | 0 | 0 | 0 | 0 | 0 | 0 | 0 | 0 |
| Case 2 | -120e6 | -120e6 | -120e6 | -70e6 | 0 | 0 | 0 | 0 | 0 | -81.6e6 (nuc. zone) | 0 | 0 |

I feel like these two cases should give the same result. However, when I run the simulation for 1 s and compare the waveform output for three stations, the amplitudes from cases 1 and 2 differ by a factor of ~ 3 - 4. 
![compare_nucxy_sxy_xyz](https://user-images.githubusercontent.com/94714078/194677494-7bd75df7-1b8b-4eee-9d6a-3385992214ee.png)
When normalized, their behavior seems consistent. 
![compare_nucxy_sxy_xyz_normalized](https://user-images.githubusercontent.com/94714078/194677502-bd752e06-8c8b-49e4-b78a-c410d2f68b85.png)
Also, the seismic moment from the two cases are significantly deviating from each other.
![ssaf_21_compare_moment_sxy_nucxy](https://user-images.githubusercontent.com/94714078/194677892-b7d16d89-44fc-4c15-bc98-68df1c526977.png)

**Expected behavior**
The two cases are expected to give the same result.

**To Reproduce**
1. Which version do you use? Provide branch and commit id.
[master] Merge pull request #665 from SeisSol/thomas/document_more_backward_incompatibility
3. Which build settings do you use? Which compiler version do you use? 
mpi compiler
4. On which machine does your problem occur? If on a cluster: Which modules are loaded?
SuperMUC
5. Provide parameter/material files.
[case1.tar.gz](https://github.com/SeisSol/SeisSol/files/9737934/case1.tar.gz)
[case2.tar.gz](https://github.com/SeisSol/SeisSol/files/9737935/case2.tar.gz)
All the files required for SeisSol running are zipped in each file. Need to create a directory named 'output' in your working directory.
[run_SeisSol.txt](https://github.com/SeisSol/SeisSol/files/9737938/run_SeisSol.txt)
SuperMUC job submission script. Make sure to convert run_SeisSol.txt to run_SeisSol.sh before running.

**Screenshots/Console output**

**Additional context**

**Comment by Thomas-Ulrich** [comment]
Nuc_xy is added over t_0 (defined in main parameter) to S_xy. So nuc_xy should be -11.6e6 and t_0 set to 0.


Le 8 octobre 2022 02:18:42 GMT+02:00, Jeena Yun ***@***.***> a écrit :

**Comment by sebwolf-de** [comment]
I suppose, @Thomas-Ulrich's answer solved the issue. If not, please reopen.

**Comment by Thomas-Ulrich** [comment]
Just test v0.9.0: similar results as the current master.

**Comment by JeenaYun** [comment]
I see, you are right. Thank you so much for investigating this issue!
