### ISSUE TITLE
Ts0 visualization problem: showing strength, not stress at t = 0

### ISSUE THREAD

**Issue by JeenaYun** [SeisSol/SeisSol#714]
**Describe the bug**
Hi, I recently found that Ts0 from the fault output shows shear strength (normal stress * static friction coefficient), rather than shear stress at time t = 0 s. This seems to happen only within a 'nucleation zone', defined as a separate surface in the geometry file.
I confirmed this behavior with [TPV5 example](https://github.com/SeisSol/Examples/tree/master/tpv5): within the nucleation patch in the middle of the fault, Ts0 value is 81.24 MPa, which equals the shear strength (120 MPa * 0.677), rather than the prescribed shear stress of 81.6 MPa. However, the rest of the fault (70 MPa) and the two patches with high (78 MPa) and low (62 MPa) initial stresses seem to show exactly the value that they should show.
I suspect this is a problem of visualization. I would appreciate it if anyone can take a look at this issue and confirm whether it is an actual bug or if I did something wrong.

**Expected behavior**
Ts0 at t = 0 (initial time) should show the initial shear stress prescribed by the fault.yaml file. For TPV5 example, it should show 81.6 MPa inside the nucleation patch.

**To Reproduce**
Please reproduce [TPV5 example](https://github.com/SeisSol/Examples/tree/master/tpv5) with Ts0 output on.

**Comment by sebwolf-de** [comment]
Hi, thanks for reporting. This is actually a feature not a bug ;-) https://github.com/SeisSol/SeisSol/blob/master/src/DynamicRupture/Output/ReceiverBasedOutput.cpp#L307-L319
Actually, this is a quite complicated topic. The physics of coulomb friction say that traction <= strength. In the TPV5 example we actually have the case that traction(t=0) > strength(t=0) in the nucleation patch. Maybe @AliceGabriel or @Thomas-Ulrich can comment further on that topic.

**Comment by AliceGabriel** [comment]
Hi, thanks @sebwolf-de ! I think the confusion stems from the fact that we do not provide an output of initial conditions before we first step through our friction routines.

**Comment by krenzland** [comment]
Can we document this (unexpected) behavior somewhere?
