### ISSUE TITLE
sumatra-andaman dataset for master branch

### ISSUE THREAD

**Issue by ivotron** [SeisSol/SeisSol#76]
When trying to execute the dataset available at https://zenodo.org/record/439946 using the master branch, we get the following:

```
--------------------------------------------------------------------------
Rank:        1 | Error   | invalid line in namelist Equations: SumatraRegions = 5 1 4 2 3 7 6 !region labels for high reso
Tue Jul 02 20:31:11, Warn:  Stack size of 8192 [kb] is lower than recommended minimum of 2097152 [kb]. 
Rank:        0 | Error   | invalid line in namelist Equations: SumatraRegions = 5 1 4 2 3 7 6 !region labels for high reso
```

We prepare the build environment as specified [here](https://github.com/popperized/scc18-workflows/blob/c73fece838c66fa3e3d4985d92175710992c379f/actions/seissol/Dockerfile) and invoke scons in [this way](https://github.com/popperized/scc18-workflows/blob/c73fece838c66fa3e3d4985d92175710992c379f/workflows/scc18/main.workflow#L5). We modified the [SConstruct file](https://github.com/SeisSol/SeisSol/compare/master...ivotron:container-friendly-mods) to (1) make openmpi's mpirun work OK inside a Docker container and (2) be able to compile with gcc8.

Would it be possible to know what modifications we need to do to the parameters in order to run it using the master branch?

thanks!

**Comment by uphoffc** [comment]
Hi,

we changed the model specification process since the SC17 version. The model parameters used to be hardcoded in Fortran, which we fully replaced with a flexible configuration file system.

So you only need to make the following changes to the parameter file.

Replace equations block:
```
&equations
MaterialFileName = '120_sumatra.yaml'
/
```
Replace dynamic rupture block:
```
&DynamicRupture
FL = 30
ModelFileName = 'f_120_sumatra.yaml'
t_0 = 0.5
GPwise = 1
XRef = 0.0
YRef = 0.0
ZRef = 1.0
refPointMethod = 1
OutputPointType = 4
/
```

In addition, please place the following files in your setup folder:
https://github.com/SeisSol/easi/blob/master/examples/120_sumatra.yaml
https://github.com/SeisSol/easi/blob/master/examples/f_120_sumatra.yaml
https://github.com/SeisSol/easi/blob/master/examples/120_initial_stress.yaml

Regards,
Carsten

**Comment by uphoffc** [comment]
So the following setup should work:

[sumatra_easi.zip](https://github.com/SeisSol/SeisSol/files/3353667/sumatra_easi.zip)

**Comment by ivotron** [comment]
thanks a lot! We'll give it a try and report back

**Comment by arshul** [comment]
Hey @uphoffc 
I Have been working on this project with @ivotron and I have followed the steps that you have told. But I am getting 
```bash
Rank:        0 | Error   | Unknown friction law           30
```
we have 
```
&DynamicRupture
FL = 30                     ! Friction law (0: none, 1:self-similar crack, 2:LSW, 3:RS (aging), 4:RS (slip))
ModelFileName = 'fault.yaml'
t_0 = 0.5
GPwise = 1                  ! elementwise =0 ; GPwise =1
XRef = 0.0                  ! Reference point
YRef = 0.0
ZRef = 1.0
refPointMethod = 1
OutputPointType = 4         ! Type (0: no output, 1: take GP's 2: 4 points per surface triangle, 3: output at certain pickpoints, 4: fault surface output, 5=4+3)
```
in the `parameters_zenodo_easi.par` file. 
I guess there's some typo here, what should be the correct value for `FL?`

**Comment by uphoffc** [comment]
Ah sorry, my setup is not up to date. Please use FL = 16 here.

**Comment by ivotron** [comment]
Sorry for the delay. After configuring as advised above, and tested, all is working well now (code is in https://github.com/popperized/seissol-workflows/tree/master/workflows/scc18) . Thanks a lot!
