### ISSUE TITLE
allocations of size 0 via MemoryAllocator in generated kernels version

### ISSUE THREAD

**Issue by alheinecke** [SeisSol/SeisSol#8]
In commit https://github.com/SeisSol/SeisSol/commit/6fc2b3a4674a464557f238fa3e577e0ff78aad28 I have added well-defined behavior if a size-0-allocation is requested: return NULL. This is the smallest subset of results for calls to different versions of malloc used in SeisSol and allows for a proper error handling.

However, I haven't fully checked if the code which calls the allocates with size 0 is able to handle NULL pointer correctly, but the correctness tests are passing so far.

**Comment by rettenbs** [comment]
Since we have not seen any issue with this change, I will close this bug. Feel free to reopen it, if this change caused any problems.
