### ISSUE TITLE
WaveFieldWriter works only in double precision

### ISSUE THREAD

**Issue by uphoffc** [SeisSol/SeisSol#80]
https://github.com/SeisSol/SeisSol/blob/master/src/ResultWriter/WaveFieldWriter.cpp#L113
https://github.com/SeisSol/SeisSol/blob/master/src/Solver/Interoperability.cpp#L686

**Comment by Thomas-Ulrich** [comment]
can't we substitute double by real in these 2 routines, try to compile SeisSol and change the declaration of all routines that complains about this change?

**Comment by uphoffc** [comment]
Yes, almost. E.g. this line is not going to complain, so one needs to be a bit more careful:
https://github.com/SeisSol/SeisSol/blob/master/src/ResultWriter/WaveFieldWriter.cpp#L400

But in principle it's not that hard, but has to be done and tested.

**Comment by ravil-mobile** [comment]
Could you, please, describe the problem according to the form that we established for issues?

**Comment by Thomas-Ulrich** [comment]
fixed by #315
