### ISSUE TITLE
Error: Detected Inf/NaN in volume output

### ISSUE THREAD

**Issue by Yonatan298** [SeisSol/SeisSol#850]
Hi, 
I would be glad if you could look at this bug/error I am getting.
I am trying to run a simulation with FL=34 using slip as an input to convert the output into initial stresses. However, I am getting the following error after 4.5 seconds:
[2796747.result.err.txt](https://github.com/SeisSol/SeisSol/files/11356895/2796747.result.err.txt)
[2796747.result.out.txt](https://github.com/SeisSol/SeisSol/files/11356897/2796747.result.out.txt)
**Expected behavior**
Run the simulation without issues
**To Reproduce**
[cascadia_kinematic.zip](https://github.com/SeisSol/SeisSol/files/11356914/cascadia_kinematic.zip)

Attaching a snapshot of the output (0.5 seconds):
![image](https://user-images.githubusercontent.com/107554177/235243474-d4e82a7e-89c8-4a79-b27d-c9fcd3b13a60.png)
This is the output for T_d. The values are reasonable, but I don't think it is correct. For example, the nan (yellow) shouldn't be there.
I am also attaching my code to generate the slip file (slip_gauss_hetro.nc). Maybe there is a problem with it. 
[Code_slip.zip](https://github.com/SeisSol/SeisSol/files/11357496/Code_slip.zip)

P.S
I already modified the effective_rise_time and acc_time in the code as suggested by @Thomas-Ulrich, but unfortunately, it didn't help.

**Comment by sebwolf-de** [comment]
Unfortunately, I can't reproduce your problem, see attached screenshot of T_d after 10s.
My settings: Release_dskx_6 stroud quadrature rule.
![Screenshot from 2023-05-02 12-14-57](https://user-images.githubusercontent.com/24592027/235640458-c9ccc4e4-5a53-47c5-b392-b238f949a6e8.png)
O4 also works.
Which settings do you use? Please tell me: 
* Machine
* Compiler, Modules
* Screenshot of `ccmake`

**Comment by Yonatan298** [comment]
Hi Sebastian, Thanks for taking a look! It seems it is working for you, so it must be 
the version of SeisSol I am using. This version is part of the seissol-env that @NicoSchlw installed in the new pn49ha project on SuperMuc (SeisSol_Release_dskx_4_elastic):
module use /hppfs/work/pn49ha/ru76tuj2/modules/linux-sles15-skylake_avx512/
module load seissol-env/develop-intel21-impi-x2b
compilers+models are here:
[bashrc.txt](https://github.com/SeisSol/SeisSol/files/11378992/bashrc.txt)
Can you please tell me what you mean by a screenshot of ccmake? I am using version 3.21.4 
I am running it on the SuperMuc. 

Thank you very much! Please let me know if anything else is needed.

**Comment by sebwolf-de** [comment]
I don't see anything particularly bothersome in your bashrc. 
About ccmake, if you haven't built SeisSol by yourself, we should ask Niko about the settings. If you've built SeisSol on your own, please go to your build directory, type `ccmake .` and send me the screenshot. Should look like the screenshot here: https://seissol.readthedocs.io/en/latest/compiling-seissol.html

**Comment by Yonatan298** [comment]
Hi Sebastian, Thanks! I didn't build SeisSol by myself, I am using the one that Niko built. Here is my log for ccmake . 
[cmake.txt](https://github.com/SeisSol/SeisSol/files/11386760/cmake.txt)
Apparently, I can do that even though I didn't build it myself?

**Comment by NicoSchlw** [comment]
Hi, the Spack module just provides the dependencies to build SeisSol, you still have to build it by yourself (and thereby chose the version). It seems that you load a SeisSol exe from this path:
`export PATH=/hppfs/work/pn68fi/di75qat/SeisSol/build-release:$PATH`
Is this your own SeisSol build?

**Comment by Yonatan298** [comment]
Hi Nico, Thanks for the comment! It was long ago, but you are right; I built it before. What is your suggestion?
Should I build it again using the latest version (git clone --recursive https://github.com/SeisSol/SeisSol.git)?

**Comment by NicoSchlw** [comment]
Yes, I would do that

**Comment by Yonatan298** [comment]
Thank you very much, Nico and Sebastian. I compiled the last version of SeisSol, and now everything works fine!
