### ISSUE TITLE
Out of memory access when `SurfaceOutputRefinement > 0` 

### ISSUE THREAD

**Issue by ravil-mobile** [SeisSol/SeisSol#854]
Hi all,

It seems to me that we allocate memory for `projectionMatrixMemory` and `projectionMatrixFromFace` without considering the surface refinement (i.e., `SurfaceOutputRefinement == 0`). 

https://github.com/SeisSol/SeisSol/blob/2c13dcccce9f7a4b6bcdc7a0f54dc231b7fa63a8/src/Solver/FreeSurfaceIntegrator.cpp#L160-L219

However, there is a loop over `numberOfSubTriangles`.

https://github.com/SeisSol/SeisSol/blob/2c13dcccce9f7a4b6bcdc7a0f54dc231b7fa63a8/src/Solver/FreeSurfaceIntegrator.cpp#L197-L199

where we increament `projectionMatrix[face]`. See, below

https://github.com/SeisSol/SeisSol/blob/2c13dcccce9f7a4b6bcdc7a0f54dc231b7fa63a8/src/Solver/FreeSurfaceIntegrator.cpp#L210

**Comment by krenzland** [comment]
I don't see where we're allocating the memory without taking the refinement into account. Because projectionMatrixMemorySize depends on the refinement. Assuming I'm reading it correctly?

**Comment by ravil-mobile** [comment]
I also didn't get why `projectionMatrixMemory` and `projectionMatrixFromFace` are unique pointers. We use `seissol::memory::allocate` which will delete the memory automatically at the end.

**Comment by ravil-mobile** [comment]
Found, the problem. 

```
   numberOfAlignedSubTriangles = seissol::kernels::getNumberOfAlignedReals(numberOfSubTriangles); 
```

which is used in 

```
projectionMatrixRow[nbf * numberOfAlignedSubTriangles] = average;
```

The problem is that I specified different alignment in SeisSol cmake (256) and YATeTo (128).
