### ISSUE TITLE
SeisSol fails if receiveroutputinterval is not set

### ISSUE THREAD

**Issue by uphoffc** [SeisSol/SeisSol#873]
**Describe the bug**
If receiveroutputinterval is omitted then SeisSol crashes with

```bash
terminate called after throwing an instance of 'std::length_error'
  what():  vector::reserve
```

The reason for this failure is that `receiverParameters.interval` is set to 1e+100 by default such that the receiver writer tries to pre-allocate a huge vector.

**Expected behavior**
Either make receiveroutputinterval non-optional or set the default interval to a sensible value (e.g. to EndTime, I think that used to be the previous default behaviour when readpar.F90 was still alive).

**Comment by uphoffc** [comment]
David could you have look, please?

**Comment by davschneller** [comment]
Yup, that got lost during the transfer. Here's the line in question: https://github.com/SeisSol/SeisSol/blame/4c638880ebb07df27526964acde58fe01d947a00/src/ResultWriter/inioutput_seissol.f90#L156

On it. I'll probably add the min operation to the `ReceiverWriter::init`.

Cf.  #874
