### ISSUE TITLE
Azure pipeline does not fail, although not all tests pass

### ISSUE THREAD

**Issue by sebwolf-de** [SeisSol/SeisSol#940]
**Describe the bug**
The azure pipeline reports a green checkmark, although the unit tests fail.

**Expected behavior**
If a unit test fails, the whole pipeline should fail.

**To Reproduce**
Look at the latest azure pipeline run and check the unit tests for viscoelastic2.

**Screenshots/Console output**
e.g. https://dev.azure.com/lukas0172/SeisSol/_build/results?buildId=5172&view=logs&j=7b8d196b-99e6-5e06-ae21-b38654797133&t=e69a43e3-13c1-5780-5210-c343f7e64b6e

**Comment by krenzland** [comment]
The pipeline doesn't check the result for make test:
https://github.com/SeisSol/SeisSol/blob/7fde47786f10aebbb4225f4c5125829ea9b541a1/azure-pipelines-seissol-template.yml#L73

**Comment by sebwolf-de** [comment]
Fixes with #941
