### ISSUE TITLE
Replacing References by Pointers in LocalData struct

### ISSUE THREAD

**Issue by kirchhart-intel** [SeisSol/SeisSol#947]
Hello SeisSol team!

my name is Matthias Kirchhart, I am an Intel employee working together with @uphoffc on SeisSol.

I suggest replacing references with pointers in the `LocalData` struct, and would like to discuss how to implement this.

### Rationale

For better performance, in the long run, it makes sense to shift from unified shared memory allocations to explicitly managed allocations using `sycl::malloc_device()` and `sycl::malloc_host()`. It allows for more fine-grained control when and which data is transferred between the host system and GPU devices.

### Description

For starters, I want to implement explicit data transfers, i.e., memcpy, between host and GPU in the `calcReceivers()` routine in [src/Kernels/Receiver.cpp](https://github.com/SeisSol/SeisSol/blob/master/src/Kernels/Receiver.cpp). 

For this I need to copy the required DOFs from the GPU to a local buffer on the host, and pass a `LocalData` object referring to that buffer to `computeAder()`. The problem is that `LocalData` objects only contain references and not pointers. So I cannot just create a copy of the `LocaData` object and have its dofs member “point-to” the local memory.

I would like to suggest the following solution:

```
struct LocalData
{
    real *member_ptr;
    
    real& member() const noexcept { return *member_ptr; }
};
```

This looks like a “clean” solution to me. However, it requires to change all the code in SeisSol that uses LocalData. Each time the old `data.member` is accessed, the we now need to write `data.member()` with the function call brackets.

Would this be okay for you? If so, I would start preparing the necessary changes and create a pull request once ready.

An alternative could be to have two members: one a reference, the other a pointer. This however, would increase memory consumption and lead to inconsistencies if the pointer member is changed.

I am looking forward to your feedback.

### General information
- [x] I have searched the issues of this repo and believe this is not a duplicate

**Comment by krenzland** [comment]
Hi Matthias, 
I see no problem with using pointers there. The manual prefetching is okay. I would make this optional as it may be beneficial on some hardware to not prefetch it explicitly (e.g. Grace Hopper?)

**Comment by davschneller** [comment]
Hi, a small question: how would you plan to implement the prefetching/copying exactly?

**Comment by uphoffc** [comment]
@krenzland: You cannot avoid the copy in any case. We know that the DOFS reside on the GPU (all DOFS are touched before in local / neighboring integration) so there must be a physical copy over PCIe or another link. It would only make a difference if you have a chip where both CPU and GPU access the same physical memory. So the only real difference is that you have a few lines of additional code that make the transfer explicit in the code.

@davschneller: Using SYCL copy or memcpy commands.

**Comment by krenzland** [comment]
Yes, but the NVLINK between CPU/GPU on Grace Hopper has a bandwidth of 900GB/s, which is larger than the CPU memory bandwidth of ca. 500GB/s.
How well this works in practice is probably a very different topic ;)
