### ISSUE TITLE
compilation error in Supermuc NG

### ISSUE THREAD

**Issue by daisy20170101** [SeisSol/SeisSol#98]
Hi,
I compiled latest SeisSol on NG and got error log as:
..
Checking for C library metis... (cached) yes
Checking whether pkg-config knows asagi... (cached) yes
Checking for C++ library asagi... (cached) yes
TypeError: unsupported operand type(s) for +: 'filter' and 'list':
  File "/hppfs/work/pr63qo/di52lak2/easi_2019-5/SeisSol/SConstruct", line 663:
    SConscript('generated_code/SConscript', variant_dir=env['buildDir'] + '/generated_code', duplicate=0)
  File "/dss/dsshome1/lrz/sys/tools/scons/3.0.1/lib/scons-3.0.1/SCons/Script/SConscript.py", line 614:
    return method(*args, **kw)
  File "/dss/dsshome1/lrz/sys/tools/scons/3.0.1/lib/scons-3.0.1/SCons/Script/SConscript.py", line 551:
    return _SConscript(self.fs, *files, **subst_kw)
  File "/dss/dsshome1/lrz/sys/tools/scons/3.0.1/lib/scons-3.0.1/SCons/Script/SConscript.py", line 256:
    call_stack[-1].globals)
  File "/hppfs/work/pr63qo/di52lak2/easi_2019-5/SeisSol/generated_code/SConscript", line 81:
    obj = env.Object(cpp, CFLAGS=cflags, CXXFLAGS=cxxflags + ['-mno-red-zone'])

The modules i used are:
Currently Loaded Modulefiles:
 1) admin/1.0            6) cmake/3.6                                  11) libszip/2.1.1   16) itac/2019          21) gcc/8.3           
 2) tempdir/1.0          7) slurm_setup/default                        12) numactl/2.0.11  17) advisor_xe/2019    22) python/3.5_intel  
 3) spack/release/19.1   8) parmetis/4.0.3-intel-impi-i64-r64          13) intel/19.0      18) amplifier_xe/2019  
 4) lrz/default          9) metis/5.1.0-intel-i64-r64                  14) mkl/2019        19) inspector_xe/2019  
 5) scons/3.0.1         10) netcdf/4.6.1-intel-impi-hdf5v1.8-parallel  15) mpi.intel/2019  20) devEnv/Intel/2019 

Any idea?

**Comment by Thomas-Ulrich** [comment]
@krenzland 
That's your commit.

**Comment by daisy20170101** [comment]
Thanks!
