### ISSUE TITLE
seissol does not compile on heisenbug , gpu-version with the new seissol (in development ) spack package

### ISSUE THREAD

**Issue by Thomas-Ulrich** [SeisSol/SeisSol#991]
**Describe the bug**

seissol does not compile on heisenbug , gpu-version with the new (in development )  seissol spack package.

**Expected behavior**
seissol compiles.

**To Reproduce**
I m trying to install seissol with spack and this PR, adding the seissol package:
https://github.com/spack/spack/pull/41176
When trying to compile seissol on heisenbug for gpus, with:
```spack install -j 60 seissol convergence_order=6 dr_quad_rule=dunavant equations=viscoelastic2 number_of_mechanisms=3 +cuda cuda_arch=86 device_backend=cuda %gcc```

I get the following error:

```
  >> 658     /tmp/ulrich/spack-stage/spack-stage-seissol-1.1.2-as2sa7jp4ho7phk3iych7ltphtskbquz/spack-src/src/Initializer/typedefs.hpp:310:20: error: 'plusFluxMatrices' in namespace 'seissol::tensor' does not
              name a type
     659       310 |   seissol::tensor::plusFluxMatrices::Container<real const*> plusFluxMatrices;
```

[spack-build-out.txt](https://github.com/SeisSol/SeisSol/files/13415103/spack-build-out.txt)

**Comment by Thomas-Ulrich** [comment]
workaround by specifying gemm_tools="LIBXSMM-PSpaMM"

**Comment by davschneller** [comment]
Unfortunately, viscoelastic simulations are not (yet) supported with GPUs—hopefully soon.
