### ISSUE TITLE
xdmf of faultoutput can't not be opened in windows 10

### ISSUE THREAD

**Issue by Jing-Lee-tj** [SeisSol/SeisSol#996]
* How do I set up a model (mesh, material parameters, ...).
       I ran a simple earthquake rupture example and turn on the faultoutput as the result. But when I tried to open the fault.xdmf file using paraview on a windows system, I encountered the following error:
```
ERROR: In vtkXdmfReader.cxx, line 476
vtkXdmfReader (000001180D5A23B0): Failed to read data.

ERROR: In vtkExecutive.cxx, line 730
vtkPVCompositeDataPipeline (000001180D42D0B0): Algorithm vtkFileSeriesReader (000001180CF5D690) returned failure for request: vtkInformation (000001181595CAE0)
  Debug: Off
  Modified Time: 472089
  Reference Count: 1
  Registered Events: (none)
  Request: REQUEST_DATA
  FORWARD_DIRECTION: 0
  ALGORITHM_AFTER_FORWARD: 1
  FROM_OUTPUT_PORT: 0
```
  I tried to install python and seissolxdmf on my system and I could run the code sample on the home page to get the result output；
  And I can open the xdmffile of mesh grid well;
  But the problem is ,How can I read xdmffile of faultoutput directly with papraview on windows system.

**Comment by Thomas-Ulrich** [comment]
could be that your seissol is compiled with hdf5 1.10 or 1.12 and your paraview with hdf5 1.8.
Try using xdmfWriterBackend = 'posix'  in the parameter file (if not already set).

**Comment by FURUNZ** [comment]
In the example of tpv33, I encountered the same problem where the file named tpv5-fault.xdmf cannot be directly opened with ParaView. Will the output folder also generate a corresponding .h5 file? I have also tried the method "Try using xdmfWriterBackend = 'posix' in the parameter file."

**Comment by Thomas-Ulrich** [comment]
@FURUNZ : if xdmfWriterBackend = 'posix' , then no h5 are created but several folder with *.bin in it.
I close the issue. Please reopen if you still have the problem.
